### ISSUE TITLE
JDK13 : Test failures on  test-godaddy-win2016-x64-2 due to unable to clean workspace

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1086]
Job running : https://ci.adoptopenjdk.net/job/Test_openjdk13_j9_sanity.openjdk_x86-64_windows/106/console

Failing with error -

Cloning repository https://github.com/AdoptOpenJDK/openjdk-tests.git
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk13_j9_sanity.openjdk_x86-64_windows\openjdk-tests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:90)
	at hudson.Util.deleteContentsRecursive(Util.java:259)
	at hudson.Util.deleteContentsRecursive(Util.java:248)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:728)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)

**Comment by sxa555** [comment]
There were a lot of processes lying around on that machine. I have rebooted it (as it was likely to be quicker than deleting them...) and hopefully that will resolve the issue for now.
