### ISSUE TITLE
JTReg Test Failure: java/lang/invoke/VarHandles/... on test-aws-rhel76-armv8-#

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#1118]
Version: JDK11+ (Hotspot since openj9 doesn't have jit support for arm64 yet)
Only occurs on these arm64 machines

Failed run: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_aarch64_linux/114/
Passed run on test-packet-armv8-ubuntu-16-04:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_aarch64_linux/

Tests:
```
java/lang/invoke/VarHandles/VarHandleTestAccessBoolean.java
java/lang/invoke/VarHandles/VarHandleTestAccessByte.java
java/lang/invoke/VarHandles/VarHandleTestAccessChar.java
java/lang/invoke/VarHandles/VarHandleTestAccessDouble.java
java/lang/invoke/VarHandles/VarHandleTestAccessFloat.java
java/lang/invoke/VarHandles/VarHandleTestAccessInt.java
java/lang/invoke/VarHandles/VarHandleTestAccessLong.java
java/lang/invoke/VarHandles/VarHandleTestAccessShort.java
java/lang/invoke/VarHandles/VarHandleTestAccessString.java
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsDouble.java
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsFloat.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessBoolean.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessByte.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessChar.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessDouble.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessFloat.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessInt.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessLong.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessShort.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessString.java
```

Example output:
```
java/lang/invoke/VarHandles/VarHandleTestAccess[TYPE].java

run testng/othervm -Diters=10 -Xint VarHandleTestAccessChar [Passes]
run testng/othervm -Diters=20000 -XX:TieredStopAtLevel=1 VarHandleTestAccessChar [Passes]
run testng/othervm -Diters=20000 VarHandleTestAccessChar [Passes]
run testng/othervm -Diters=20000 -XX:-TieredCompilation VarHandleTestAccessChar [Fails]

22:40:25  test VarHandleTestAccessChar.testAccess("VarHandle -> Array", VarHandle -> Array): failure
22:40:25  java.lang.AssertionError: weakCompareAndSetPlain char expected [true] but found [false]
22:40:25  	at org.testng.Assert.fail(Assert.java:94)
22:40:25  	at org.testng.Assert.failNotEquals(Assert.java:496)
22:40:25  	at org.testng.Assert.assertEquals(Assert.java:125)
22:40:25  	at org.testng.Assert.assertEquals(Assert.java:288)
22:40:25  	at VarHandleTestAccessChar.testArray(VarHandleTestAccessChar.java:979)
22:40:25  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:405)
22:40:25  	at VarHandleTestAccessChar.testAccess(VarHandleTestAccessChar.java:225)
```

```
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccess[TYPE].java

run testng/othervm -Diters=20000 VarHandleTestMethodHandleAccessBoolean 

22:43:01  java.lang.AssertionError: weakCompareAndSet boolean expected [true] but found [false]
22:43:01  	at org.testng.Assert.fail(Assert.java:94)
22:43:01  	at org.testng.Assert.failNotEquals(Assert.java:496)
22:43:01  	at org.testng.Assert.assertEquals(Assert.java:125)
22:43:01  	at org.testng.Assert.assertEquals(Assert.java:288)
22:43:01  	at VarHandleTestMethodHandleAccessBoolean.testArray(VarHandleTestMethodHandleAccessBoolean.java:738)
22:43:01  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:405)
22:43:01  	at VarHandleTestMethodHandleAccessBoolean.testAccess(VarHandleTestMethodHandleAccessBoolean.java:116)

22:43:01  java.lang.AssertionError: weakCompareAndSetRelease boolean expected [true] but found [false]
22:43:01  	at org.testng.Assert.fail(Assert.java:94)
22:43:01  	at org.testng.Assert.failNotEquals(Assert.java:496)
22:43:01  	at org.testng.Assert.assertEquals(Assert.java:125)
22:43:01  	at org.testng.Assert.assertEquals(Assert.java:288)
22:43:01  	at VarHandleTestMethodHandleAccessBoolean.testArray(VarHandleTestMethodHandleAccessBoolean.java:728)
22:43:01  	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:405)
22:43:01  	at VarHandleTestMethodHandleAccessBoolean.testAccess(VarHandleTestMethodHandleAccessBoolean.java:116)
```

**Comment by Willsparker** [comment]
Looks like it's okay now : 
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_aarch64_linux/210/ (as well as most of the other runs)
Unless I'm missing something, @adam-thorpe  ?

**Comment by adam-thorpe** [comment]
These tests don't appear to be running in sanity and aren't excluded so my guess is that they were moved to tier 2 while ago, closing.
