### ISSUE TITLE
Multicasting Test Failures on test-godaddy-win2016-x64-1 to 4

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#1153]
Multicast tests are returning localhost ipv4 and ipv6 addresses. Potentially related to other hosting problems with godaddy machines

Failures are seen on jdk14, I know `MulticastSendReceiveTests.java` failure is only re-createable on jdk14 due to a difference in test material, not sure about the other tests

**java/net/MulticastSocket/IPMulticastIF.java**
```
run testng IPMulticastIF [PASS]
run testng/othervm -Djava.net.preferIPv4Stack=true IPMulticastIF [PASS]
run testng/othervm -Djava.net.preferIPv6Addresses=true IPMulticastIF [FAIL]

--- testSetGetInterfaceBound bindAddr=[s160-153-234-27/[0:0:0:0:0:0:0:1]:0], nif=[name:eth2 (Microsoft KM-TEST Loopback Adapter)]
01:07:09  test IPMulticastIF.testSetGetInterfaceBound(java.net.InetSocketAddress@3e72d39a, java.net.NetworkInterface@17c88e2b): failure
01:07:09  java.lang.AssertionError: expected [name:eth2 (Microsoft KM-TEST Loopback Adapter)] but found [name:::]

--- testSetGetInterfaceBound bindAddr=[s160-153-234-27/[0:0:0:0:0:0:0:1]:0], nif=[name:eth1 (Red Hat VirtIO Ethernet Adapter)]
01:07:09  test IPMulticastIF.testSetGetInterfaceBound(java.net.InetSocketAddress@f844c8ab, java.net.NetworkInterface@c105cba7): failure
01:07:09  java.lang.AssertionError: expected [name:eth1 (Red Hat VirtIO Ethernet Adapter)] but found [name:::]

...
```

**java/net/MulticastSocket/TestInterfaces.java**
```
01:07:28  NetworkInterface under test name:eth1 (Red Hat VirtIO Ethernet Adapter)
01:07:28  Display name: Red Hat VirtIO Ethernet Adapter
01:07:28  Name: eth1
01:07:28  InetAddress: /10.217.192.225
01:07:28  InetAddress: /160.153.234.27
01:07:28  Up? true
01:07:28  Loopback? false
01:07:28  PointToPoint? false
01:07:28  Supports multicast? true
01:07:28  Virtual? false
01:07:28  Hardware address: [-6, 22, 62, 99, -15, 83]
01:07:28  MTU: 1500
01:07:28  Index: 3

01:07:28  MulticastSocket.getInterface returned: /127.0.0.1
01:07:28  Failed! Expected: /10.217.192.225

01:07:28  MulticastSocket.getInterface returned: /127.0.0.1
01:07:28  Failed! Expected: /160.153.234.27

01:07:28  MulticastSocket.getNetworkInterface returned: name:lo (Software Loopback Interface 1)
01:07:28  Failed! Expected: name:eth1 (Red Hat VirtIO Ethernet Adapter)

-> Tests are returning localhost:
01:07:28  Display name: Software Loopback Interface 1
01:07:28  Name: lo
01:07:28  InetAddress: /127.0.0.1
01:07:28  InetAddress: /0:0:0:0:0:0:0:1
01:07:28  Up? true
01:07:28  Loopback? true
01:07:28  PointToPoint? false
01:07:28  Supports multicast? true
01:07:28  Virtual? false
01:07:28  Hardware address: null
01:07:28  MTU: -1
01:07:28  Index: 1
```

**java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java**
```
01:19:23  STDOUT:
01:19:23  
01:19:23  Test DatagramChannel to UNSPEC socket
01:19:23  join 225.4.5.6 @ eth2
01:19:23  Send message from 169.254.254.28 -> group 225.4.5.6 (id=0x7747ccae)
01:19:23  Waiting to receive message
01:19:23  Received message from /0:0:0:0:0:ffff:a9fe:fe1c%4 (id=0x7747ccae)
01:19:23  Message ignored (wrong sender)
01:19:23  Waiting to receive message
01:19:23  STDERR:
01:19:23  java.lang.RuntimeException: Expected message not received
01:19:23  	at MulticastSendReceiveTests.receiveDatagram(MulticastSendReceiveTests.java:110)
01:19:23  	at MulticastSendReceiveTests.test(MulticastSendReceiveTests.java:187)
01:19:23  	at MulticastSendReceiveTests.main(MulticastSendReceiveTests.java:267)
01:19:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:19:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:19:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:19:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
01:19:23  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
01:19:23  	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by sxa555** [comment]
I believe only George has access to these systems

**Comment by karianna** [comment]
Godaddy hosts are gone.
