### ISSUE TITLE
build-siteox-solaris10u9-x64-1 failing to do some https downloads (cert error)

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1194]
From https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot job 231
```

BUILD_CONFIG[WORKSPACE_DIR]="/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace"
Running gradle with /usr/jdk/openjdk11.0.2/
Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:642)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:461)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:361)
[...]
```

**Comment by sxa555** [comment]
This now appears to be working but there are no updates in this ticket - what was done to resolve it?

**Comment by sxa555** [comment]
@gdams can you log the fix here as I'm assuming you did something

**Comment by gdams** [comment]
this was almost certainly the same issue with the date being incorrect.
