### ISSUE TITLE
test-aws-ubuntu1604-armv8-1 connection problem

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#1236]
Throws this every time a connection the machine is attempted. 
Eg. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2645/console

```
Running on test-aws-ubuntu1604-armv8-1 in /home/jenkins/workspace/Grinder
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-aws-ubuntu1604-armv8-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1069)
		at hudson.FilePath.act(FilePath.java:1058)
		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:122)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:826)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1156)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy9
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1015)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1001)
	at hudson.remoting.RemoteInvocationHandler.wrap(RemoteInvocationHandler.java:167)
	at hudson.remoting.Channel.export(Channel.java:768)
	at hudson.remoting.Channel.export(Channel.java:731)
	at org.jenkinsci.plugins.gitclient.LegacyCompatibleGitAPIImpl.writeReplace(LegacyCompatibleGitAPIImpl.java:204)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:564)
	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1220)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1137)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:263)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:272)
	at hudson.remoting.UserRequest.perform(UserRequest.java:222)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:844)
Caused: java.io.IOException: Remote call on test-aws-ubuntu1604-armv8-1 failed
	at hudson.remoting.Channel.call(Channel.java:961)
	at hudson.FilePath.act(FilePath.java:1069)
	at hudson.FilePath.act(FilePath.java:1058)
	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:122)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:835)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:826)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1156)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sxa555** [comment]
Removed that definition in jenkins as it was incorrect
