### ISSUE TITLE
build-marist-rhel77-s390x-2 Out of Space

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1243]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-linux-s390x-openj9-linuxXL/22/console

```
Error: java.io.IOException: No space left on device
java.io.UncheckedIOException: java.io.IOException: No space left on device
	at jdk.jlink/jdk.tools.jlink.internal.ByteArrayResourcePoolEntry.write(ByteArrayResourcePoolEntry.java:69)
	at jdk.jlink/jdk.tools.jlink.internal.ImageFileCreator.lambda$generateJImage$4(ImageFileCreator.java:239)
	at jdk.jlink/jdk.tools.jlink.internal.ImageFileCreator$$Lambda$237/0000000000000000.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at jdk.jlink/jdk.tools.jlink.internal.ImageFileCreator.generateJImage(ImageFileCreator.java:238)
	at jdk.jlink/jdk.tools.jlink.internal.ImageFileCreator.writeImage(ImageFileCreator.java:161)
	at jdk.jlink/jdk.tools.jlink.internal.ImageFileCreator.create(ImageFileCreator.java:100)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask$ImageHelper.retrieve(JlinkTask.java:851)
	at jdk.jlink/jdk.tools.jlink.internal.ImagePluginStack.operate(ImagePluginStack.java:206)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:408)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:272)
	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:54)
	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)
```

**Comment by sxa555** [comment]
Cleared pr-tester job workspaces
