### ISSUE TITLE
JTReg Failures: well known file exceptions 

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1274]
**Describe the bug**
On mac machines for 11 and 14 hotspot the following tests are failing due to pretty much the same error 
```
com/sun/jdi/ProcessAttachTest.java
jdk/jfr/jcmd/TestJcmdStartStopDefault.java
```

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
1. Go to https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder
2. Kick off a grinder with these parameters 
- JDK11: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=x86-64_mac&TARGET=jdk_svc_sanity_0
- JDK14: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=14&JDK_IMPL=hotspot&BUILD_LIST=openjdk&PLATFORM=x86-64_mac&TARGET=jdk_svc_sanity_0
3. See error in console log

**Expected behavior**
Tests pass

**Screenshots**
ProcessAttachTest.java
```
01:55:19  java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid18038 is not secure: file's group should be the current group (which is -1) but the group is 0
01:55:19  	at jdk.jdi/com.sun.tools.jdi.ProcessAttachingConnector.attach(ProcessAttachingConnector.java:106)
01:55:19  	at ProcessAttachTest.tryDebug(ProcessAttachTest.java:107)
01:55:19  	at ProcessAttachTest.runTest(ProcessAttachTest.java:87)
01:55:19  	at ProcessAttachTest.main(ProcessAttachTest.java:66)
01:55:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:55:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:55:19  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:55:19  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:55:19  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
01:55:19  	at java.base/java.lang.Thread.run(Thread.java:834)
```

TestJcmdStartStopDefault.java
```
Standard Output: 

Running DCMD 'JFR.start' through 'PidJcmdExecutor'
Executing command '[/Users/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/../bin/jcmd, 18106, JFR.start]'
Command returned with exit code 1
---------------- stdout ----------------
18106:

---------------- stderr ----------------
java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid18106 is not secure: file's group should be the current group (which is -1) but the group is 0
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:108)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at jdk.jcmd/sun.tools.jcmd.JCmd.executeCommandForPid(JCmd.java:114)
	at jdk.jcmd/sun.tools.jcmd.JCmd.main(JCmd.java:98)

----------------------------------------
    
Standard Error:

 stdout: [18106:
];
 stderr: [java.io.IOException: well-known file /var/folders/rt/8_by_h8n5g9d5jhp66cf_7d80000gr/T/.java_pid18106 is not secure: file's group should be the current group (which is -1) but the group is 0
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:108)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at jdk.jcmd/sun.tools.jcmd.JCmd.executeCommandForPid(JCmd.java:114)
	at jdk.jcmd/sun.tools.jcmd.JCmd.main(JCmd.java:98)
]
 exitValue = 1

java.lang.RuntimeException: Expected to get exit value of [0]

	at jdk.test.lib.process.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:396)
	at jdk.jfr.jcmd.JcmdHelper.jcmd(JcmdHelper.java:111)
	at jdk.jfr.jcmd.JcmdHelper.jcmd(JcmdHelper.java:116)
	at jdk.jfr.jcmd.TestJcmdStartStopDefault.main(TestJcmdStartStopDefault.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Additional context**
It appears to be a perm issue on the surface. The test is creating items in the `/var/`directory which is a sensitive directory to be creating files in. Its possible that this is likely caused by the the debugger that the test creates [not having the same perms as the java_pid file](https://stackoverflow.com/questions/9100149/jstack-well-known-file-is-not-secure).

**Comment by gdams** [comment]
This is to do with the fact that Jenkins isn't it a security group:

test-macincloud-macos1014-x64-:
```bash
test-macincloud-macos1014-x64-1:~ admin$ dscl . search /Groups GroupMembership jenkins
test-macincloud-macos1014-x64-1:~ $ 
```

test-macincloud-macos1010-x64-1
```bash
test-macincloud-macos1010-x64-1:~ admin$ dscl . search /Groups GroupMembership jenkins
com.apple.sharepoint.group.1		GroupMembership = (
    jenkins
)
```

**Comment by gdams** [comment]
testing with a group added to Jenkins user:

https://ci.adoptopenjdk.net/job/Grinder/2812/

**Comment by gdams** [comment]
test failed, trying with a reboot first: https://ci.adoptopenjdk.net/job/Grinder/2813/console

**Comment by gdams** [comment]
hmm maybe not. `TMPDIR` is defined on all the machines. On macOS it seems to default to some weird `/var/` dir

**Comment by gdams** [comment]
trying with `_JAVA_OPTIONS: -Djava.io.tmpdir=/tmp`

**Comment by gdams** [comment]
hmm so the test shows that it picked up the top dir:

```bash
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/tmp
```

but then runs the test without it:

```bash
12:38:37  Command line: [/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/../bin/java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n -classpath /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_158686425467/jdk_svc_sanity_0/work/classes/0/com/sun/jdi/ProcessAttachTest.d ProcessAttachTestTarg ]
```

@smlambert any idea why?

**Comment by smlambert** [comment]
As per our Slack conversation, test job sets JVM_OPTIONS for each run, you can append additional options by using EXTRA_OPTIONS param (or replace the entire set by using JVM_OPTIONS).

<img width="538" alt="Screen Shot 2020-04-14 at 10 42 27 AM" src="https://user-images.githubusercontent.com/2836948/79237871-a9cad000-7e3c-11ea-9fd1-74eb2feb2898.png">

**Comment by gdams** [comment]
using EXTRA_OPTIONS https://ci.adoptopenjdk.net/job/Grinder/2821/

**Comment by gdams** [comment]
setting `JVM_OPTIONS:  -Djava.io.tmpdir=/tmp` resolved this. @smlambert can you look at setting all the mac tests to have `/tmp` as the temp dir rather than the weird `/var`

**Comment by smlambert** [comment]
Adding this from our DM in Slack for search-ability later:

Command definition for that test:
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/playlist.xml#L721-L729

Command that gets run:
command that gets run:
08:44:08  	"/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/..//bin/java" -Xmx512m -jar "/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/openjdk/jtreg/lib/jtreg.jar" \
08:44:08  	-agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:2 -vmoptions:"-Xmx512m  -Djava.io.tmpdir=/tmp" \
08:44:08  	-w ""/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_15869546463959/jdk_svc_sanity_0"/work" \
08:44:08  	-r "/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/openjdk/report" \
08:44:08  	-jdk:"/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/../" \
08:44:08  	-exclude:"/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../openjdk/openjdk-jdk/test/jdk/ProblemList.txt" \
08:44:08  	-exclude:"/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/openjdk/ProblemList_openjdk11.txt" \
08:44:08  	"/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../openjdk/openjdk-jdk/test/jdk:jdk_svc_sanity"; \

EXTRA_OPTIONS is appended to JVM_OPTIONS, which gets fed to jtreg via -vmoptions parameter (see https://openjdk.java.net/jtreg/vmoptions.html)

**Comment by M-Davies** [comment]
Exclude PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1734

**Comment by karianna** [comment]
@M-Davies I've landed that PR - can this be closed in that case?

**Comment by gdams** [comment]
@karianna probably not, the issue still exists, we've just skipped the test for now

**Comment by M-Davies** [comment]
This is also occurring for `com/sun/jdi/ProcessAttachTest.sh` on `test-macincloud-macos1013-x64-*` machines (`test-macincloud-macos1010-x64-*` machines are unaffected). 

@gdams Are there any differences between the 1010 and 1013 machines that could cause this? Maybe that'll lead you to the solution for this?
```
19:29:52  Exception in thread "main" java.io.IOException: well-known file /var/folders/rc/_hq7pkh54kb0dk8vvlt34pz00000gr/T/.java_pid88080 is not secure: file's group should be the current group (which is -1) but the group is 0
19:29:52  	at com.sun.tools.jdi.ProcessAttachingConnector.attach(ProcessAttachingConnector.java:104)
19:29:52  	at ProcessAttachDebugger.main(ProcessAttachDebugger.java:68)
19:29:52  Waiting for port file to be written...
19:29:52  Waiting 1 second(s) ...
19:29:52  Waiting 2 second(s) ...
19:29:52  Waiting 3 second(s) ...
19:29:52  Waiting 4 second(s) ...
19:29:52  Waiting 5 second(s) ...
...
Timeout!
```

Exclude PR: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1741

**Comment by smlambert** [comment]
Same core issue for failures in a system test target HCRLateAttachWorkload_previewEnabled ([deep history](https://trss.adoptopenjdk.net/deepHistory?testId=5f86346011d26031c1076ecb) noting it passes on macos1010 but not on macos1012/13/14 machines).  This error will occur in any test that invokes jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)

stderr Exception in thread "main" java.io.IOException: well-known file /var/folders/h1/b_v48zpd1zd54jblxnx58p3r0000gr/T/.java_pid1386 is not secure: file's group should be the current group (which is -1) but the group is 0
[2020-10-13T21:04:53.246Z] AG  stderr 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)

**Comment by lumpfish** [comment]
There are suggestions in the preceding comments that this may be due to java.io.tmpdir not being set to /tmp. I have tweaked the openjdk-systemtest HCRLateAttachWorkload test to explicitly set java.io.tmpdir to /tmp but that does not seem to be used by hotspot for the location of the `.java_pid` files.

This is the output from the tweaked (and still failing) test.
```
16:54:39  STF 16:54:39.202 - +------ Step 2 - Run StringModifierAgent
16:54:39  STF 16:54:39.202 - | Start background process
16:54:39  STF 16:54:39.202 - |   Program:     /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/java
16:54:39  STF 16:54:39.202 - |   Mnemonic:    AG
16:54:39  STF 16:54:39.202 - |   Echo:        ECHO_ON
16:54:39  STF 16:54:39.202 - |   Expectation: CLEAN_RUN within 10m
16:54:39  STF 16:54:39.202 - |
16:54:39  STF 16:54:39.204 - Running command: /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/bin/java -Djava.io.tmpdir=/tmp --enable-preview -classpath /Users/jenkins/workspace/Grinder/jvmtest/system/openjdk-systemtest/openjdk.test.debugging/bin/StringModifierAgent.jar:/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/Contents/Home/lib/tools.jar net.adoptopenjdk.test.hcrAgent.agent.Attacher 46418 /Users/jenkins/workspace/Grinder/jvmtest/system/openjdk-systemtest/openjdk.test.debugging/bin/StringModifierAgent.jar duration=240
16:54:39  STF 16:54:39.204 - Redirecting stderr to /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_1603209272942/HCRLateAttachWorkload_previewEnabled_0/20201020-165433-HCRLateAttachWorkload/results/2.AG.stderr
16:54:39  STF 16:54:39.204 - Redirecting stdout to /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_1603209272942/HCRLateAttachWorkload_previewEnabled_0/20201020-165433-HCRLateAttachWorkload/results/2.AG.stdout
16:54:39  STF 16:54:39.207 - 
16:54:39  STF 16:54:39.207 - +------ Step 3 - Wait for Agent to complete, followed by the MiniMix test seconds later.
16:54:39  STF 16:54:39.207 - | Wait for processes to meet expectations
16:54:39  STF 16:54:39.207 - |   Processes: [LT, AG]
16:54:39  STF 16:54:39.207 - |
16:54:39  STF 16:54:39.207 - Monitoring processes: AG  LT 
16:54:41  AG  16:54:40 > Will attempt to attach to JVM with pid 46418
16:54:41  AG  16:54:40 > Attach will be done using agent jar file: /Users/jenkins/workspace/Grinder/jvmtest/system/openjdk-systemtest/openjdk.test.debugging/bin/StringModifierAgent.jar
16:54:41  AG  stderr Exception in thread "main" java.io.IOException: well-known file /var/folders/rc/_hq7pkh54kb0dk8vvlt34pz00000gr/T/.java_pid46418 is not secure: file's group should be the current group (which is -1) but the group is 0
16:54:41  AG  stderr 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.checkPermissions(Native Method)
16:54:41  AG  stderr 	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:108)
16:54:41  AG  stderr 	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
16:54:41  AG  stderr 	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
16:54:41  AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:70)
16:54:41  STF 16:54:41.477 - **FAILED** Process AG  ended with exit code (1) and not the expected exit code/s (0)
```

**Comment by lumpfish** [comment]
Previous similar errors seem to have been due to `.java_pid<nnn>` files having been left on machines but created by different users to the current one - e.g. https://bugs.openjdk.java.net/browse/JDK-8170423.
However, since this only happens on osx versions 12, 13 and 14 and is repeatable I suspect that it not the case here.
The error message suggests the `.java_pid<nnn>` file is created with "group 0" but the group of the current user is "group -1".
Can someone log into one of the test machines and run the test so that the attributes of the file can be checked.
Also it would be useful to know if this failure is unique to the AdoptOpenJDK machine setups.  I don't have access to a local osx machine myself.  If someone could please run one of the failing tests locally and see whether they also fail that would be useful information too.

**Comment by smlambert** [comment]
@lumpfish - I have not seen this type of failure recently... have you?  

I am wondering if some config change has occurred to make this less noticeable?

**Comment by karianna** [comment]
Suggest reversing https://github.com/AdoptOpenJDK/openjdk-tests/pull/1734 and seeing if that now passes.

**Comment by lumpfish** [comment]
I'm not aware of anything that's been done to make it pass, but the system test HCRLateAttachWorkloadTest reported as failing above does now pass on an osx 1015 machine (test-nine-macos1015-x64-2): https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_x86-64_mac/486/consoleFull

As observed in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1274#issuecomment-806580597, it looks like the openjdk tests which were getting this error were excluded.

**Comment by sxa** [comment]
Grinder re-run from the ealiier parameters is now running ok as per [1021](https://ci.adoptopenjdk.net/job/Grinder/1021/) [1022](https://ci.adoptopenjdk.net/job/Grinder/1022) [1023](https://ci.adoptopenjdk.net/job/Grinder/1023/) - do we need further work on this or can it now be closed (or retested if the test has actually been disabled)? I see it's been re-assiged to @smlambert ...

**Comment by smlambert** [comment]
Someone should remove the 4 exclusions and rerun tests:
How to find exclusions?  search for `https://github.com/adoptium/infrastructure/issues/1274` in aqa-tests repo results in 4 findings:
- ProblemList_openjdk8.txt
- ProblemList_openjdk11.txt
- ProblemList_openjdk14.txt
- ProblemList_openjdk15.txt

**Comment by sxa** [comment]
@karianna Was there a reason why this was re-assigned to Shelley in March?

**Comment by smlambert** [comment]
Created https://github.com/adoptium/aqa-tests/issues/2716 as good first issue to verify this infra issue has been addressed.

**Comment by karianna** [comment]
> @karianna Was there a reason why this was re-assigned to Shelley in March?

I suspect I was thinking it was ready for a re-test but forgot to add a comment explaining that.

**Comment by sxa** [comment]
Anyone can handle this so I will unassign.

**Comment by sxa** [comment]
@smlambert Have we seen any problems as a result of the exclusions being reverted in the aforementioned PR?
