### ISSUE TITLE
java/util/zip/ZipFile/Zip64SizeTest.java forces test-softlayer-win2012r2-x64-2 to run out of space

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1311]
- To reproduce, run a grinder with these params or see https://ci.adoptopenjdk.net/job/Grinder/2987/console if still live: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=x86-64_windows_xl&CUSTOM_TARGET=test/jdk/java/util/zip/ZipFile/Zip64SizeTest.java&TARGET=jdk_custom_0&LABEL=test-softlayer-win2012r2-x64-2

The test forces the machine to run out of space. `test-softlayer-win2012r2-x64-1` is currently offline so I cannot check if it affects other softlayer machines. However, it doesn't affect `test-aws-win2019-x64-2` as per https://ci.adoptopenjdk.net/job/Grinder/2989/

Seems similar to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1163
```
14:28:59  config Zip64SizeTest.setUp(): success
14:28:59  Creating LargeZipEntry.txt
14:28:59  test Zip64SizeTest.validateZipEntrySizes(): failure
14:28:59  java.io.IOException: There is not enough space on the disk
14:28:59  	at java.base/java.io.RandomAccessFile.setLength(Native Method)
14:28:59  	at Zip64SizeTest.createFiles(Zip64SizeTest.java:124)
14:28:59  	at Zip64SizeTest.validateZipEntrySizes(Zip64SizeTest.java:67)
14:28:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:28:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:28:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:28:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
14:28:59  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
14:28:59  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
14:28:59  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
14:28:59  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
14:28:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
14:28:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
14:28:59  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
14:28:59  	at org.testng.TestRunner.run(TestRunner.java:623)
14:28:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
14:28:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
14:28:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
14:28:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
14:28:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
14:28:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
14:28:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
14:28:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
14:28:59  	at org.testng.TestNG.run(TestNG.java:1018)
14:28:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
14:28:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:28:59  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:28:59  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:28:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
14:28:59  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
14:28:59  	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by M-Davies** [comment]
Seen again on 14 https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk14_j9_sanity.openjdk_x86-64_windows/71/

**Comment by M-Davies** [comment]
Seen again on https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk14_j9_sanity.openjdk_x86-64_windows/72/

Running https://ci.adoptopenjdk.net/job/Grinder/3024/ to see if it occurs on other machines

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/Grinder/3061/console
Another quick verification that it still affects the machine. 
@M-Davies Do you have any idea of how much disk space this test takes up?

**Comment by M-Davies** [comment]
Yeah it looks good. Not sure why it didnt fill the machine up this time 🤔

**Comment by M-Davies** [comment]
Try running with ITERATIONS=5?

**Comment by Willsparker** [comment]
For #1328 , I had to restart the machine, which cleared off about a GB of space- it has about 12GB free, if I remember correctly- I'd be surprised if the test took up more than that!
Running with `ITERATIONS=5` : https://ci.adoptopenjdk.net/job/Grinder/3063/console

**Comment by Willsparker** [comment]
Above run succeeded (Passed the test 5 times) - closing issue
