### ISSUE TITLE
test-softlayer-win2012r2-x64-2 can't clean itself

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-infrastructure#1328]
See https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/149/console and https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/148/console

Looks like it needs a cleandown (@Willsparker if you have access?)
```
Running on test-softlayer-win2012r2-x64-2 in C:\Users\jenkins\workspace\Test_openjdk8_hs_sanity.openjdk_x86-64_windows
[Pipeline] {
[Pipeline] checkout
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/AdoptOpenJDK/openjdk-tests.git
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk8_hs_sanity.openjdk_x86-64_windows\openjdk-tests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:90)
	at hudson.Util.deleteContentsRecursive(Util.java:260)
	at hudson.Util.deleteContentsRecursive(Util.java:249)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:739)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: jenkins.util.io.CompositeIOException: Unable to remove directory C:\Users\jenkins\workspace\Test_openjdk8_hs_sanity.openjdk_x86-64_windows\openjdk-tests\TKG\test_output_1587577378934\jdk_jdi_0\work\scratch with directory contents: []
		at jenkins.util.io.PathRemover.removeOrMakeRemovableThenRemove(PathRemover.java:250)
		at jenkins.util.io.PathRemover.tryRemoveFile(PathRemover.java:205)
		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:216)
		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:215)
		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:215)
		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:215)
		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
		at jenkins.util.io.PathRemover.tryRemoveRecursive(PathRemover.java:215)
		at jenkins.util.io.PathRemover.tryRemoveDirectoryContents(PathRemover.java:226)
		at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:87)
		... 14 more
```

**Comment by Willsparker** [comment]
Cleaned up - Machine required a restart as some `java.exe` processes had locked the file.

**Comment by M-Davies** [comment]
Thanks :)
