### ISSUE TITLE
build-osuosl-aix71-ppc64-1 : connect issue.

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-infrastructure#1374]
**Test_openjdk8_hs_sanity.openjdk_ppc64_aix**

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/103/console

`build-osuosl-aix71-ppc64-1 was marked offline: Connection was broken: java.io.IOException: Unexpected EOF
	at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:99)
	at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
`

**Comment by Willsparker** [comment]
The machine appears to be reconnected in Jenkins again. Running a [Grinder](https://ci.adoptopenjdk.net/job/Grinder/3279/) to ensure it's stable enough to run `sanity.openjdk` , in I believe the same conditions that the job mentioned above does.

**Comment by Willsparker** [comment]
My Grinder ran through okay and the machine is still connected okay. I am going to assume that this was just a one-off disconnection (I noticed that the `-2` machine disconnected at around the same time too), feel free to reopen if it occurs again :)
