### ISSUE TITLE
build-siteox-solaris10u9-x64-1 server "time" wrong??

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1435]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/365/console
```
18:08:36  Caused by: java.security.cert.CertificateNotYetValidException: NotBefore: Sat Jul 04 19:00:00 CDT 2020
18:08:36  	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:270)
18:08:36  	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:687)
18:08:36  	at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
18:08:36  	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
18:08:36  	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
18:08:36  	... 34 more
18:08:36  RETRYWARNING: Gradle failed on attempt 2
```

assuming server time is wrong?

**Comment by karianna** [comment]
#1430 - Probably duplicate

**Comment by Willsparker** [comment]
Yep, looks like it to me- closing.
