### ISSUE TITLE
build-osuosl-aix71-ppc64-1 ulimit not large enough

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1445]
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/126/console
```
03:03:37  [TestNG] Running:
03:03:37    java/util/zip/ZipFile/Zip64SizeTest.java
03:03:37  
03:03:37  config Zip64SizeTest.setUp(): success
03:03:37  Creating LargeZipEntry.txt
03:03:37  test Zip64SizeTest.validateZipEntrySizes(): failure
03:03:37  java.io.IOException: A file cannot be larger than the value set by ulimit.
03:03:37  	at java.base/java.io.RandomAccessFile.setLength(Native Method)
03:03:37  	at Zip64SizeTest.createFiles(Zip64SizeTest.java:124)
03:03:37  	at Zip64SizeTest.validateZipEntrySizes(Zip64SizeTest.java:67)
```
Test is trying to create a 5Gb test file

**Comment by andrew-m-leonard** [comment]
Duplicate: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1443
