### ISSUE TITLE
JDK15 builds fail on build-macstadium-macos1014-x64-2

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-infrastructure#1455]
...but not on build-macstadium-macos1014-x64-1

Right after we try to run "git fetch -q --tags --depth=1" during a jdk15 build, we get this error on x64-2:

```
04:34:25  Execution error: hudson.AbortException: script returned exit code 1
[Pipeline] echo
04:34:25  hudson.AbortException: script returned exit code 1
04:34:25  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:658)
04:34:25  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:604)
04:34:25  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:548)
04:34:25  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
04:34:25  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04:34:25  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
04:34:25  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
04:34:25  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
04:34:25  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
04:34:25  	at java.lang.Thread.run(Thread.java:748)
```

It happens at exactly this point, but only during a jdk15 build, and only on this machine. I don't know why.

One possibility is a corrupted workspace. Running a [job](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15/job/jdk15-mac-x64-openj9/46/console) to clean the workspace now.

If this doesn't work, I may ask someone with access to try running some variant on the commands below, to see if they can prompt a more useful error message, debug log, etc.

git clone https://github.com/ibmruntimes/openj9-openjdk-jdk15.git
cd openj9-openjdk-jdk15
bash ./get_source.sh
git fetch -q --tags --depth=1

**Comment by adamfarley** [comment]
Ok, we passed the point of failure. 

Verdict: workspace corruption, resolved by a "clean workspace" run.

Closing issue.
