### ISSUE TITLE
FileNotFoundException on test-aws-rhel8-x64-1

### ISSUE THREAD

**Issue by austin0** [AdoptOpenJDK/openjdk-infrastructure#1468]
**Describe the bug**
A FileNotFoundException occurs during the "Post" section of the pipeline.

The error is believe to be caused during:
```
[2020-07-26T17:45:29.331Z] Recording test results
[2020-07-26T17:45:29.997Z] Remote call on test-aws-rhel8-x64-1 failed
```

The full error + stack trace is:

```
java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-3.el8_2.x86_64/jre/lib/resources.jar
	at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:938)
	at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:801)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:886)
	at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:879)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:878)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1050)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-aws-rhel8-x64-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at hudson.FilePath.act(FilePath.java:1069)
		at hudson.FilePath.act(FilePath.java:1058)
		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114)
		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137)
		at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167)
		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:52)
		at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:25)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Caused: java.lang.InternalError
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1052)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:302)
	at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1257)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1086)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:233)
	at java.util.ResourceBundle$RBClassLoader.getResourceAsStream(ResourceBundle.java:524)
	at java.util.ResourceBundle$Control$1.run(ResourceBundle.java:2694)
	at java.util.ResourceBundle$Control$1.run(ResourceBundle.java:2679)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2678)
	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1518)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1482)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1436)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1436)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1370)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at com.sun.org.apache.xerces.internal.utils.SecuritySupport$7.run(SecuritySupport.java:169)
	at com.sun.org.apache.xerces.internal.utils.SecuritySupport$7.run(SecuritySupport.java:166)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.org.apache.xerces.internal.utils.SecuritySupport.getResourceBundle(SecuritySupport.java:166)
	at com.sun.org.apache.xerces.internal.util.SAXMessageFormatter.formatMessage(SAXMessageFormatter.java:58)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.getFeature(AbstractSAXParser.java:1826)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.setFeature(SAXParserImpl.java:469)
	at org.dom4j.io.SAXHelper.setParserFeature(SAXHelper.java:49)
	at org.dom4j.io.SAXHelper.createXMLReader(SAXHelper.java:111)
	at org.dom4j.io.SAXReader.createXMLReader(SAXReader.java:874)
	at org.dom4j.io.SAXReader.getXMLReader(SAXReader.java:695)
	at org.dom4j.io.SAXReader.setFeature(SAXReader.java:200)
	at hudson.tasks.junit.SuiteResult.setFeatureQuietly(SuiteResult.java:191)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:172)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:348)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:281)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:206)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:178)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:143)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:118)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3073)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
Caused: java.io.IOException: Remote call on test-aws-rhel8-x64-1 failed
	at hudson.remoting.Channel.call(Channel.java:1004)
	at hudson.FilePath.act(FilePath.java:1069)
	at hudson.FilePath.act(FilePath.java:1058)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137)
	at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:52)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:25)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This error has been occurring on the `test-aws-rhel8-x64-1` machine, @Willsparker has taken a look on the machine and found that the version (`/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-3.el8_2.x86_64/jre/lib/resources.jar`) the build is looking for has been replaced by a newer one (`/usr/lib/jvm/java/java-1.8.0-openjdk-1.8.0.262.b10-0.el8_2.x86_64/jre/lib/resources.jar`).

Reruns are currently ongoing for both the failing `test-aws-rhel8-x64-1` machine (https://ci.adoptopenjdk.net/job/Test_openjdk8_corretto_sanity.openjdk_x86-64_linux/131/console) and for the last known passing machine `test-godaddy-ubuntu1604-x64-3` (https://ci.adoptopenjdk.net/job/Test_openjdk8_corretto_sanity.openjdk_x86-64_linux/133/console).

Issue seems to be only on the `test-aws-rhel8-x64-1` machine.

**To Reproduce**
This has been observed for multiple consecutive builds on `test-aws-rhel8-x64-1` i.e. https://ci.adoptopenjdk.net/job/Test_openjdk8_corretto_sanity.openjdk_x86-64_linux/129/console, https://ci.adoptopenjdk.net/job/Test_openjdk8_corretto_sanity.openjdk_x86-64_linux/130/console,
https://trss.adoptopenjdk.net/output/test?id=5f1dca6e0bec7975aeff1638

**Expected behavior**
```
[Pipeline] junit
18:46:31  Recording test results
[Pipeline] echo
18:46:33  ARTIFACTORY_SERVER is not set. Saving SHA file on jenkins.
[Pipeline] step
18:46:33  Archiving artifacts
18:46:33  Recording fingerprints
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
```

**Comment by Willsparker** [comment]
I had a look at the machine- as the error message contained `hudson` I assumed it had something to do with the Jenkins Agent. `top` found that it was running as `java -jar agent,jar etc` so it was using whichever `java` was in the path first- which happens to be `jdk8u-262.b10`. On the system information at https://ci.adoptopenjdk.net/computer/test-aws-rhel8-x64-1/systemInfo , the java version was `jdk8u-252.b09`, so I theorise that somebody updated JDK8 without restarting the Jenkins agent. Restarted it, and the system info now shows the java version to be correct, so- rerunning at 
https://ci.adoptopenjdk.net/job/Test_openjdk8_corretto_sanity.openjdk_x86-64_linux/135/

**Comment by Willsparker** [comment]
Seems fixed to me! Huzzah!
