### ISSUE TITLE
test-macincloud-macos1014-x64-1 is out of space

### ISSUE THREAD

**Issue by Haroon-Khel** [AdoptOpenJDK/openjdk-infrastructure#1489]
```
java.nio.file.FileSystemException: /Users/jenkins/workspace/build-scripts/release/create_installer_mac: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
```
This is causing some of the recent mac installer job failures such as https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_mac/4161/console and https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_mac/4163/console

**Comment by Haroon-Khel** [comment]
Theres now 4.6g available in `/` Closing issue
