### ISSUE TITLE
test-azure-win2012r2-x64-1 workspace needs cleanup

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1527]
See: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows/295/console
```
[Pipeline] checkout
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/AdoptOpenJDK/openjdk-tests.git
ERROR: Failed to clean the workspace
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.openjdk_x86-32_windows\openjdk-tests'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at jenkins.util.io.PathRemover.forceRemoveDirectoryContents(PathRemover.java:90)
	at hudson.Util.deleteContentsRecursive(Util.java:261)
	at hudson.Util.deleteContentsRecursive(Util.java:250)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:742)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)

```

Seems a regular problem, we need to try to understand why the cleanup does not occur? or perhaps make the above cleanup first before trying to clone maybe?

**Comment by Willsparker** [comment]
ref: #1396 
Done - This is a known issue (see the referenced one) - there's a leftover `java.exe` process running within the `openjdk-tests` folder, so it can't be deleted. I propose we run `SXA-ProcessCheck` after each test run, for the machine the tests have run on. This would theoretically stop any non-Jenkins-Agent processes, allowed the next test run to cleanup the workspace properly. (ping @sxa )
