### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1565]
This problem occurs intermittently, most recently on the Mac machines:
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_mac/4799/console
```
FATAL: Remote call on test-macincloud-macos1014-x64-3 failed
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-macincloud-macos1014-x64-3
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:998)
		at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1083)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:510)
		at hudson.model.Run.execute(Run.java:1880)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:428)
java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins
	at jenkins.agents.AgentComputerUtil.getChannelToMaster(AgentComputerUtil.java:48)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1100)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1091)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Remote call on test-macincloud-macos1014-x64-3 failed
	at hudson.remoting.Channel.call(Channel.java:1004)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1083)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:510)
	at hudson.model.Run.execute(Run.java:1880)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
```
From looking at various old Jenkins bugs, the most likely culprit seems to be a Java8 version issue. The above Mac machine are running:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)
```

I suggest we upgrade the Mac nodes to at least jdk8u265 to see if that resolves the problem.

**Comment by Haroon-Khel** [comment]
@andrew-m-leonard Ive upgraded the java version to jdk8u265
```
test-macincloud-macos1014-x64-3:~ admin$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```
Would you like to re run the job on that machine (test-macincloud-macos1014-x64-3) to see if it fixes the problem? Im not too sure but the machine **may** need to be disconnected and reconnected for the jenkins agent to update the java version

**Comment by Willsparker** [comment]
I believe it does need to be reconnected, @Haroon-Khel , the system info on the Node screen is still showing `1.8.0_212-b04`

**Comment by andrew-m-leonard** [comment]
Just tried, and looks good now, thanks, we will see if this resolves the intermittent problem going forward...

**Comment by Willsparker** [comment]
I think this may be a good time to open a new issue to just check the java versions that are running all the nodes' Jenkins agents. Or possibly automate it ...?

**Comment by Willsparker** [comment]
Either way, I'm going to close this issue as it's fixed for now.
Here's a list of the java versions running all the mac test machines that I checked manually
```
macincloud machines
macos1010-x64-1 jdk1.8.0_131
macos1010-x64-2 "
macos1012-x64-1 jdk1.8.0_212-b04
macos1013-x64-1 "
macos1013-x64-2 "
macos1014-x64-1 "
macos1014-x64-2 "
macos1014-x64-3 jdk1.8.0_265-b01

macstadium arm machines
macos11-arm64-1 jdk1.8.0_265
macos11-arm64-2 jdk1.8.0_265_b01
```
