### ISSUE TITLE
openjdk-systemtest jlm tests failing on test-scaleway-ubuntu1604-x64-1

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1627]
This issue has been raised at eclipse/openj9: https://github.com/eclipse/openj9/issues/10156, but it appears that the failure is peculiar to test-scaleway-ubuntu1604-x64-1 (the test runs successfully on other machines - e.g. https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.system_x86-64_linux/74 (test-godaddy-ubuntu1604-x64-3), https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4207 (test-godaddy-centos7-x64-2).

A Grinder forcing the test to run on test-scaleway-ubuntu1604-x64-1 shows the issue is still present: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4205/.

In the test a 'client' process attempts to connect to a 'server' process using the JMXConnector interface on port `localhost:1234` and receives `Connection refused`.

Can someone with test machine login authorisation please help investigate.

 The output from the test around the time of failure is:
```
13:11:19  STF 12:11:18.991 - +------ Step 5 - Wait for the processes to complete
13:11:19  STF 12:11:18.991 - | Wait for processes to meet expectations
13:11:19  STF 12:11:18.991 - |   Processes: [LT1, CL1]
13:11:19  STF 12:11:18.991 - |
13:11:19  STF 12:11:18.991 - Monitoring processes: CL1 LT1
13:11:20  CL1 j> 2020/10/15 12:11:19.507 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
13:11:20  CL1 j> 2020/10/15 12:11:19.760 Attempting to connect
13:11:20  CL1 j> 2020/10/15 12:11:20.566 Monitored VM not ready at Oct 15, 2020, 12:11:20 PM (attempt 1, elapsed 731ms).
13:11:20  CL1 j> 2020/10/15 12:11:20.566 Waiting 5 secs and trying again...
13:11:26  CL1 j> 2020/10/15 12:11:25.567 Attempting to connect
13:15:50  CL1 j> 2020/10/15 12:15:43.385 Failed to connect to Monitored VM after 2 attempts in 263 seconds - giving up.  Connection Exception received is below:
13:15:50  CL1 stderr java.rmi.ConnectException: Connection refused to host: 10.8.206.67; nested exception is: 
13:15:50  CL1 stderr 	java.net.ConnectException: Connection timed out
13:15:50  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
13:15:50  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
13:15:50  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
13:15:50  CL1 stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
13:15:50  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83)
13:15:50  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2105)
13:15:50  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321)
13:15:50  CL1 stderr 	at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
13:15:50  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.getSecureServerConnection(ServerConnector.java:188)
13:15:50  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.<init>(ServerConnector.java:81)
13:15:50  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.<init>(ClassProfiler.java:72)
13:15:50  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:89)
13:15:50  CL1 stderr Caused by: java.net.ConnectException: Connection timed out
13:15:50  CL1 stderr 	at java.base/sun.nio.ch.Net.connect0(Native Method)
13:15:50  CL1 stderr 	at java.base/sun.nio.ch.Net.connect(Net.java:574)
13:15:50  CL1 stderr 	at java.base/sun.nio.ch.Net.connect(Net.java:563)
13:15:50  CL1 stderr 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
13:15:50  CL1 stderr 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
13:15:50  CL1 stderr 	at java.base/java.net.Socket.connect(Socket.java:648)
13:15:50  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
13:15:50  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:149)
13:15:50  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
13:15:50  CL1 stderr 	at java.rmi/javax.rmi.ssl.SslRMIClientSocketFactory.createSocket(SslRMIClientSocketFactory.java:121)
13:15:50  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
13:15:50  CL1 stderr 	... 11 more
13:15:50  CL1 stderr Exception in thread "main" java.lang.NullPointerException
13:15:50  CL1 stderr 	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:651)
13:15:50  CL1 stderr 	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:611)
13:15:50  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.getStatsViaProxy(ClassProfiler.java:117)
13:15:50  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:102)
13:15:50  STF 12:15:43.797 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)
13:15:50  STF 12:15:43.797 - Monitoring Report Summary:
13:15:50  STF 12:15:43.797 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
13:15:50  STF 12:15:43.797 -   o Process LT1 is still running as expected
13:15:50  STF 12:15:43.798 - Killing processes: CL1 LT1
13:15:50  STF 12:15:43.798 -   o Process CL1 is not running
13:15:56  STF 12:15:54.800 -   o Process LT1 killed
13:15:56  **FAILED** at step 5 (Wait for the processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16027638738250/TestJlmRemoteClassAuth_0/20201015-121113-TestJlmRemoteClassAuth/execute.pl line 174.
13:15:56  STF 12:15:55.293 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by lumpfish** [comment]
This is still occurring: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4640/consoleFull

**Comment by sxa** [comment]
Re-running at https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.system_x86-64_linux/103/ after updating `/etc/hosts` so that the hostname resolves to something that can be connected to (it's external IP address) as opposed to one that can't (The `10.` address that it's currently associated with in the hosts file). If everything is using `localhost` then it /shouldn't/ matter but something's going wrong here so it's worth a try.

Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1691#issuecomment-730542988

**Comment by sxa** [comment]
Onlhy MauveMultiThreadLoadTest_0 failed on that run (which seems to have failed consistently over the last week whever it was run) so looks like fixing the name resolution of the system's hostname has resolved this.
