### ISSUE TITLE
System unavailable: test-ibm-aix71-ppc64-2: There is not enough memory available

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1664]
Sample failing job: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4524/console

Jobs on test-ibm-aix71-ppc64-2 are failing with:
```
Caused by: java.io.IOException: Cannot run program "git" (in directory "/home/jenkins/workspace/Grinder/openjdk-tests"): error=12, There is not enough memory available now.
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at hudson.Proc$LocalProc.<init>(Proc.java:252)
	at hudson.Proc$LocalProc.<init>(Proc.java:221)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:996)
	at hudson.Launcher$ProcStarter.start(Launcher.java:508)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2443)
	... 15 more
Caused by: java.io.IOException: error=12, There is not enough memory available now.
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 20 more
```

**Comment by sxa** [comment]
Something's gone badly wrong on that system - I can't establish an ssh connection to it

**Comment by sxa** [comment]
Marked https://ci.adoptopenjdk.net/computer/test-ibm-aix71-ppc64-2 offline in jenkins for now

**Comment by sxa** [comment]
Back online - summary:

`I was able to get on the LPAR, but I noticed that it had run out of memory and swap space at some point, and killed some processes. This may explain why you were not able to connect.
I rebooted the LPAR, it should be in a better state now.`
