### ISSUE TITLE
More than half of jdk_jdi tests failed with Dragonwell jdk on packet boxes

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#1691]
More than half of jdk_jdi tests failed with Dragonwell jdk8 on packet boxes. Tests passed on other boxes. Also test build took 4 hours compared 40 mins on other boxes. Test builds with hotspot|openj9 on packet boxes also take three times longer than on other boxes without behaviour difference. That is test results are consistent running on packet or other boxes.

<img width="1247" alt="Screen Shot 2020-09-17 at 11 05 22 AM" src="https://user-images.githubusercontent.com/18030625/93489704-c11f5500-f8d5-11ea-9705-492ab2416b30.png">

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/14/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/12/
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/10/

Not sure what's the difference between packet boxes with other except for performance?

**Comment by sxa** [comment]
@sophia-guo @smlambert The title of this mentions packet boxes but I don't see any packet ones in the screenshot you've given. Did you mean scaleway?

**Comment by sxa** [comment]
Replicated a potential issue outside jenkins and the test harness on the [Scaleway machine](https://ci.adoptopenjdk.net/computer/test-scaleway-ubuntu1604-x64-1/):
```
root@test-scaleway-ubuntu1604-x64-1:~# /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi -Xdebug -Xrunjdwp:transport=dt_socket,address=test-scaleway-ubuntu1604-x64-1.adoptopenjdk.net:46599,suspend=y EarlyReturnNegativeTarg
ERROR: transport error 202: connect failed: Network is unreachable
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```
The hostname that the machine has resolves to a `10.` IP address (a private one) I would have thought that would be accessible (although it's setup is obviously provider-dependent) but it seems not. It's external IP adress is pingable however. Once the current test run is complete I'll try switching `/etc/hosts` so that the hostname resolves the the external IP adress and see if that makes a difference.

Memo to self - test links running on the Scaleway machine for each variant:
- [Dragonwell run](https://ci.adoptopenjdk.net/job/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/89)
- [OpenJ9 run](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/404)
- [HotSpot run](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/596)

**Comment by sxa** [comment]
HotSpot run after changing `/etc/hosts`: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/598

**Comment by sxa** [comment]
Killed and restarting as [job 600](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/600/console) due to a lot of leftover processes from previous `sanity.openjdk` runs:
```
root@test-scaleway-ubuntu1604-x64-1:~# ps -ef | grep Test_
jenkins   2858     1  0 11:42 ?        00:00:03 /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=46077 HelloWorld
root      3072 25774  0 23:06 pts/0    00:00:00 grep --color=auto Test_
jenkins   5523     1  0 16:10 ?        00:00:01 /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=45812 -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16057983637450/jdk_jdi_0/work/classes/com/sun/jdi Exit0
jenkins   8159     1  0 19:00 ?        00:00:00 /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16057983637450/jdk_jdi_0/work/classes/com/sun/jdi -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=40481 Exit0
jenkins  10109     1  0 12:23 ?        00:00:43 /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java -DHANGINGJAVA_DEB -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi -showversion -DTRANSPORT_METHOD=dt_socket -classpath /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi JITDebug
jenkins  10126 10109  0 12:23 ?        00:00:42 /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi -agentlib:jdwp=transport=dt_socket,server=y,onuncaught=y,launch=/home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java -DTRANSPORT_METHOD=dt_socket JITDebug DEBUGGER  JITDebug TARGET
jenkins  14301     1  0 16:48 ?        00:00:01 /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16057983637450/jdk_jdi_0/work/classes/com/sun/jdi -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=38077 HelloWorld
jenkins  18196     1  0 13:25 ?        00:00:02 /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y -classpath /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi ProcessAttachDebuggee /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi/shutdown2.port
jenkins  22256     1  0 17:30 ?        00:00:20 /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java -DHANGINGJAVA_DEB -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16057983637450/jdk_jdi_0/work/classes/com/sun/jdi -showversion -DTRANSPORT_METHOD=dt_socket -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16057983637450/jdk_jdi_0/work/classes/com/sun/jdi JITDebug
jenkins  22271 22256  0 17:30 ?        00:00:20 /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16057983637450/jdk_jdi_0/work/classes/com/sun/jdi -agentlib:jdwp=transport=dt_socket,server=y,onuncaught=y,launch=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java -DTRANSPORT_METHOD=dt_socket JITDebug DEBUGGER  JITDebug TARGET
jenkins  25963     1  0 11:06 ?        00:00:03 /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=46149 -classpath /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi Exit0
jenkins  27890     1  0 13:52 ?        00:00:03 /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/java -classpath /home/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_1605779978272/jdk_jdi_0/work/classes/com/sun/jdi -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=44970 Exit0
jenkins  31490     1  0 18:33 ?        00:00:00 /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16057983637450/jdk_jdi_0/work/classes/com/sun/jdi ProcessAttachDebuggee /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16057983637450/jdk_jdi_0/work/classes/com/sun/jdi/shutdown2.port
root@test-scaleway-ubuntu1604-x64-1:~# 
```

**Comment by sxa** [comment]
Hmmm possibly different error now from run 600 - none of the output below occurred on the last passing run (job 597 at the time of writing):

```
23:37:21  --------------------------------------------------
23:37:21  TEST: com/sun/jdi/connect/spi/DebugUsingCustomConnector.java
23:37:21  TEST JDK: /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image
23:37:21  
23:37:21  ACTION: build -- Passed. Build successful
23:37:21  REASON: User specified action: run build DebugUsingCustomConnector SimpleLaunchingConnector Foo NullTransportService 
23:37:21  TIME:   1.134 seconds
23:37:21  messages:
23:37:21  command: build DebugUsingCustomConnector SimpleLaunchingConnector Foo NullTransportService
23:37:21  reason: User specified action: run build DebugUsingCustomConnector SimpleLaunchingConnector Foo NullTransportService 
23:37:21  Test directory:
23:37:21    compile: DebugUsingCustomConnector, SimpleLaunchingConnector, Foo, NullTransportService
23:37:21  elapsed time (seconds): 1.134
23:37:21  
23:37:21  ACTION: compile -- Passed. Compilation successful
23:37:21  REASON: .class file out of date or does not exist
23:37:21  TIME:   1.115 seconds
23:37:21  messages:
23:37:21  command: compile -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/DebugUsingCustomConnector.java /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/SimpleLaunchingConnector.java /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/Foo.java /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/NullTransportService.java
23:37:21  reason: .class file out of date or does not exist
23:37:21  Mode: agentvm
23:37:21  Agent id: 1
23:37:21  elapsed time (seconds): 1.115
23:37:21  configuration:
23:37:21  Boot Layer (javac runtime environment)
23:37:21    class path: /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
23:37:21                /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/javatest.jar
23:37:21                /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/jvmtest/openjdk/jtreg/lib/jtreg.jar
23:37:21  
23:37:21  javac compilation environment
23:37:21    source path: /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi
23:37:21    class path:  /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi
23:37:21                 /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16058273708339/jdk_jdi_0/work/classes/com/sun/jdi/connect/spi
23:37:21                 /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar
23:37:21  
23:37:21  rerun:
23:37:21  cd /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16058273708339/jdk_jdi_0/work/scratch && \
23:37:21  DISPLAY=:0 \
23:37:21  HOME=/home/jenkins \
23:37:21  LANG=en_US.UTF-8 \
23:37:21  PATH=/bin:/usr/bin:/usr/sbin \
23:37:21      /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/javac \
23:37:21          -J-ea \
23:37:21          -J-esa \
23:37:21          -J-Xmx512m \
23:37:21          -J-Dtest.vm.opts='-ea -esa -Xmx512m' \
23:37:21          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \
23:37:21          -J-Dtest.compiler.opts= \
23:37:21          -J-Dtest.java.opts= \
23:37:21          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
23:37:21          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image \
23:37:21          -J-Dtest.timeout.factor=8.0 \
23:37:21          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
23:37:21          -J-Dtest.name=com/sun/jdi/connect/spi/DebugUsingCustomConnector.java \
23:37:21          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/DebugUsingCustomConnector.java \
23:37:21          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi \
23:37:21          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi \
23:37:21          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16058273708339/jdk_jdi_0/work/classes/com/sun/jdi/connect/spi \
23:37:21          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16058273708339/jdk_jdi_0/work/classes/com/sun/jdi/connect/spi \
23:37:21          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16058273708339/jdk_jdi_0/work/classes/com/sun/jdi/connect/spi:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi \
23:37:21          -d /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16058273708339/jdk_jdi_0/work/classes/com/sun/jdi/connect/spi \
23:37:21          -sourcepath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi \
23:37:21          -classpath /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/test_output_16058273708339/jdk_jdi_0/work/classes/com/sun/jdi/connect/spi:/home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar \
23:37:21          -XDignore.symbol.file=true /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/DebugUsingCustomConnector.java /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/SimpleLaunchingConnector.java /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/Foo.java /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/com/sun/jdi/connect/spi/NullTransportService.java
23:37:21  direct:
23:37:21  Note: Some input files use unchecked or unsafe operations.
23:37:21  Note: Recompile with -Xlint:unchecked for details.
23:37:21  
23:37:21  ACTION: build -- Passed. All files up to date
23:37:21  REASON: Named class compiled on demand
23:37:21  TIME:   0.0 seconds
23:37:21  messages:
23:37:21  command: build DebugUsingCustomConnector
23:37:21  reason: Named class compiled on demand
23:37:21  elapsed time (seconds): 0.0
23:37:21  
23:37:21  ACTION: main -- Failed. Execution failed: `main' threw exception: com.sun.jdi.connect.TransportTimeoutException: timeout waiting for connection
23:37:21  REASON: User specified action: run main/othervm DebugUsingCustomConnector 
23:37:21  TIME:   30.427 seconds
23:37:21  messages:
23:37:21  command: main DebugUsingCustomConnector
23:37:21  reason: User specified action: run main/othervm DebugUsingCustomConnector 
23:37:21  Mode: othervm [/othervm specified]
23:37:21  elapsed time (seconds): 30.427
23:37:21  configuration:
23:37:21  STDOUT:
23:37:21  STDERR:
23:37:21  com.sun.jdi.connect.TransportTimeoutException: timeout waiting for connection
23:37:21  	at com.sun.tools.jdi.SocketTransportService.accept(SocketTransportService.java:350)
23:37:21  	at SimpleLaunchingConnector.launch(SimpleLaunchingConnector.java:152)
23:37:21  	at DebugUsingCustomConnector.main(DebugUsingCustomConnector.java:73)
23:37:21  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:37:21  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:37:21  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:37:21  	at java.lang.reflect.Method.invoke(Method.java:498)
23:37:21  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:37:21  	at java.lang.Thread.run(Thread.java:748)
23:37:21  
23:37:21  JavaTest Message: Test threw exception: com.sun.jdi.connect.TransportTimeoutException: timeout waiting for connection
23:37:21  JavaTest Message: shutting down test
23:37:21  
23:37:21  STATUS:Failed.`main' threw exception: com.sun.jdi.connect.TransportTimeoutException: timeout waiting for connection
23:37:21  rerun:
```

**Comment by sxa** [comment]
Backlog for now as not a Temurin build failure
