### ISSUE TITLE
test-marist-ubuntu1604-s390x-2X Jenkins failure at end of test run

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1692]
Test builds are failing with a Jenkins error on test-marist-ubuntu1604-s390x-2X after the tests have completed their execution - e.g. test-marist-ubuntu1604-s390x-2X

Output around the point of failure showing the test run completing followed by the Jenkins error:
```
14:36:26  TEST TARGETS SUMMARY
14:36:26  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
14:36:26  PASSED test targets:
14:36:26  	MathLoadTest_all_0
14:36:26  	LockingLoadTest_0
14:36:26  
14:36:26  TOTAL: 2   EXECUTED: 2   PASSED: 2   FAILED: 0   DISABLED: 0   SKIPPED: 0
14:36:26  ALL TESTS PASSED
14:36:26  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
14:36:26  
14:36:26  _testList done
14:36:26  make[1]: Leaving directory '/home/jenkins/workspace/Grinder/openjdk-tests/TKG'
14:36:26  + '[' '!' -z 0 ']'
14:36:26  + '[' linux-gnu = cygwin ']'
14:36:26  + echo PROCESSCATCH: Checking for any leftover java processes on the machine
14:36:26  PROCESSCATCH: Checking for any leftover java processes on the machine
14:36:26  + ps -fu jenkins
14:36:26  + grep java
14:36:26  + egrep -v 'remoting.jar|agent.jar|grep'
[Pipeline] sh
14:36:28  + uname
14:36:28  + [ Linux = AIX ]
14:36:28  + uname
14:36:28  + [ Linux = SunOS ]
14:36:28  + MAKE=make
14:36:28  + make -f ./openjdk-tests/TKG/testEnv.mk testEnvTeardown
14:36:28  make: Nothing to be done for 'testEnvTeardown'.
[Pipeline] }
14:36:28  Xvfb stopping
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] step
14:36:28  TAP Reports Processing: START
14:36:28  Looking for TAP results report in workspace using pattern: **/*.tap
14:36:29  Saving reports...
14:36:29  Processing '/home/jenkins/.jenkins/jobs/Grinder/builds/4914/tap-master-files/openjdk-tests/TKG/test_output_16057965018204/TestTargetResult.tap'
14:36:29  Parsing TAP test result [/home/jenkins/.jenkins/jobs/Grinder/builds/4914/tap-master-files/openjdk-tests/TKG/test_output_16057965018204/TestTargetResult.tap].
14:36:29  TAP Reports Processing: FINISH
[Pipeline] junit
14:36:29  Recording test results
14:36:29  None of the test reports contained any result
14:36:29  [Checks API] No suitable checks publisher found.
[Pipeline] echo
14:36:29  ARTIFACTORY_SERVER is not set. Saving SHA file on jenkins.
[Pipeline] archiveArtifacts
14:36:30  Archiving artifacts
14:36:30  Recording fingerprints
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
[WS-CLEANUP] done
[Pipeline] sh
+ find /tmp -name *core* -print -exec rm -f {} ;
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-marist-ubuntu1604-s390x-2X
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1147)
		at org.jenkinsci.plugins.xvfb.Xvfb.shutdownAndCleanup(Xvfb.java:327)
		at org.jenkinsci.plugins.xvfb.XvfbDisposer.tearDown(XvfbDisposer.java:52)
		at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Callback.finished(CoreWrapperStep.java:248)
		at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2$Callback2.finished(CoreWrapperStep.java:186)
		at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$TailCall.lambda$onSuccess$0(GeneralNonBlockingStepExecution.java:140)
		at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins
	at jenkins.agents.AgentComputerUtil.getChannelToMaster(AgentComputerUtil.java:48)
	at hudson.util.ProcessTree.get(ProcessTree.java:432)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1164)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1155)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
Caused: java.io.IOException: Remote call on test-marist-ubuntu1604-s390x-2X failed
	at hudson.remoting.Channel.call(Channel.java:1007)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1147)
	at org.jenkinsci.plugins.xvfb.Xvfb.shutdownAndCleanup(Xvfb.java:327)
	at org.jenkinsci.plugins.xvfb.XvfbDisposer.tearDown(XvfbDisposer.java:52)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Callback.finished(CoreWrapperStep.java:248)
	at org.jenkinsci.plugins.workflow.steps.CoreWrapperStep$Execution2$Callback2.finished(CoreWrapperStep.java:186)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution$TailCall.lambda$onSuccess$0(GeneralNonBlockingStepExecution.java:140)
	at org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE


```

Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name? 
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? 
- Which machine(s) does it fail on?
- Do you have a link to a Grinder re-run if the test with the failure?

Any other details:

**Comment by Haroon-Khel** [comment]
Could not recreate the issue. Seems to have been an intermittent Jenkins glitch. Closing
