### ISSUE TITLE
test-ibmcloud-win2012r2-x64-1: out of memory errors running tests

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1836]
This test run has a number of test failures due to insufficient resources being avialable on test-ibmcloud-win2012r2-x64-1: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/431/consoleFull

```
19:45:24  ===============================================
19:45:24  java/lang/ProcessHandle/OnExitTest.java
19:45:24  Total tests run: 3, Failures: 1, Skips: 0
19:45:24  ===============================================
19:45:24  
19:45:24  STDERR:
19:45:24  JVMJ9VM015W Initialization error for library j9jit29(11): cannot initialize JIT
19:45:24  Error: Could not create the Java Virtual Machine.
19:45:24  Error: A fatal exception has occurred. Program will exit.
19:45:24  JVMJ9VM015W Initialization error for library j9gc29(5): Failed to allocate default memory space.
19:45:24  Error: Could not create the Java Virtual Machine.
19:45:24  Error: A fatal exception has occurred. Program will exit.
19:45:24  JVMJ9VM015W Initialization error for library j9jit29(11): cannot initialize JIT
19:45:24  Error: Could not create the Java Virtual Machine.
19:45:24  Error: A fatal exception has occurred. Program will exit.
19:45:24  java.lang.Exception: failures: 1
19:45:24  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
19:45:24  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
19:45:24  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:45:24  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:45:24  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:45:24  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
19:45:24  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:45:24  	at java.base/java.lang.Thread.run(Thread.java:836)
19:45:24  
19:45:24  JavaTest Message: Test threw exception: java.lang.Exception: failures: 1
19:45:24  JavaTest Message: shutting down test
```
```
19:48:09  STDERR:
19:48:09  JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata.  200M requested
19:48:09  Error: Could not create the Java Virtual Machine.
19:48:09  Error: A fatal exception has occurred. Program will exit.
```
```
19:48:09  STDERR:
19:48:09  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2021/01/12 13:48:05 - please wait.
19:48:09  JVMDUMP032I JVM requested Java dump using 'E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TKG\test_output_16104802555766\jdk_lang_j9_0\work\scratch\2\javacore.20210112.134805.6300.0001.txt' in response to an event
19:48:09  JVMDUMP010I Java dump written to E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TKG\test_output_16104802555766\jdk_lang_j9_0\work\scratch\2\javacore.20210112.134805.6300.0001.txt
19:48:09  JVMDUMP032I JVM requested Snap dump using 'E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TKG\test_output_16104802555766\jdk_lang_j9_0\work\scratch\2\Snap.20210112.134805.6300.0002.trc' in response to an event
19:48:09  JVMDUMP010I Snap dump written to E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TKG\test_output_16104802555766\jdk_lang_j9_0\work\scratch\2\Snap.20210112.134805.6300.0002.trc
19:48:09  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
19:48:09  compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.10, {1}, {2}, {3}, {4}, {5}, {6}, {7}
19:48:09  java.lang.OutOfMemoryError: native memory exhausted
19:48:09  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
```
```
19:48:17  STDERR:
19:48:17  Unhandled exception
19:48:17  Type=Segmentation error vmState=0x00000000
19:48:17  Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFB85586978 ContextFlags=0010005f
19:48:17  Handler1=00007FFB85619790 Handler2=00007FFB8551AAA0 InaccessibleReadAddress=FFFFFFFFFFFFFFFF
19:48:17  RDI=00000000000001D6 RSI=0000005B53C2EF10 RAX=0000005B52F35580 RBX=DDDDDDDD00297268
19:48:17  RCX=0000005B52F35580 RDX=DDDDDDDD00297268 R8=0000000000000000 R9=0000000000000000
19:48:17  R10=00000000000000C8 R11=00000000000000D0 R12=0000005B5C31FC28 R13=00007FFB85619790
19:48:17  R14=000000000001D600 R15=0000005B52F48FD0
19:48:17  RIP=00007FFB85586978 RSP=0000005B5C31F850 RBP=0000005B53C2EF10 GS=002B
19:48:17  FS=0053 ES=002B DS=002B
19:48:17  XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:48:17  Module=E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\bin\compressedrefs\j9thr29.dll
19:48:17  Module_base_address=00007FFB85580000 Offset_in_DLL=0000000000006978
19:48:17  Target=2_90_20210112_895 (Windows Server 2012 R2 6.3 build 9600)
19:48:17  CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
19:48:17  ----------- Stack Backtrace -----------
19:48:17  JVMJ9VM015W Initialization error for library j9jit29(11): cannot initialize JIT
19:48:17  omrthread_get_category+0x2f28 (0x00007FFB85586978 [j9thr29+0x6978])
19:48:17  omrthread_monitor_wait+0x43 (0x00007FFB85582B13 [j9thr29+0x2b13])
19:48:17  (0x00007FFB84BF1B95 [j9jit29+0x71b95])
19:48:17  (0x00007FFB84BFAD07 [j9jit29+0x7ad07])
19:48:17  j9port_isCompatible+0x1a0ef (0x00007FFB8551CC1F [j9prt29+0x1cc1f])
19:48:17  (0x00007FFB84BFA94D [j9jit29+0x7a94d])
19:48:17  omrthread_get_category+0xa42 (0x00007FFB85584492 [j9thr29+0x4492])
19:48:17  _o_strcat_s+0x5e (0x00007FFB8589C1AE [ucrtbase+0x1c1ae])
19:48:17  BaseThreadInitThunk+0x22 (0x00007FFB919F1412 [KERNEL32+0x1412])
19:48:17  RtlUserThreadStart+0x34 (0x00007FFB931F54F4 [ntdll+0x154f4])
19:48:17  ---------------------------------------
19:48:17  Error: Could not create the Java Virtual Machine.
```

**Comment by lumpfish** [comment]
Dup of #1835
