### ISSUE TITLE
test-gdams-win10-aarch64-1 offline

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1872]
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/cross-compiled-version-out/118/console
```
[Pipeline] node
test-gdams-win10-aarch64-1 was marked offline: Connection was broken: java.util.concurrent.TimeoutException: Ping started at 1611793774493 hasn't completed by 1611794014494
	at hudson.remoting.PingThread.ping(PingThread.java:134)
	at hudson.remoting.PingThread.run(PingThread.java:90)
```

**Comment by Willsparker** [comment]
ping @gdams

**Comment by sxa** [comment]
Hmmm I thought moving the hosting into a VM was expected to reduce these outages

**Comment by gdams** [comment]
Hmm I thought that this would be more stable. It looks like it's failing with the following error:

```
Jan 28, 2021 9:09:10 AM hudson.remoting.UserRequest perform
WARNING: LinkageError while performing UserRequest:hudson.node_monitors.SwapSpaceMonitor$MonitorTask@7fd33c4
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/win32-aarch64/jnidispatch.dll) not found in resource path ([])
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1032)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
        at com.sun.jna.Native.<clinit>(Native.java:195)
        at com.sun.jna.Structure.setAlignType(Structure.java:280)
        at com.sun.jna.Structure.<init>(Structure.java:197)
        at com.sun.jna.Structure.<init>(Structure.java:193)
        at com.sun.jna.Structure.<init>(Structure.java:180)
        at com.sun.jna.Structure.<init>(Structure.java:172)
        at org.jvnet.hudson.Windows$MEMORYSTATUSEX.<init>(Windows.java:57)
        at org.jvnet.hudson.Windows.monitor(Windows.java:42)
        at hudson.node_monitors.SwapSpaceMonitor$MonitorTask.call(SwapSpaceMonitor.java:125)
        at hudson.node_monitors.SwapSpaceMonitor$MonitorTask.call(SwapSpaceMonitor.java:115)
        at hudson.remoting.UserRequest.perform(UserRequest.java:211)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:375)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:118)
        at java.base/java.lang.Thread.run(Thread.java:831)

Jan 28, 2021 10:08:38 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Terminated
```

I wonder whether switching to an x86 binary would be a more stable option than using the EA Windows Aarch64 binary to connect to Jenkins

**Comment by sxa** [comment]
Naively `win32-aarch64` doesn't superficially look right at all if that's for the native port, but yes I'd definitely be tempted to run a real win32 JDK8 for the jenkins agent for now.

**Comment by sxa** [comment]
Since there is no work being done to bring this online and we have removed the platform from the pipelines, I'm closing this
