### ISSUE TITLE
ThunderX machines cannot reliably git clone due to random gnuTls recv errors

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#1897]
```
error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
ThunderX nodes to be disabled: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1809#issuecomment-771658763

**Comment by andrew-m-leonard** [comment]
Disabled:
```
https://ci.adoptopenjdk.net/computer/test-docker-centos8-armv8-1
https://ci.adoptopenjdk.net/computer/test-docker-ubuntu1604-armv8-1
https://ci.adoptopenjdk.net/computer/test-docker-ubuntu1804-armv8-1
https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-armv8-1
https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2010-armv8-1
```

**Comment by sxa** [comment]
Problem references:
- https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/404
- https://github.com/AdoptOpenJDK/openjdk-build/issues/1804

I'm going to close each of those as both have now been mitigated as the ThunderX machines appear to be the cause of both and are no longer in use. We can continue any investigation towards a resolution here (although it is likely the machines will be decomissioned in the next few months anyway)

My plan, which I hadn't created an issue for, was to try doing an OS upgrade on one of the ThunderX systems - try Ubuntu 18.04 for example, but given that the problems has been seen on both CentOS and Ubuntu systems I'm not convinced that will make a difference if it's hardware related. The only thing may be if we try a TLS implementation build using a differnet compiler version in case we're hitting some sort of compiler bug that only effects these systems.

**Comment by sxa** [comment]
cat/. Let's see if the problem showls up on there.

- Rerunning [JDK8/J9 extended system #168](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.system_aarch64_linux/168/) as [Grinder#6477](https://ci.adoptopenjdk.net/job/Grinder/6477/)
- Rerunning JDK8/J9 sanity.system #168](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_aarch64_linux/168/) in [Grinder#6478](https://ci.adoptopenjdk.net/job/Grinder/6478/)
- Rerunnning [JDK16/J9 extended.system](https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.system_aarch64_linux_xl/45/) as [Grinder#6479](https://ci.adoptopenjdk.net/job/Grinder/6478/)

**Comment by sxa** [comment]
Now failing with this - may need git to be rebuilt (or use the system one)
```
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/AdoptOpenJDK/openjdk-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: /usr/local/libexec/git-core/git-remote-https: /usr/lib/aarch64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/libexec/git-core/git-remote-https)

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2051)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:573)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
```

**Comment by sxa** [comment]
Upgtrading to Ubuntu 18 has not resolved this - ran multiple tests and two of them failed.

Cloning openjdk-tests gave this:

```

Receiving objects:  12% (1427/11886)   
Receiving objects:  13% (1546/11886)   
Receiving objects:  14% (1665/11886)   
Receiving objects:  15% (1783/11886)   
Receiving objects:  15% (1856/11886), 4.54 MiB | 9.07 MiB/s   
Receiving objects:  16% (1902/11886), 13.55 MiB | 13.55 MiB/s   
error: RPC failed; curl 56 GnuTLS recv error (-12): A TLS fatal alert has been received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
and on another run:
```

Receiving objects:  14% (1665/11886)   
Receiving objects:  15% (1783/11886)   
error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed


	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2051)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:573)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:802)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-packet-ubuntu1604-armv8-2
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor669.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy408.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1224)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$$Lambda$541/000000000000000000.run(Unknown Source)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:823)
[Pipeline] }
```

**Comment by karianna** [comment]
Wrong TLS version or net split?

**Comment by sxa** [comment]
> Wrong TLS version or net split?

It's happening quite frequently and only on this hardware type. The same job running about 10 times failed twice so unlikely they've negotiatednegotriated the wrong TLS version.

**Comment by sxa** [comment]
Random musing ... would it react differently if OpenSSL was build without hardware crypto support (e.g. `./config no-asm no-engine no-threads` or even debug `-d`)?

**Comment by sxa** [comment]
I've now got five loops running in parallel:
- The system version of OpenSSL on Ubuntu 18.04 (Some verison of 1.1.1 dated 11 Sep 2018)
- Normal hardware accelerated OpenSSL 1.1.1i
- Non-accelerated version of 1.1.1i (`no-engine` `no-hw`)
- No assembler version of `1.1.1i` (`no engine` `no-hw` `no-threads` `-no-asm`)
- Debug version

Initially I just had the first three, and they all showed the problem at one point (all at around the same ten second period)

**Comment by lumpfish** [comment]
Maybe related: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/402

**Comment by sxa** [comment]
Two observations:
- It doesn't seem to show up much while those parallel loops are running on their own - I only seem to see issues when there is another job running on the machine at the same time (e.g. a Grinder) but it doesn't always fail when there's another job running
- It doesn't seem to fail (or at least hasn't during my testing) when a `noasm` version of OpenSSL isbeing used, therefore one option would be to update the OpenSSL to use one with `no-asm` - in addition to the above sets I've also tried with one that only has `no-asm` and not the other options present.

**Comment by sxa** [comment]
OK re-enabled the following after replacing libcrypto with a symlink to mine (ubuntu 16.04 excluded as it uses openssl 1.0 and I haven't built a copy of that)
- https://ci.adoptopenjdk.net/computer/test-docker-ubuntu1804-armv8-1 (`/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1`)
- https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-armv8-1 (`/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1`)
- https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2010-armv8-1 (`/usr/lib/aarch64-linux-gnu/libcrypto.so.1.1`)
- https://ci.adoptopenjdk.net/computer/test-docker-fedora33-armv8-1 (`/usr/lib6/libcrypto.so.1.1.1i`)

**Comment by sxa** [comment]
OK That experiment didn't quite go as well as I expected.

First some good news: I'd replaced `/usr/lib64/libcrypto.so.10` and `/usr/lib64/libssl.so.10` with links to `no-asm` versions on [build-packet-centos75-armv8-1](https://ci.adoptopenjdk.net/computer/build-packet-centos74-armv8-1x/) and while it gives warnings it appears to work

On [test-docker-ubuntu2004-armv8-1](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-armv8-1)

On [test-docker-ubuntu1804-armv8-1](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu1804-armv8-1) and [test-docker-ubuntu1604-armv8-1](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu1604-armv8-1) `/usr/lib/git-core/git-remote-https` is not linked against `libcrypto.so` directly, only `libk6crypto.so.3` and `libhcrypto.so.4` which I didn't have replacements for, therefore we got multiple failures on that machine. NOTE: On both systems `wget` is NOT linked against those two, so it likely works reliably, but not git.

**Comment by sxa** [comment]
These machiens will be decomissioned in favour of the ampere ones being set up as part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2078
