### ISSUE TITLE
build-scaleway-ubuntu1604-armv7-1 / 2 : jlm tests fail with Connection refused

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#1907]
The following tests fail on `build-scaleway-ubuntu1604-armv7-1` and `build-scaleway-ubuntu1604-armv7-2`. (jdk11 and jdk16.  The tests are not enabled on jdk8.)

TestJlmRemoteClassAuth_2
TestJlmRemoteClassNoAuth_2
TestJlmRemoteMemoryAuth_2
TestJlmRemoteMemoryNoAuth_2
TestJlmRemoteNotifierProxyAuth_2
TestJlmRemoteThreadAuth_2
TestJlmRemoteThreadNoAuth_2

The tests pass on `test-aahlenst-armv7-raspbian-pi4-2`.

Example failing job link: https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_sanity.system_arm_linux/20/consoleFull

Failing test error message:
```
java.rmi.ConnectException: Connection refused to host: 10.1.4.55
```

To rerun: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=hotspot&JDK_VENDOR=adoptopenjdk&BUILD_LIST=system&PLATFORM=aarch32_linux&TARGET=TestJlmRemoteClassAuth_2

Full failing test output:
```
07:37:37  STF 07:37:36.918 - +------ Step 3 - Running ClassProfiler Proxy test Server Process(with security)
07:37:37  STF 07:37:36.918 - | Start background process
07:37:37  STF 07:37:36.919 - |   Program:     /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdkbinary/j2sdk-image/bin/java
07:37:37  STF 07:37:36.919 - |   Mnemonic:    LT1
07:37:37  STF 07:37:36.919 - |   Echo:        ECHO_OFF
07:37:37  STF 07:37:36.919 - |   Expectation: NEVER
07:37:37  STF 07:37:36.919 - |
07:37:37  STF 07:37:36.922 - Running command: /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdkbinary/j2sdk-image/bin/java -Xmx256m -Dcom.sun.management.jmxremote.port=1234 -Dcom.sun.management.jmxremote.ssl.need.client.auth=true -Djavax.net.ssl.keyStore=/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/testkeys -Djavax.net.ssl.trustStore=/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/testkeys -Djavax.net.ssl.keyStoreType=JKS -Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.keyStorePassword=passphrase -Djavax.net.ssl.trustStorePassword=passphrase -Dcom.sun.management.jmxremote.password.file=/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/tmp/jmxremote.password -classpath /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/stf/stf.load/bin:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/stf/stf.core/bin:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/systemtest_prereqs/log4j/log4j-api.jar:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/systemtest_prereqs/log4j/log4j-core.jar:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/systemtest_prereqs/junit/junit.jar:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/systemtest_prereqs/junit/hamcrest-core.jar:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/openjdk-systemtest/openjdk.test.lang/bin:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/openjdk-systemtest/openjdk.test.util/bin:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/openjdk-systemtest/openjdk.test.math/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results -resultsPrefix 3.LT1. -timeLimit 30m -abortAtFailureLimit -1 -reportFailureLimit 1 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.mini-mix.totalNumberTests 20000000 -suite.mini-mix.inventoryFile /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/3.LT1.inventory/openjdk.test.load/config/inventories/mix/mini-mix.xml -suite.mini-mix.inventoryExcludeFile /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/3.LT1.inventory/openjdk.test.load/config/inventories/mix/mini-mix_exclude.xml -suite.mini-mix.inventoryExcludeFile /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/3.LT1.inventory/openjdk.test.load/config/inventories/util/util_exclude.xml -suite.mini-mix.threadCount 30 -suite.mini-mix.selection random -suite.mini-mix.seed -1 -suite.mini-mix.repeatCount 1 -suite.mini-mix.thinkingTime 0ms..0ms
07:37:37  STF 07:37:36.923 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/3.LT1.stderr
07:37:37  STF 07:37:36.923 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/3.LT1.stdout
07:37:37  STF 07:37:37.001 - 
07:37:37  STF 07:37:37.002 - +------ Step 4 - Running Monitoring Client with proxy connection(with security)
07:37:37  STF 07:37:37.002 - | Start background process
07:37:37  STF 07:37:37.002 - |   Program:     /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdkbinary/j2sdk-image/bin/java
07:37:37  STF 07:37:37.002 - |   Mnemonic:    CL1
07:37:37  STF 07:37:37.003 - |   Echo:        ECHO_ON
07:37:37  STF 07:37:37.003 - |   Expectation: CLEAN_RUN within 30m
07:37:37  STF 07:37:37.003 - |
07:37:37  STF 07:37:37.007 - Running command: /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdkbinary/j2sdk-image/bin/java -Xmx256m -Djavax.net.ssl.keyStore=/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/testkeys -Djavax.net.ssl.trustStore=/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/testkeys -Djavax.net.ssl.keyStoreType=JKS -Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.keyStorePassword=passphrase -Djavax.net.ssl.trustStorePassword=passphrase -Dcom.sun.management.jmxremote.password.file=/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/tmp/jmxremote.password -classpath /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/openjdk-systemtest/openjdk.test.jlm/bin:/home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/jvmtest/system/systemtest_prereqs/junit/junit.jar net.adoptopenjdk.test.jlm.remote.ClassProfiler proxy /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/scls_proxy.log /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/scls_proxy.csv auth controlRole control1 localhost 1234
07:37:37  STF 07:37:37.007 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/4.CL1.stderr
07:37:37  STF 07:37:37.007 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/results/4.CL1.stdout
07:37:37  STF 07:37:37.014 - 
07:37:37  STF 07:37:37.014 - +------ Step 5 - Wait for the processes to complete
07:37:37  STF 07:37:37.014 - | Wait for processes to meet expectations
07:37:37  STF 07:37:37.015 - |   Processes: [LT1, CL1]
07:37:37  STF 07:37:37.015 - |
07:37:37  STF 07:37:37.016 - Monitoring processes: CL1 LT1
07:37:41  CL1 j> 2021/02/07 07:37:39.446 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
07:37:41  CL1 j> 2021/02/07 07:37:40.668 Attempting to connect
07:37:43  CL1 j> 2021/02/07 07:37:42.574 Monitored VM not ready at Feb 7, 2021, 7:37:42 AM (attempt 1, elapsed 1438ms).
07:37:43  CL1 j> 2021/02/07 07:37:42.576 Waiting 5 secs and trying again...
07:37:48  CL1 j> 2021/02/07 07:37:47.578 Attempting to connect
07:37:52  CL1 j> 2021/02/07 07:37:51.286 Monitored VM not ready at Feb 7, 2021, 7:37:51 AM (attempt 2, elapsed 10614ms).
07:37:52  CL1 j> 2021/02/07 07:37:51.287 Waiting 5 secs and trying again...
07:37:57  CL1 j> 2021/02/07 07:37:56.289 Attempting to connect
07:37:57  CL1 j> 2021/02/07 07:37:56.377 Monitored VM not ready at Feb 7, 2021, 7:37:56 AM (attempt 3, elapsed 15706ms).
07:37:57  CL1 j> 2021/02/07 07:37:56.379 Waiting 5 secs and trying again...
07:38:03  CL1 j> 2021/02/07 07:38:01.391 Attempting to connect
07:38:03  CL1 j> 2021/02/07 07:38:01.441 Monitored VM not ready at Feb 7, 2021, 7:38:01 AM (attempt 4, elapsed 20768ms).
07:38:03  CL1 j> 2021/02/07 07:38:01.442 Waiting 5 secs and trying again...
07:38:07  CL1 j> 2021/02/07 07:38:06.494 Attempting to connect
07:38:07  CL1 j> 2021/02/07 07:38:06.717 Monitored VM not ready at Feb 7, 2021, 7:38:06 AM (attempt 5, elapsed 26045ms).
07:38:07  CL1 j> 2021/02/07 07:38:06.718 Waiting 5 secs and trying again...
07:38:12  CL1 j> 2021/02/07 07:38:11.720 Attempting to connect
07:38:12  CL1 j> 2021/02/07 07:38:11.847 Monitored VM not ready at Feb 7, 2021, 7:38:11 AM (attempt 6, elapsed 31175ms).
07:38:12  CL1 j> 2021/02/07 07:38:11.848 Waiting 5 secs and trying again...
07:38:17  CL1 j> 2021/02/07 07:38:16.850 Attempting to connect
07:38:17  CL1 j> 2021/02/07 07:38:16.947 Monitored VM not ready at Feb 7, 2021, 7:38:16 AM (attempt 7, elapsed 36275ms).
07:38:17  CL1 j> 2021/02/07 07:38:16.949 Waiting 5 secs and trying again...
07:38:22  CL1 j> 2021/02/07 07:38:21.950 Attempting to connect
07:38:22  CL1 j> 2021/02/07 07:38:22.017 Monitored VM not ready at Feb 7, 2021, 7:38:22 AM (attempt 8, elapsed 41345ms).
07:38:22  CL1 j> 2021/02/07 07:38:22.019 Waiting 5 secs and trying again...
07:38:27  CL1 j> 2021/02/07 07:38:27.020 Attempting to connect
07:38:27  CL1 j> 2021/02/07 07:38:27.107 Monitored VM not ready at Feb 7, 2021, 7:38:27 AM (attempt 9, elapsed 46435ms).
07:38:27  CL1 j> 2021/02/07 07:38:27.143 Waiting 5 secs and trying again...
07:38:33  CL1 j> 2021/02/07 07:38:32.144 Attempting to connect
07:38:33  CL1 j> 2021/02/07 07:38:32.207 Monitored VM not ready at Feb 7, 2021, 7:38:32 AM (attempt 10, elapsed 51535ms).
07:38:33  CL1 j> 2021/02/07 07:38:32.208 Waiting 5 secs and trying again...
07:38:40  CL1 j> 2021/02/07 07:38:37.210 Attempting to connect
07:38:40  CL1 j> 2021/02/07 07:38:37.382 Monitored VM not ready at Feb 7, 2021, 7:38:37 AM (attempt 11, elapsed 56710ms).
07:38:40  CL1 j> 2021/02/07 07:38:37.395 Waiting 5 secs and trying again...
07:38:42  CL1 j> 2021/02/07 07:38:42.396 Attempting to connect
07:38:43  CL1 j> 2021/02/07 07:38:42.457 Monitored VM not ready at Feb 7, 2021, 7:38:42 AM (attempt 12, elapsed 61785ms).
07:38:43  CL1 j> 2021/02/07 07:38:42.458 Waiting 5 secs and trying again...
07:38:48  CL1 j> 2021/02/07 07:38:47.459 Attempting to connect
07:38:48  CL1 j> 2021/02/07 07:38:47.491 Monitored VM not ready at Feb 7, 2021, 7:38:47 AM (attempt 13, elapsed 66819ms).
07:38:48  CL1 j> 2021/02/07 07:38:47.492 Waiting 5 secs and trying again...
07:38:53  CL1 j> 2021/02/07 07:38:52.493 Attempting to connect
07:38:53  CL1 j> 2021/02/07 07:38:52.576 Monitored VM not ready at Feb 7, 2021, 7:38:52 AM (attempt 14, elapsed 71905ms).
07:38:53  CL1 j> 2021/02/07 07:38:52.578 Waiting 5 secs and trying again...
07:38:58  CL1 j> 2021/02/07 07:38:57.579 Attempting to connect
07:38:58  CL1 j> 2021/02/07 07:38:57.638 Monitored VM not ready at Feb 7, 2021, 7:38:57 AM (attempt 15, elapsed 76967ms).
07:38:58  CL1 j> 2021/02/07 07:38:57.640 Waiting 5 secs and trying again...
07:39:03  CL1 j> 2021/02/07 07:39:02.641 Attempting to connect
07:39:03  CL1 j> 2021/02/07 07:39:02.844 Monitored VM not ready at Feb 7, 2021, 7:39:02 AM (attempt 16, elapsed 82172ms).
07:39:03  CL1 j> 2021/02/07 07:39:02.845 Waiting 5 secs and trying again...
07:39:08  CL1 j> 2021/02/07 07:39:07.846 Attempting to connect
07:39:08  CL1 j> 2021/02/07 07:39:07.956 Monitored VM not ready at Feb 7, 2021, 7:39:07 AM (attempt 17, elapsed 87285ms).
07:39:08  CL1 j> 2021/02/07 07:39:07.958 Waiting 5 secs and trying again...
07:39:14  CL1 j> 2021/02/07 07:39:12.959 Attempting to connect
07:39:14  CL1 j> 2021/02/07 07:39:13.007 Monitored VM not ready at Feb 7, 2021, 7:39:13 AM (attempt 18, elapsed 92335ms).
07:39:14  CL1 j> 2021/02/07 07:39:13.008 Waiting 5 secs and trying again...
07:39:19  CL1 j> 2021/02/07 07:39:18.010 Attempting to connect
07:39:19  CL1 j> 2021/02/07 07:39:18.106 Monitored VM not ready at Feb 7, 2021, 7:39:18 AM (attempt 19, elapsed 97435ms).
07:39:19  CL1 j> 2021/02/07 07:39:18.107 Waiting 5 secs and trying again...
07:39:24  CL1 j> 2021/02/07 07:39:23.109 Attempting to connect
07:39:24  CL1 j> 2021/02/07 07:39:23.176 Monitored VM not ready at Feb 7, 2021, 7:39:23 AM (attempt 20, elapsed 102505ms).
07:39:24  CL1 j> 2021/02/07 07:39:23.177 Waiting 5 secs and trying again...
07:39:29  CL1 j> 2021/02/07 07:39:28.223 Attempting to connect
07:39:29  CL1 j> 2021/02/07 07:39:28.428 Monitored VM not ready at Feb 7, 2021, 7:39:28 AM (attempt 21, elapsed 107756ms).
07:39:29  CL1 j> 2021/02/07 07:39:28.429 Waiting 5 secs and trying again...
07:39:34  CL1 j> 2021/02/07 07:39:33.430 Attempting to connect
07:39:34  CL1 j> 2021/02/07 07:39:33.558 Monitored VM not ready at Feb 7, 2021, 7:39:33 AM (attempt 22, elapsed 112885ms).
07:39:34  CL1 j> 2021/02/07 07:39:33.559 Waiting 5 secs and trying again...
07:39:39  CL1 j> 2021/02/07 07:39:38.561 Attempting to connect
07:39:39  CL1 j> 2021/02/07 07:39:38.643 Monitored VM not ready at Feb 7, 2021, 7:39:38 AM (attempt 23, elapsed 117951ms).
07:39:39  CL1 j> 2021/02/07 07:39:38.645 Waiting 5 secs and trying again...
07:39:45  CL1 j> 2021/02/07 07:39:43.646 Attempting to connect
07:39:45  CL1 j> 2021/02/07 07:39:43.776 Monitored VM not ready at Feb 7, 2021, 7:39:43 AM (attempt 24, elapsed 123105ms).
07:39:45  CL1 j> 2021/02/07 07:39:43.777 Waiting 5 secs and trying again...
07:39:50  CL1 j> 2021/02/07 07:39:48.778 Attempting to connect
07:39:50  CL1 j> 2021/02/07 07:39:48.805 Monitored VM not ready at Feb 7, 2021, 7:39:48 AM (attempt 25, elapsed 128133ms).
07:39:50  CL1 j> 2021/02/07 07:39:48.806 Waiting 5 secs and trying again...
07:39:54  CL1 j> 2021/02/07 07:39:53.808 Attempting to connect
07:39:54  CL1 j> 2021/02/07 07:39:53.846 Monitored VM not ready at Feb 7, 2021, 7:39:53 AM (attempt 26, elapsed 133175ms).
07:39:54  CL1 j> 2021/02/07 07:39:53.854 Waiting 5 secs and trying again...
07:39:59  CL1 j> 2021/02/07 07:39:58.855 Attempting to connect
07:39:59  CL1 j> 2021/02/07 07:39:58.899 Monitored VM not ready at Feb 7, 2021, 7:39:58 AM (attempt 27, elapsed 138228ms).
07:39:59  CL1 j> 2021/02/07 07:39:58.901 Waiting 5 secs and trying again...
07:40:04  CL1 j> 2021/02/07 07:40:03.902 Attempting to connect
07:40:04  CL1 j> 2021/02/07 07:40:03.942 Monitored VM not ready at Feb 7, 2021, 7:40:03 AM (attempt 28, elapsed 143270ms).
07:40:04  CL1 j> 2021/02/07 07:40:03.983 Waiting 5 secs and trying again...
07:40:09  CL1 j> 2021/02/07 07:40:08.985 Attempting to connect
07:40:09  CL1 j> 2021/02/07 07:40:09.044 Monitored VM not ready at Feb 7, 2021, 7:40:09 AM (attempt 29, elapsed 148355ms).
07:40:09  CL1 j> 2021/02/07 07:40:09.045 Waiting 5 secs and trying again...
07:40:15  CL1 j> 2021/02/07 07:40:14.046 Attempting to connect
07:40:15  CL1 j> 2021/02/07 07:40:14.322 Failed to connect to Monitored VM after 30 attempts in 153 seconds - giving up.  Connection Exception received is below:
07:40:15  CL1 stderr java.rmi.ConnectException: Connection refused to host: 10.1.4.55; nested exception is: 
07:40:15  CL1 stderr 	java.net.ConnectException: Connection refused
07:40:15  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:623)
07:40:15  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
07:40:15  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
07:40:15  CL1 stderr 	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:132)
07:40:15  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIServerImpl_Stub.newClient(RMIServerImpl_Stub.java:83)
07:40:15  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2105)
07:40:15  CL1 stderr 	at java.management.rmi/javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:321)
07:40:15  CL1 stderr 	at java.management/javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
07:40:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.doConnect(ServerConnector.java:273)
07:40:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.getSecureServerConnection(ServerConnector.java:170)
07:40:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ServerConnector.<init>(ServerConnector.java:82)
07:40:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.<init>(ClassProfiler.java:72)
07:40:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:89)
07:40:15  CL1 stderr Caused by: java.net.ConnectException: Connection refused
07:40:15  CL1 stderr 	at java.base/sun.nio.ch.Net.connect0(Native Method)
07:40:15  CL1 stderr 	at java.base/sun.nio.ch.Net.connect(Net.java:576)
07:40:15  CL1 stderr 	at java.base/sun.nio.ch.Net.connect(Net.java:565)
07:40:15  CL1 stderr 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
07:40:15  CL1 stderr 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
07:40:15  CL1 stderr 	at java.base/java.net.Socket.connect(Socket.java:645)
07:40:15  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
07:40:15  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:149)
07:40:15  CL1 stderr 	at java.base/sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
07:40:15  CL1 stderr 	at java.rmi/javax.rmi.ssl.SslRMIClientSocketFactory.createSocket(SslRMIClientSocketFactory.java:121)
07:40:15  CL1 stderr 	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:617)
07:40:15  CL1 stderr 	... 12 more
07:40:15  CL1 stderr Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.management.MBeanServerConnection.isInstanceOf(javax.management.ObjectName, String)" because "connection" is null
07:40:15  CL1 stderr 	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:651)
07:40:15  CL1 stderr 	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:611)
07:40:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.getStatsViaProxy(ClassProfiler.java:117)
07:40:15  CL1 stderr 	at net.adoptopenjdk.test.jlm.remote.ClassProfiler.main(ClassProfiler.java:102)
07:40:15  STF 07:40:15.379 - **FAILED** Process CL1 ended with exit code (1) and not the expected exit code/s (0)
07:40:15  STF 07:40:15.380 - Monitoring Report Summary:
07:40:15  STF 07:40:15.381 -   o Process CL1 ended with exit code (1) and not the expected exit code/s (0)
07:40:15  STF 07:40:15.381 -   o Process LT1 is still running as expected
07:40:15  STF 07:40:15.385 - Killing processes: CL1 LT1
07:40:15  STF 07:40:15.386 -   o Process LT1 pid 8225 stop()
07:40:27  STF 07:40:25.394 -   o Process LT1 pid 8225 terminate()
07:40:27  STF 07:40:26.396 -   o Process LT1 pid 8225 killed
07:40:27  STF 07:40:26.396 -   o Process CL1 pid 8226 is not running
07:40:27  **FAILED** at step 5 (Wait for the processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_arm_linux/openjdk-tests/TKG/../TKG/output_16126791957891/TestJlmRemoteClassAuth_2/20210207-073722-TestJlmRemoteClassAuth/execute.pl line 173.
07:40:27  STF 07:40:26.877 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by Haroon-Khel** [comment]
Another improper line in /etc/hosts. The line
`10.1.4.55 build-scaleway-ubuntu1604-armv7-1.adoptopenjdk.net build-scaleway-ubuntu1604-armv7-1`
Should be
`212.47.233.28 build-scaleway-armv7-ubuntu16-04-1.adoptopenjdk.net build-scaleway-armv7-ubuntu16-04-1`
The test target `TestJlmRemoteClassAuth_2` passed
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7323/

**Comment by Haroon-Khel** [comment]
In this case, I think the improper line was put into /etc/hosts by the playbooks. Ansible seems to pick up the wrong ipv4 address when running a playbook on the machine
`"ansible_default_ipv4.address: 10.1.14.2"`
Though the improper line has the private address 10.1.4.55, I suspect the address may have changed since the playbooks ran on this machine. Either way, I am not sure why ansible isnt able to detect the public ip address

**Comment by Haroon-Khel** [comment]
Same with build-scaleway-ubuntu1604-armv7-2:
`"ansible_default_ipv4.address: 10.1.40.104",`

Ive manually fixed its /etc/hosts file too

**Comment by Haroon-Khel** [comment]
Running all the targets on build-scaleway-ubuntu1604-armv7-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7327/console

**Comment by Haroon-Khel** [comment]
TestJlmRemoteClassNoAuth_2 and TestJlmRemoteMemoryAuth_2 have also passed on build-scaleway-ubuntu1604-armv7-1
https://ci.adoptopenjdk.net/job/Grinder/7324/console

**Comment by Haroon-Khel** [comment]
Running the remaining targets, TestJlmRemoteMemoryNoAuth_2, TestJlmRemoteNotifierProxyAuth_2, TestJlmRemoteThreadAuth_2, TestJlmRemoteThreadNoAuth_2, on build-scaleway-ubuntu1604-armv7-1
https://ci.adoptopenjdk.net/job/Grinder/7328/console

**Comment by Haroon-Khel** [comment]
On -2, all targets pass except for

**Comment by lumpfish** [comment]
Different problem: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/274

**Comment by Haroon-Khel** [comment]
Considering that whats left on this issue is being covered by another one, https://github.com/adoptium/aqa-systemtest/issues/274, Im going to close this one
