### ISSUE TITLE
Ansible request for AWX to deploy to macos

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1910]
Our AWX server does not currently have a template for deploying to macos systems. We should add that and ensure that it is "safe" to deploy across all machines

**Comment by Haroon-Khel** [comment]
We dont have a separate playbook for macos. We run the UNIX playbook, which contains tasks that only run if it detects Macos. Would a seperate template be redundant?

**Comment by sxa** [comment]
As long as it works probably not if the `hosts` line in the top of the top level `main.yml` is ok without any tweaks.

**Comment by Haroon-Khel** [comment]
test-macstadium-macos1012-x64-1 is unreachable

fatal: [test-macstadium-macos1012-x64-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '208.83.1.46' (ECDSA) to the list of known hosts.\r\nno such identity: /var/lib/awx/.ssh/id_rsa: No such file or directory\r\nAdministrator@208.83.1.46: Permission denied (publickey,password,keyboard-interactive).", "unreachable": true}

As is test-macincloud-macos1010-x64-2

**Comment by Haroon-Khel** [comment]
Unreachable:
test-macstadium-macos1014-x64-1
test-macstadium-macos1014-x64-2
test-macstadium-macos1014-x64-3
test-macstadium-macos1015-x64-1
build-macstadium-macos1010-x64-1
build-macstadium-macos1014-x64-2
build-macstadium-macos1014-x64-1

Hanged:
test-macstadium-macos11-arm64-1 (also hung when I tried to ssh in)

Ran on (but had errors):
test-macstadium-macos11-arm64-2

**Comment by sxa** [comment]
Hmmm - I thought @gdams had them all configured via Bastillion to have the AWX key and others. It looks like the following ones should be in there (I believe macstadium generally uses `administrator`, macincloud `admin` which is why you're seeing that difference):

- build-macstadium-macos1010-x64-1
- build-macstadium-macos1014-x64-1
- build-macstadium-macos1014-x64-2
- test-macincloud-macos1010-x64-1
- test-macincloud-macos1010-x64-2
- test-macstadium-macos1012-x64-1
- test-macstadium-macos1013-x64-1
- test-macstadium-macos1014-x64-1
- test-macstadium-macos1014-x64-2
- test-macstadium-macos1014-x64-3
- test-macstadium-macos1015-x64-1
- test-macstadium-macos11-arm64-1
- test-macstadium-macos11-arm64-2

**Comment by Haroon-Khel** [comment]
AWX isnt able to connect to the nine machines, test-nine-macos1015-x64-1 and test-nine-macos1015-x64-2, but I suppose that's because theyre behind a firewall? Either way, its not an unreachable error that returns, its a `does not match any hosts` error:

```
[WARNING]: Could not match supplied host pattern, ignoring: test-nine-
macos1015-x64-2
ERROR! Specified hosts and/or --limit does not match any hosts
```

**Comment by sxa** [comment]
OK Looks like they hadn't been added to any of the profiles so they didn't have anything other than the default keys. All the ones ending in `-1` ought to be ok now.

**Comment by Haroon-Khel** [comment]
The condition in the [Common role](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/8c71ce4fe20172d2a81ad0c22460d745f29f6ef4/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml#L99)

```
  when:
    - not macos_version | regex_search("10.12")
  tags: build_tools
```

Should be 

```
  when:
    - not macos_version.stdout | regex_search("10.12")
  tags: build_tools
```

since `macos_version` is a registered variable. This gives the following error

```
fatal: [test-macstadium-macos1014-x64-1]: FAILED! => {"msg": "The conditional check 'not macos_version | regex_search(\"10.12\")' failed. The error was: Unexpected templating type error occurred on ({% if not macos_version | 
regex_search(\"10.12\") %} True {% else %} False {% endif %}): expected string or bytes-like object\n\nThe error appears to be in '/tmp/awx_763_m5aop2n8/project/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml': 
line 93, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Build Tool Packages NOT macOS 10.12\n  ^ here\n"}
```

**Comment by Haroon-Khel** [comment]
@sxa 
test-macincloud-macos1010-x64-2 and test-macincloud-macos1010-x64-1 are still unreachable. It would be ideal if I could test the playbook on either of these, since they are not currently being used by a jenkins job, hence I could bring them temporarily offline. Preferably -2

**Comment by sxa** [comment]
`-1` already seems to have yours and AWX's key on it (admin user) as per [the earlier change](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1910#issuecomment-795620149)

Can you post the error you're getting for `-1` (and whether it's from AWX or a connection using your own machine)?

**Comment by Haroon-Khel** [comment]
```
TASK [Gathering Facts] *********************************************************
fatal: [test-macincloud-macos1010-x64-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via
 ssh: Connection closed by 74.80.250.151 port 22", "unreachable": true}
```

Same on -2. Ive just run this now. Bare in mind im using the Deploy UNIX playbook to macos template, not the Deploy UNIX playbook template. Ill test it on the latter now, depsite both having the same ssh admin key credential

**Comment by sxa** [comment]
Hmmm I put the verbosity level up to maximum on the AWX job and re-run it (I've put it back now). After being somewhat confused it looks like fails when you try to connect from a RHEL8/CentOS8 host (The AWX docker images are based on CentOS8, but I've tried it on a couple of other RHEL8 systems and get the same problem (Either try with one of our other ones, or `docker run -it centos:8 /bin/bash` then `dnf install openssh-clients` `ssh -vvvv 74.80.250.151` and you'll see it kicks you out without even attempting to prompt for a password or anything else - that's what we're seeing ...

**Comment by sxa** [comment]
As far as I can tell this only affects macos 10.10 systems - the later ones seem to be ok (https://awx.adoptopenjdk.net/#/jobs/playbook/797?job_search=page_size:20;order_by:-finished;not__launch_type:sync is a run on `test-macstadium-macos1012-x64-1`).

**Comment by sxa** [comment]
OK the problem was that the CentOS8 ssh client by default does not allow the `aes128-ctr` cipher. I've enabled it in the ssh_config of the `awx_task` container and it now [seems to work](https://awx.adoptopenjdk.net/#/jobs/playbook/805) on the 10.10 boxes

**Comment by sxa** [comment]
At least for now the [macos11 aarch64 machines seem to be stalling](https://awx.adoptopenjdk.net/#/jobs/playbook/807) - I would possibly ignore them for now as we only really want to the x64 ones

**Comment by Haroon-Khel** [comment]
I see that test-macincloud-macos1010-x64-1 is now no longer unreachable so ive taken it down in jenkins to run the playbook on. -2 is still unreachable. Im using the unix playbook template, so this should not disrupt the jobs that you have pending/running

**Comment by Haroon-Khel** [comment]
While upgrading all packages

```
TASK [Common : Upgrade installed packages] *************************************
fatal: [test-macincloud-macos1010-x64-1]: FAILED! => {"changed": false, "msg": "Error: /usr/local/Cellar is not writable. You should change the\nownership and permissions of /usr/local/Cellar back to your\nuser account:\n  sudo chown -R $(whoami) /usr/local/Cellar\nWarning: You are using macOS 10.10.\n
We (and Apple) do not provide support for this old version.\n
You will encounter build failures with some formulae.\n
Please create pull requests instead of asking for help on Homebrew's GitHub,\nDiscourse, Twitter or IRC. You are responsible for resolving any issues you\nexperience while you are running this old version.\n\nError: The following directories are not writable by your user:\n
/usr/local/Cellar\n
/usr/local/Homebrew\n
/usr/local/include\n
/usr/local/lib/pkgconfig\n
/usr/local/share/aclocal\n
/usr/local/share/info\n
/usr/local/share/zsh\n/usr/local/share/zsh/site-functions\n
/usr/local/var/homebrew/linked\n
/usr/local/var/homebrew/locks\n
\nYou should change the ownership of these directories to your user.\n
  sudo chown -R $(whoami) /usr/local/Cellar /usr/local/Homebrew /usr/local/include /usr/local/lib/pkgconfig /usr/local/share/aclocal /usr/local/share/info /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew/linked /usr/local/var/homebrew/locks\n
\nAnd make sure that your user has write permission.\n
  chmod u+w /usr/local/Cellar /usr/local/Homebrew /usr/local/include /usr/local/lib/pkgconfig /usr/local/share/aclocal /usr/local/share/info /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew/linked /usr/local/var/homebrew/locks"}
```

**Comment by sxa** [comment]
My gut feel is that this is a reasonable thing to do. @gdams do you know if there's any reason why the macincloud systems are set up with an admin user that doesn't have these privileges, or any other reason why we should add it to the `admin` group?

**Comment by sxa** [comment]
@gdams Why is e.g. `/usr/local/Cellar` on `test-macincloud-macos1010-x64-1` full of files owned by the `zeus` user - did you install as that user instead of `admin`?

**Comment by Haroon-Khel** [comment]
Various errors found. Ive documented them here https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2042

**Comment by Haroon-Khel** [comment]
The ansible version on awx

```
ansible-playbook 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

**Comment by Haroon-Khel** [comment]
Ive updated AWX's ansible version to 2.11.1

**Comment by Haroon-Khel** [comment]
After a preliminary run of the Unix playbook our mac machines

```
Unreachable
```

test-macstadium-macos1012-x64-1 
test-macstadium-macos1013-x64-1
test-macincloud-macos1010-x64-2
build-macstadium-macos1014-x64-1
build-macstadium-macos1014-x64-2

```
TASK [macos_codesign : Set Jenkins user password] ******************************
fatal: [test-macstadium-macos1014-x64-1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'macOS_Jenkins_Password' is undefined\n\nThe error appears to be in '/tmp/awx_893_u3elnyft/project/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/macos_codesign/tasks/main.yml': line 6, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set Jenkins user password\n  ^ here\n"}
```

test-macstadium-macos1014-x64-1 
test-macstadium-macos1014-x64-2
test-macstadium-macos1014-x64-3
test-macstadium-macos1015-x64-1

```
TASK [Common : Upgrade installed packages] *************************************
fatal: [test-macincloud-macos1010-x64-1]: FAILED! => {"changed": false, "msg": "Warning: You are using macOS 10.10.\nWe (and Apple) do not provide support for this old version.\nYou will encounter build failures with some formulae.\nPlease create pull requests instead of asking for help on Homebrew's GitHub,\nTwitter or any other official channels. You are responsible for resolving\nany issues you experience while you are running this\nold version.\n\nError: ruby: no bottle available!\nYou can try to install from source with:\n  brew install --build-from-source ruby\nPlease note building from source is unsupported. You will encounter build\nfailures with some formulae. If you experience any issues please create pull\nrequests instead of asking for help on Homebrew's GitHub, Twitter or any other\nofficial channels.\nError: coreutils: no bottle available!\nYou can try to install from source with:\n  brew install --build-from-source coreutils\nPlease note building from source is unsupported. You will enc…

```
test-macincloud-macos1010-x64-1

```
Host key has changed
```

test-macstadium-macos11-arm64-1
test-macstadium-macos11-arm64-2

```
ERROR! Specified hosts and/or --limit does not match any hosts
```

build-macstadium-macos1014-x64-3
build-macstadium-macos11-arm64-1
build-macstadium-macos11-arm64-2

**Comment by Haroon-Khel** [comment]
ping @sxa

**Comment by sxa** [comment]
@Haroon-Khel I'd double check that all of the "unavailable" ones are in the inventory file properly and that AWX has the correct list. I'm not sure where the last message is coming from - that looks like you've explicitly specified a machine that isn't in the AWX copy of the inventory. Are the unreachables all not on the network or not able to be connected to over ssh?

**Comment by Haroon-Khel** [comment]
The 'unreachable' are in inventory.yml and in the awx inventory (they are searchable in the hosts section). The machines in the  `does not match any hosts` are not found in the awx inventory, but are in jenkins and inventory.yml

In unreachable:

test-macstadium-macos1012-x64-1 pingable, I can ssh into
test-macstadium-macos1013-x64-1 pingable, I cant ssh into (public key isnt on) but jenkins can (job running on it)
test-macincloud-macos1010-x64-2 not pingable, jenkins agent says started in logs, but not on main page
build-macstadium-macos1014-x64-1 pingable, I cant ssh into (public key isnt on)
build-macstadium-macos1014-x64-2 pingable, I cant ssh into (public key isnt on)

In `does not match any hosts`

build-macstadium-macos1014-x64-3 is pingable, online in jenkins, I cant ssh into (public key isnt on)
build-macstadium-macos11-arm64-1 is pingable, online in jenkins, I cant ssh into (public key isnt on)
build-macstadium-macos11-arm64-2 is pingable, online in jenkins, I cant ssh into (public key isnt on)

@gdams Could you give me access to 

build-macstadium-macos1014-x64-3
build-macstadium-macos11-arm64-1
build-macstadium-macos11-arm64-2 
test-macstadium-macos1013-x64-1
build-macstadium-macos1014-x64-1
build-macstadium-macos1014-x64-2

**Comment by Haroon-Khel** [comment]
I think the reason AWX isnt finding the build-macstadium hosts is because they were added to inventory.yml 2 months ago, https://github.com/adoptium/infrastructure/commit/54968f03194ffc1f9389e1fe2cc46e48b934b922 and https://github.com/adoptium/infrastructure/commit/fbfe092f1940bf382a1468bf47e0da16b741efbe, and AWX's inventory has not synced with github.

I tried to manually sync the inventory (there's a sync button when you navigate to the source tab of the inventory), and received a python related error

```
    6.156 INFO     Updating inventory 2: Dynamic inventory from github
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the 
controller starting with Ansible 2.12. Current version: 3.6.8 (default, Apr 16 
2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]. This feature will be 
removed from ansible-core in version 2.12. Deprecation warnings can be disabled
 by setting deprecation_warnings=False in ansible.cfg.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1149, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1039, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 212, in load
    base_args = self.get_base_args()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 142, in get_base_args
    if this_version >= Version('2.5'):
  File "/usr/lib64/python3.6/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/lib64/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by Haroon-Khel** [comment]
As per https://github.com/adoptium/infrastructure/wiki/Ansible-AWX#inventory Ive changed the Inventory source to `ansible/plugins/adoptopenjdk_yaml.py`. The inventory still will not sync

**Comment by Haroon-Khel** [comment]
Fixed the inventory sync problem. An AWX python script was having trouble getting the ansible version, which caused the error posted above. I have hardcoded the ansible version into the script to circumvent this problem. The inventory now syncs when initiated

**Comment by sxa** [comment]
Looks like we've had some green runs, but not with a full playbook so I'm moving this to July

**Comment by sxa** [comment]
Hmmm the bastillion keys seem to be on the `test-macstadium-macos11-arm64-1` systems so I'm not sure why they would be unreachable. Looks like they haven't been set up on Bastillion yet :'(

**Comment by Haroon-Khel** [comment]
Anything under 10.13 is too old for the `Upgrade installed packages` task in the `Common` role. A simple condition to skip this task on those OS's seems like a good temp fix.

The Xcode role fails because AWX does not have access to the environment variables required for this role. Those being
https://github.com/adoptium/infrastructure/blob/0c92087baac090b909cdbf4cf81f2148aa367542/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml#L62

**Comment by Haroon-Khel** [comment]
On the bright side, a quick build job on the machines, after the playbook run, shows that builds still work. 

```
jdk_util_0
jdk_util_1
```
These fail on jdk 11 hotspot due to some locale and other errors

```
11:59:07  STDERR:
11:59:07  java.lang.RuntimeException: Uncaught exception thrown in test method TestSimpleDisplayNames
11:59:07  
11:59:07  	at LocaleTestFmwk.err(LocaleTestFmwk.java:204)
11:59:07  	at LocaleTestFmwk.errln(LocaleTestFmwk.java:209)
11:59:07  	at LocaleTestFmwk.run(LocaleTestFmwk.java:152)
11:59:07  	at LocaleTest.main(LocaleTest.java:177)
11:59:07  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:59:07  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:59:07  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:59:07  	at java.lang.reflect.Method.invoke(Method.java:498)
11:59:07  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
11:59:07  	at java.lang.Thread.run(Thread.java:748)
11:59:07  
11:59:07  JavaTest Message: Test threw exception: java.lang.RuntimeException
11:59:07  JavaTest Message: shutting down test
```

```
12:05:19  java.lang.RuntimeException: Failed.
12:05:19  	at Bug8040211.main(Bug8040211.java:131)
12:05:19  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:05:19  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:05:19  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:05:19  	at java.lang.reflect.Method.invoke(Method.java:498)
12:05:19  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
12:05:19  	at java.lang.Thread.run(Thread.java:748)

```

```
12:05:19    testCreateLocaleCanonicalValid Passed
12:05:19    testGetDisplayName {
12:05:19      English display name for zh-Hans: expected 'Chinese (Simplified)' but got 'Chinese (Simplified Han)'
12:05:19      English display name for zh-Hant: expected 'Chinese (Traditional)' but got 'Chinese (Traditional Han)'
12:05:19      English display name for zh-Hans-CN: expected 'Chinese (Simplified,China)' but got 'Chinese (Simplified Han,China)'
12:05:19      English display name for und-Hans: expected 'Simplified' but got 'Simplified Han'
```

These tests failed before and after the playbook run

**Comment by sxa** [comment]
@Haroon-Khel What's the current status on this - do we have outstanding issues that need resolving ref the locales for example?

**Comment by Haroon-Khel** [comment]
test-macincloud-macos1010-x64-2 is still unreachable
test-macstadium-macos11-arm64-1 and test-macstadium-macos11-arm64-2 are unreachable because their remote host id has changed (were they reinstalled?)

The locale issue (I think) is documented in a separate infra issue, I'll see if I can dig it out

**Comment by sxa** [comment]
> test-macincloud-macos1010-x64-2 is still unreachable

Fixed via https://github.com/adoptium/infrastructure/issues/2476#issuecomment-1056810719, although those 1010 machines are going to be decomissioned soon.

> test-macstadium-macos11-arm64-1 and test-macstadium-macos11-arm64-2 are unreachable because their remote host id has changed (were they reinstalled?)

Fixed by clearing the previous host key from the `known_hosts` file in the `awx_task` container, although from looking at it it's now failing to locate the private key it wants to be able to log in, although the connections are still working ok for other Linux machines.

We've got two new machines via https://github.com/adoptium/infrastructure/pull/2494/files and have put a minimal installation on it (ant+contrib+/usr/local/bin symlink, jenkins user, boot JDK, Xcode license accept, and adding the hostname to /etc/hosts) but we should look at running a full playbook on at least one of these (based on an earlier comment it sounded like we hadn't used the playbooks from scratch yet)

> The locale issue (I think) is documented in a separate infra issue, I'll see if I can dig it out

Was this one resolved?

**Comment by Haroon-Khel** [comment]
>We've got two new machines via https://github.com/adoptium/infrastructure/pull/2494/files and have put a minimal installation on it (ant+contrib+/usr/local/bin symlink, jenkins user, boot JDK, Xcode license accept, and adding the hostname to /etc/hosts) but we should look at running a full playbook on at least one of these (based on an earlier comment it sounded like we hadn't used the playbooks from scratch yet)

I'll get started on deploying the playbook to one of these machines

> The locale issue (I think) is documented in a separate infra issue, I'll see if I can dig it out
> 
> Was this one resolved?

I must have been mistaken when I thought it was a separate infra issue since I cannot seem to find it. I'll rerun the jdk_util tests to see if the problem persists

**Comment by Haroon-Khel** [comment]
> Anything under 10.13 is too old for the `Upgrade installed packages` task in the `Common` role. A simple condition to skip this task on those OS's seems like a good temp fix.

@sxa We still have [test-macstadium-macos1012-x64-1](https://ci.adoptopenjdk.net/computer/test-macincloud-macos1201-x64-1/search/?q=test-macstadium-macos1012-x64-1) and 
[test-macstadium-macos1013-x64-1](https://ci.adoptopenjdk.net/computer/test-macincloud-macos1201-x64-1/search/?q=test-macstadium-macos1013-x64-1) whose packages brew will not upgrade. Do we have any plans to decommission those and replace them with newer machines?

**Comment by sxa** [comment]
Hmmm we have nothing in plan at the moment, however since we only list 10.14 and later as supported on https://adoptium.net/supported_platforms.html that would definitely be an option. Is the error the same as [the one you had on 10.10](https://github.com/adoptium/infrastructure/issues/1910#issuecomment-799499192)? If so we should definitely consider it as part of #2496

**Comment by sxa** [comment]
Also, could you download and try and run JDK11 and 17 on 10.13 and check if they work at all? (Extract tarball, run `java -version` from it) I know 17 doesn't work on 10.10.

**Comment by Haroon-Khel** [comment]
Both JDKs work on [macos10.13](https://ci.adoptopenjdk.net/computer/test-macstadium-macos1013-x64-1/). 
```
test-macstadium-macos1013-x64-1:~ administrator$ ./jdk-11.0.14.1+1/Contents/Home/bin/java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)
```
```
test-macstadium-macos1013-x64-1:~ administrator$ ./jdk-17.0.2+8/Contents/Home/bin/java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

**Comment by Haroon-Khel** [comment]
>We've got two new machines via https://github.com/adoptium/infrastructure/pull/2494/files and have put a minimal installation on it (ant+contrib+/usr/local/bin symlink, jenkins user, boot JDK, Xcode license accept, and adding the hostname to /etc/hosts) but we should look at running a full playbook on at least one of these (based on an earlier comment it sounded like we hadn't used the playbooks from scratch yet)

@sxa Any reservations on having the second machine setup to completion?

**Comment by sxa** [comment]
> @sxa Any reservations on having the second machine setup to completion?

While we have a "clean" machine I'd recommendtrying to run a build pipeline on the one you've set up (Say, JDK17 or 19) and making sure that the one that has had the playbook run on it does build properly first. That way if there is any remedial action required we can do that from scratch on the second one.

**Comment by Haroon-Khel** [comment]
One thing missing from the awx deployment of the playbook is the variable `Apple_ID_User`, here https://github.com/adoptium/infrastructure/blob/87c0db93880c4b0c16449dfab3f46e9e3f853730/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml#L67

```
TASK [Xcode : Install Xcode on Intel Macs] *************************************
fatal: [test-macincloud-macos1201-x64-1]: FAILED! => {"msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'Apple_ID_User' is undefined\n\nThe error appears to be in '/tmp/awx_1285_7hdbqt40/project/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Xcode/tasks/main.yml': line 69, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# with older macOS won't have Xcode installed.\n- name: Install Xcode on Intel Macs\n  ^ here\n"}
```

In the Xcode role, other variables (which awx will likewise not be able to find) are "{{ Apple_ID_Password }}" and "{{ FASTLANE_SESSION }}"

Awx is able to pull the vendor files/secrets from the secrets repo, which is where I assume these variables are. So I am not sure why it is not able to find these variables. @gdams Any ideas?

**Comment by Haroon-Khel** [comment]
>We've got two new machines via https://github.com/adoptium/infrastructure/pull/2494/files and have put a minimal installation on it (ant+contrib+/usr/local/bin symlink, jenkins user, boot JDK, Xcode license accept, and adding the hostname to /etc/hosts) but we should look at running a full playbook on at least one of these (based on an earlier comment it sounded like we hadn't used the playbooks from scratch yet)

@sxa I see that you've manually installed xcode on these machines already (which suggests that the xcode role is not idempotent?). I've kicked off a jdk17 build here https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-mac-x64-hotspot/74/console

**Comment by sxa** [comment]
> @sxa I see that you've manually installed xcode on these machines 

I did not install Xcode - it had been preinstalled on the systems. I did do a license accept for it that was a prereq to it being used.

**Comment by Haroon-Khel** [comment]
Build seems to be failing
```
13:03:49  [SUCCESS] Executing local file at /Users/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-mac-x64-hotspot/build-farm/platform-specific-configurations/mac.sh
13:03:49  [WARNING] You may be asked for your su user password, attempting to switch Xcode version to /Applications/Xcode.app
13:03:49  sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
13:03:49  sudo: a password is required
```
Fails when executing this
https://github.com/adoptium/temurin-build/blob/c4842313fe56dacd4986e35d34d132db979bf8df/build-farm/platform-specific-configurations/mac.sh#L68

**Comment by Haroon-Khel** [comment]
Rerunning build job https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-mac-x64-hotspot/76/console

**Comment by sxa** [comment]
> `sudo xcode-select --switch "/Applications/Xcode.app"`

While I'm somewhat curious as to why we use a different version for 11 than all of the other releases if we determine that this is required and there's no other way to do it then we should add a suitably restricted (i.e. only allow `xcode-select --switch`) into the `/etc/sudoers` setup for the jenkins user.

**Comment by Haroon-Khel** [comment]
Since https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-mac-x64-hotspot/76/console passed, I will begin setting up the second machine 216.39.74.140. Any changes to its xcode-select config can be made after setup

**Comment by Haroon-Khel** [comment]
Since the move to awx2, I will close this issue once we get a MacOS specific deployment job. It currently uses the Unix one

**Comment by sxa** [comment]
@Haroon-Khel Presumably you an create the job yourself since you have admin access to the server?

**Comment by sxa** [comment]
@Haroon-Khel Are you able to progress this?

**Comment by Haroon-Khel** [comment]
I've created a MacOS template on awx2 and have tested it on one of our macos machines. It runs successfully. This issue can now be closed
