### ISSUE TITLE
System unavailable: Jenkins master

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#1914]
System is not restarting properly. Comes up but then stops responding. Unclear if it was related in any way to the work being done for https://github.com/AdoptOpenJDK/openjdk-build/issues/2455 this morning

Final entry in the log at the time of the most recent failure was:
```
2021-02-09 10:38:21.766+0000 [id=65]	INFO	o.j.p.P.u.DropCachePeriodicWork#doRun: begin schedule clean...
2021-02-09 10:38:32.075+0000 [id=65]	INFO	o.j.p.P.u.DropCachePeriodicWork#doRun: end schedule clean...
2021-02-09 10:40:15.423+0000 [id=1255]	INFO	hudson.slaves.ChannelPinger$1#onDead: Ping failed. Terminating the channel test-macstadium-macos1015-x64-1.
java.util.concurrent.TimeoutException: Ping started at 1612866937077 hasn't completed by 1612867179291
	at hudson.remoting.PingThread.ping(PingThread.java:134)
	at hudson.remoting.PingThread.run(PingThread.java:90)
```

**Comment by sxa** [comment]
Reboot did not resolve. I'm wondering if we've hit a memory limit ...

**Comment by sxa** [comment]
Switched back from an OpenJ9 VM to HotSpot (despite it running ok for about two months) and it's managed to start up again. Reason unclear, but I'll close this unless it recurs.

**Comment by sxa** [comment]
Didn't last long. CPU was still sitting at 100% (all 8 cores) more or less constantly.

Have adjusted JVM startup options to be `-Xmx16g -Xms8g` and it's now started and feeling more responsive. CPU load still high but not critical.
