### ISSUE TITLE
AIX: needs additional support for Africa/Juba to prevent java.lang.RuntimeException

### ISSUE THREAD

**Issue by aixtools** [AdoptOpenJDK/openjdk-infrastructure#1991]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name?
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on?
- Which machine(s) does it fail on?
- Do you have a link to a Grinder re-run if the test with the failure?

Any other details:
History: https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1614275510079000?thread_ts=1614251654.056600&cid=C09NW3L2J, https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1614335374088300?thread_ts=1614251654.056600&cid=C09NW3L2J

basically - 

Just looked at console output. Reports 'unstable' due to, I expect:
02:32:26.506  STDERR:
02:32:26.506  javazic: warning: found last rules for Morocco inconsistent.
02:32:26.506  javazic: warning: found last rules for Morocco inconsistent.
02:32:26.507  javazic: warning: found last rules for Eire inconsistent.
02:32:26.507  java.lang.RuntimeException:   FAILED:  Africa/Juba

To resolve this - a further update to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/704 and https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1032

Adding support for Africa/Juba (South Africa specific)

Installation Summary
--------------------
Name                        Level           Part        Event       Result
-------------------------------------------------------------------------------
bos.loc.utf.EN_ZA           7.1.4.0         USR         APPLY       SUCCESS
bos.loc.iso.en_ZA           7.1.4.0         USR         APPLY       SUCCESS

**Comment by aixtools** [comment]
After running with these filesets installed the error changes:

2021-03-02T08:26:50-0600 Test starting: sun/util/calendar/zi/TestZoneInfo310.java
2021-03-02T08:26:53-0600 Test finished: sun/util/calendar/zi/TestZoneInfo310.java: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: FAILED: aliases don't match
2021-03-02T08:26:53-0600 Test starting: sun/util/calendar/Bug6653944.java

* Reading 'Better' it is specifically: `TEST: sun/util/calendar/zi/TestZoneInfo310.java`

**Comment by aixtools** [comment]
More specific test results: BEFORE filesets added:
```
02:32:26.505          TestZoneInfo310
02:32:26.505  STDOUT:
02:32:26.505  Compiling tz files!
02:32:26.505  testing!
02:32:26.505  OLD.getZoneInfoOld()[1]=355
02:32:26.505  OLD.getZoneInfoOld()[2]=348
02:32:26.505  OLD.getZoneInfoOld()[3]=242
02:32:26.505  OLD.getAvailableIDs()=671, total=628
02:32:26.505  OLD.getAliasTable()=424, total=229
02:32:26.505  OLD.TotalTZ()=40 (ms)
02:32:26.505  NEW.getTimeZone()[1]=10
02:32:26.505  NEW.getTimeZone()[2]=1
02:32:26.505  NEW.getTimeZone()[3]=0
02:32:26.505  NEW.getAvailableIDs()=20, total=628
02:32:26.505  NEW.getAliasTable()=34, total=229
02:32:26.505  NEW.TotalTZ()=1 (ms)
02:32:26.505  ******************************
02:32:26.505  Africa/Juba : Africa/Juba
02:32:26.505      offset=10800000,dstSavings=0,useDaylight=false,transitions=36,offsets=4,checksum=1124812718,gmtChanged=false
02:32:26.505  [NG]offset=7200000,dstSavings=0,useDaylight=false,transitions=37,offsets=4,checksum=1488933974,gmtChanged=false
02:32:26.505      offset.len=4    4
02:32:26.505          +03:00    +02:00
02:32:26.505          +02:06:28    +02:06:28
02:32:26.505          +02:00    +03:00
02:32:26.505          +01:00    +01:00
02:32:26.505      -------------
02:32:26.505      (NG) Different trans size :36, 37
02:32:26.505                    1900-01-01T00:00  [utc=-2208988800   raw=fffffdfdae01dc00, offset=7588/+02:06:28, saving=0]
02:32:26.505      (OK)          1900-01-01T00:00  [utc=-2208988800   raw=fffffdfdae01dc00, offset=7588/+02:06:28, saving=0]
02:32:26.505              -----
02:32:26.505                    1931-01-01T00:00  [utc=-1230775588   raw=fffffee1700eeb60, offset=7200/+02:00, saving=0]
02:32:26.505      (OK)          1931-01-01T00:00  [utc=-1230775588   raw=fffffee1700eeb60, offset=7200/+02:00, saving=0]
02:32:26.505              -----
02:32:26.505                    1970-05-01T00:00  [utc=10360800   raw=2698d4300, offset=10800/+03:00, saving=3600]
02:32:26.505      (OK)          1970-05-01T00:00  [utc=10360800   raw=2698d4300, offset=10800/+03:00, saving=3600]
02:32:26.505              -----
02:32:26.505                    1970-10-15T00:00  [utc=24786000   raw=5c55c5880, offset=7200/+02:00, saving=0]
02:32:26.505      (OK)          1970-10-15T00:00  [utc=24786000   raw=5c55c5880, offset=7200/+02:00, saving=0]
02:32:26.505              -----
02:32:26.505                    1971-04-30T00:00  [utc=41810400   raw=9bc181300, offset=10800/+03:00, saving=3600]
02:32:26.505      (OK)          1971-04-30T00:00  [utc=41810400   raw=9bc181300, offset=10800/+03:00, saving=3600]
02:32:26.505              -----
02:32:26.505                    1971-10-15T00:00  [utc=56322000   raw=d1d0d8480, offset=7200/+02:00, saving=0]
02:32:26.505      (OK)          1971-10-15T00:00  [utc=56322000   raw=d1d0d8480, offset=7200/+02:00, saving=0]
02:32:26.505              -----
02:32:26.505                    1972-04-30T00:00  [utc=73432800   raw=1118ef9b00, offset=10800/+03:00, saving=3600]
02:32:26.505      (OK)          1972-04-30T00:00  [utc=73432800   raw=1118ef9b00, offset=10800/+03:00, saving=3600]
02:32:26.505              -----
02:32:26.505                    1972-10-15T00:00  [utc=87944400   raw=1479e50c80, offset=7200/+02:00, saving=0]
02:32:26.505      (OK)          1972-10-15T00:00  [utc=87944400   raw=1479e50c80, offset=7200/+02:00, saving=0]
02:32:26.505              -----
02:32:26.505                    1973-04-29T00:00  [utc=104882400   raw=186b7a6b00, offset=10800/+03:00, saving=3600]
02:32:26.505      (OK)          1973-04-29T00:00  [utc=104882400   raw=186b7a6b00, offset=10800/+03:00, saving=3600]
02:32:26.505              -----
02:32:26.505                    1973-10-15T00:00  [utc=119480400   raw=1bd1963880, offset=7200/+02:00, saving=0]
02:32:26.505      (OK)          1973-10-15T00:00  [utc=119480400   raw=1bd1963880, offset=7200/+02:00, saving=0]
02:32:26.505              -----
02:32:26.505                    1974-04-28T00:00  [utc=136332000   raw=1fbe053b00, offset=10800/+03:00, saving=3600]
02:32:26.505      (OK)          1974-04-28T00:00  [utc=136332000   raw=1fbe053b00, offset=10800/+03:00, saving=3600]
02:32:26.505              -----
02:32:26.505                    1974-10-15T00:00  [utc=151016400   raw=2329476480, offset=7200/+02:00, saving=0]
02:32:26.505      (OK)          1974-10-15T00:00  [utc=151016400   raw=2329476480, offset=7200/+02:00, saving=0]
02:32:26.505              -----
02:32:26.505                    1975-04-27T00:00  [utc=167781600   raw=2710900b00, offset=10800/+03:00, saving=3600]
02:32:26.505      (OK)          1975-04-27T00:00  [utc=167781600   raw=2710900b00, offset=10800/+03:00, saving=3600]
02:32:26.505              -----
02:32:26.505                    1975-10-15T00:00  [utc=182552400   raw=2a80f89080, offset=7200/+02:00, saving=0]
02:32:26.505      (OK)          1975-10-15T00:00  [utc=182552400   raw=2a80f89080, offset=7200/+02:00, saving=0]
02:32:26.505              -----
02:32:26.506                    1976-04-25T00:00  [utc=199231200   raw=2e631adb00, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1976-04-25T00:00  [utc=199231200   raw=2e631adb00, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1976-10-15T00:00  [utc=214174800   raw=31ddd01880, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1976-10-15T00:00  [utc=214174800   raw=31ddd01880, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1977-04-24T00:00  [utc=230680800   raw=35b5a5ab00, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1977-04-24T00:00  [utc=230680800   raw=35b5a5ab00, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1977-10-15T00:00  [utc=245710800   raw=3935814480, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1977-10-15T00:00  [utc=245710800   raw=3935814480, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1978-04-30T00:00  [utc=262735200   raw=3d2c3cff00, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1978-04-30T00:00  [utc=262735200   raw=3d2c3cff00, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1978-10-15T00:00  [utc=277246800   raw=408d327080, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1978-10-15T00:00  [utc=277246800   raw=408d327080, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1979-04-29T00:00  [utc=294184800   raw=447ec7cf00, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1979-04-29T00:00  [utc=294184800   raw=447ec7cf00, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1979-10-15T00:00  [utc=308782800   raw=47e4e39c80, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1979-10-15T00:00  [utc=308782800   raw=47e4e39c80, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1980-04-27T00:00  [utc=325634400   raw=4bd1529f00, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1980-04-27T00:00  [utc=325634400   raw=4bd1529f00, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1980-10-15T00:00  [utc=340405200   raw=4f41bb2480, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1980-10-15T00:00  [utc=340405200   raw=4f41bb2480, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1981-04-26T00:00  [utc=357084000   raw=5323dd6f00, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1981-04-26T00:00  [utc=357084000   raw=5323dd6f00, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1981-10-15T00:00  [utc=371941200   raw=56996c5080, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1981-10-15T00:00  [utc=371941200   raw=56996c5080, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1982-04-25T00:00  [utc=388533600   raw=5a76683f00, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1982-04-25T00:00  [utc=388533600   raw=5a76683f00, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1982-10-15T00:00  [utc=403477200   raw=5df11d7c80, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1982-10-15T00:00  [utc=403477200   raw=5df11d7c80, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1983-04-24T00:00  [utc=419983200   raw=61c8f30f00, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1983-04-24T00:00  [utc=419983200   raw=61c8f30f00, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1983-10-15T00:00  [utc=435013200   raw=6548cea880, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1983-10-15T00:00  [utc=435013200   raw=6548cea880, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1984-04-29T00:00  [utc=452037600   raw=693f8a6300, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1984-04-29T00:00  [utc=452037600   raw=693f8a6300, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1984-10-15T00:00  [utc=466635600   raw=6ca5a63080, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1984-10-15T00:00  [utc=466635600   raw=6ca5a63080, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    1985-04-28T00:00  [utc=483487200   raw=7092153300, offset=10800/+03:00, saving=3600]
02:32:26.506      (OK)          1985-04-28T00:00  [utc=483487200   raw=7092153300, offset=10800/+03:00, saving=3600]
02:32:26.506              -----
02:32:26.506                    1985-10-15T00:00  [utc=498171600   raw=73fd575c80, offset=7200/+02:00, saving=0]
02:32:26.506      (OK)          1985-10-15T00:00  [utc=498171600   raw=73fd575c80, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506                    2000-01-15T12:00  [utc=947930400   raw=dcb50e0500, offset=10800/+03:00, saving=0]
02:32:26.506      (OK)          2000-01-15T12:00  [utc=947930400   raw=dcb50e0500, offset=10800/+03:00, saving=0]
02:32:26.506              -----
02:32:26.506                    2037-01-01T00:00  [utc=2114370000   raw=1ec4a45d480, offset=10800/+03:00, saving=0]
02:32:26.506      (NG)          2021-02-01T00:00  [utc=1612126800   raw=1775a3ec880, offset=7200/+02:00, saving=0]
02:32:26.506              -----
02:32:26.506      -------------
02:32:26.506  STDERR:
02:32:26.506  javazic: warning: found last rules for Morocco inconsistent.
02:32:26.506  javazic: warning: found last rules for Morocco inconsistent.
02:32:26.507  javazic: warning: found last rules for Eire inconsistent.
02:32:26.507  java.lang.RuntimeException:   FAILED:  Africa/Juba
02:32:26.507  	at TestZoneInfo310.main(TestZoneInfo310.java:204)
02:32:26.507  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:32:26.507  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:32:26.507  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:32:26.507  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:32:26.507  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
02:32:26.507  	at java.base/java.lang.Thread.run(Thread.java:836)
02:32:26.507  
02:32:26.507  JavaTest Message: Test threw exception: java.lang.RuntimeException
02:32:26.507  JavaTest Message: shutting down test
02:32:26.507  
02:32:26.507  
02:32:26.507  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: FAILED: Africa/Juba
02:32:26.507  --------------------------------------------------
```

After filesets added (note much shorter, and very different STDOUT); STDERR has different error.
```
00:45:16.102          TestZoneInfo310
00:45:16.102  STDOUT:
00:45:16.102  Compiling tz files!
00:45:16.102  testing!
00:45:16.102  OLD.getZoneInfoOld()[1]=574
00:45:16.102  OLD.getZoneInfoOld()[2]=514
00:45:16.102  OLD.getZoneInfoOld()[3]=341
00:45:16.102  OLD.getAvailableIDs()=836, total=628
00:45:16.102  OLD.getAliasTable()=523, total=229
00:45:16.102  OLD.TotalTZ()=58 (ms)
00:45:16.102  NEW.getTimeZone()[1]=27
00:45:16.102  NEW.getTimeZone()[2]=1
00:45:16.102  NEW.getTimeZone()[3]=1
00:45:16.102  NEW.getAvailableIDs()=18, total=628
00:45:16.102  NEW.getAliasTable()=101, total=228
00:45:16.102  NEW.TotalTZ()=1 (ms)
00:45:16.102  STDERR:
00:45:16.102  javazic: warning: found last rules for Morocco inconsistent.
00:45:16.102  javazic: warning: found last rules for Morocco inconsistent.
00:45:16.102  javazic: warning: found last rules for Eire inconsistent.
00:45:16.102  java.lang.RuntimeException:   FAILED:  aliases don't match
00:45:16.102  	at TestZoneInfo310.main(TestZoneInfo310.java:167)
00:45:16.102  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:45:16.102  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:45:16.102  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:45:16.102  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:45:16.102  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
00:45:16.102  	at java.base/java.lang.Thread.run(Thread.java:836)
00:45:16.102  
00:45:16.102  JavaTest Message: Test threw exception: java.lang.RuntimeException
00:45:16.102  JavaTest Message: shutting down test
00:45:16.102  
00:45:16.102  
00:45:16.102  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: FAILED: aliases don't match
00:45:16.102  --------------------------------------------------
```

**Comment by aixtools** [comment]
I am confused - no idea what has changed.

A) Not all osuosl AIX hosts have the new language filesets
```
root@nim.bak:[/home/root]for i in 1 2 3 4 5^Jdo^Jgrep ojdk0$i /etc/hosts^Jssh ojdk0$i.bak lslpp -L | grep ZA^Jdone
10.1.0.7        ojdk01.bak      # ojdk1.bak
  bos.loc.iso.en_ZA          7.1.4.0    C     F    Base System Locale ISO Code
  bos.loc.utf.EN_ZA          7.1.4.0    C     F    Base System Locale UTF Code
10.1.0.8        ojdk02.bak      # ojdk2.bak p8-aix2-ojdk02.osuosl.bak
10.1.0.12       ojdk03.bak
10.1.0.16       ojdk04.bak
  bos.loc.iso.en_ZA          7.2.4.0    C     F    Base System Locale ISO Code
  bos.loc.utf.EN_ZA          7.2.0.0    C     F    Base System Locale UTF Code
10.1.0.4        ojdk05.bak      # p9-aix1-ojdk05.osuosl.bak
  bos.loc.iso.en_ZA          7.1.4.0    C     F    Base System Locale ISO Code
  bos.loc.utf.EN_ZA          7.1.4.0    C     F    Base System Locale UTF Code
```
B) All these nodes are passing the `sanity.openjdk` TARGET
https://ci.adoptopenjdk.net/job/Grinder/7393/, https://ci.adoptopenjdk.net/job/Grinder/7392/, https://ci.adoptopenjdk.net/job/Grinder/7391/, https://ci.adoptopenjdk.net/job/Grinder/7387/, https://ci.adoptopenjdk.net/job/Grinder/7388/ - respectively.

* recall - failed https://ci.adoptopenjdk.net/job/Grinder/7284/ on sanity.openjdk (and other settings I do not understand)

C) Shall start a test/check with TARGET `jdk_util`

**Comment by aixtools** [comment]
OK - just ran https://ci.adoptopenjdk.net/job/Grinder/7407/ with TARGET `jdk_util` and both PASS, regardless of whether the fileset is installed. So, removing from ojdk01, ojdk04 and ojdk05 - as unneeded.
