### ISSUE TITLE
sanity.openjdk failure on test-nine-macos1015-x64-2 : java/lang/ProcessBuilder/Basic.java.Basic

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2018]
Suspecting a setup issue on this new 10.15 mac machine:
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/487/testReport/junit/java_lang_ProcessBuilder_Basic/java/Basic/
```
Testing ASCII environment values
Testing Latin1 environment values
Testing Unicode environment values
Testing directory .
Testing directory ..
Testing directory /
Testing directory /bin
0 not equal to 1
cmdp
cmdp 0: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/jre/bin/java
cmdp 1: -XX:+DisplayVMOutputToStderr
cmdp 2: -classpath
cmdp 3: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdk-tests/TKG/output_16152925343528/jdk_lang_0/work/classes/3/java/lang/ProcessBuilder:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/ProcessBuilder:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/../lib/tools.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/jvmtest/openjdk/jtreg/lib/javatest.jar:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/jvmtest/openjdk/jtreg/lib/jtreg.jar
cmdp 4: Basic$JavaChild
cmdp 5: System.getenv()
envp
envp 0: LC_ALL=C\u0000\u0000
envp 1: FO\u0000=B\u0000R
 waitFor process: delta: 42281

Passed = 8947, failed = 4
```
```
java.lang.Throwable
	at java.lang.Thread.dumpStack(Thread.java:498)
	at Basic.fail(Basic.java:2585)
	at Basic.check(Basic.java:2588)
	at Basic.realMain(Basic.java:1659)
	at Basic.main(Basic.java:2595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:823)
java.lang.Throwable
	at java.lang.Thread.dumpStack(Thread.java:498)
	at Basic.fail(Basic.java:2585)
	at Basic.check(Basic.java:2588)
	at Basic.realMain(Basic.java:1660)
	at Basic.main(Basic.java:2595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:823)
java.lang.Throwable
	at java.lang.Thread.dumpStack(Thread.java:498)
	at Basic.fail(Basic.java:2585)
	at Basic.check(Basic.java:2588)
	at Basic.realMain(Basic.java:1661)
	at Basic.main(Basic.java:2595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:823)
java.lang.Throwable
	at java.lang.Thread.dumpStack(Thread.java:498)
	at Basic.fail(Basic.java:2585)
	at Basic.fail(Basic.java:2586)
	at Basic.equal(Basic.java:2592)
	at Basic.realMain(Basic.java:1662)
	at Basic.main(Basic.java:2595)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:823)
java.lang.AssertionError: Some tests failed
	at Basic.main(Basic.java:2597)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:823)

JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.AssertionError: Some tests failed
    

REST API
Jenkins 2.263.3
```

**Comment by andrew-m-leonard** [comment]
I am fairly sure this is fixed by: https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/ac53c29ae214ce3342fe7591f369aa4e9e4a3204
