### ISSUE TITLE
build-ibmcloud-win2012r2-x64-2 fails to run process type openjdk tests

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2021]
Looks like a setup issue on build-ibmcloud-win2012r2-x64-2
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/457/

```
13:40:51  STDOUT:
13:40:51  This appears to be a Windows system.
13:40:51  This appears to be a Unicode-based OS.
13:40:51  Testing ASCII environment values
13:40:51  Testing Latin1 environment values
13:40:51  Testing directory .
13:40:51  Testing directory ..
13:40:51  Testing directory \
13:40:51  Testing directory C:
13:40:51  Testing directory c:
13:40:51  Testing directory C:\
13:40:51  Testing directory c:\
13:40:51  Testing directory \
13:40:51  Testing directory c:\windows  
13:40:51  Testing directory c:\Program Files
13:40:51  Testing directory c:\Program Files
13:40:51  Testing Unicode directory:.\ProcessBuilderDir??
13:40:51  Running case insensitve variable tests
13:40:51  cmdp
13:40:51  cmdp 0: E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\bin\java
13:40:51  cmdp 1: -XX:+DisplayVMOutputToStderr
13:40:51  cmdp 2: -classpath
13:40:51  cmdp 3: E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TKG\output_16152968778390\jdk_lang_0\work\classes\0\java\lang\ProcessBuilder\Basic_id0.d;E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\openjdk\openjdk-jdk\test\jdk\java\lang\ProcessBuilder;E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\javatest.jar;E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\jvmtest\openjdk\jtreg\lib\jtreg.jar
13:40:51  cmdp 4: Basic$JavaChild
13:40:51  cmdp 5: System.getenv()
13:40:51  envp
13:40:51  envp 0: SystemRoot=C:\Windows
13:40:51  envp 1: LC_ALL=C
13:40:51  envp 2: FO=BR
13:40:51   waitFor process: delta: 148720
13:40:51  
13:40:51  Passed = 9255, failed = 3
13:40:51  
13:40:51  STDERR:
13:40:51  >'1'< not equal to '0'
13:40:51  java.lang.Throwable
13:40:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
13:40:51  	at Basic.fail(Basic.java:2747)
13:40:51  	at Basic.fail(Basic.java:2748)
13:40:51  	at Basic.equal(Basic.java:2754)
13:40:51  	at Basic.commandOutput(Basic.java:111)
13:40:51  	at Basic.commandOutput(Basic.java:122)
13:40:51  	at Basic.javaChildOutput(Basic.java:567)
13:40:51  	at Basic.pwdInChild(Basic.java:583)
13:40:51  	at Basic.realMain(Basic.java:1745)
13:40:51  	at Basic.main(Basic.java:2757)
13:40:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:40:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:40:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:40:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:40:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:40:51  	at java.base/java.lang.Thread.run(Thread.java:836)
13:40:51  >'1'< not equal to '0'
13:40:51  java.lang.Throwable
13:40:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
13:40:51  	at Basic.fail(Basic.java:2747)
13:40:51  	at Basic.fail(Basic.java:2748)
13:40:51  	at Basic.equal(Basic.java:2754)
13:40:51  	at Basic.commandOutput(Basic.java:112)
13:40:51  	at Basic.commandOutput(Basic.java:122)
13:40:51  	at Basic.javaChildOutput(Basic.java:567)
13:40:51  	at Basic.pwdInChild(Basic.java:583)
13:40:51  	at Basic.realMain(Basic.java:1745)
13:40:51  	at Basic.main(Basic.java:2757)
13:40:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:40:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:40:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:40:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:40:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:40:51  	at java.base/java.lang.Thread.run(Thread.java:836)
13:40:51  >''< not equal to 'E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdk-tests\TKG\output_16152968778390\jdk_lang_0\work\scratch\3'
13:40:51  java.lang.Throwable
13:40:51  	at java.base/java.lang.Thread.dumpStack(Thread.java:511)
13:40:51  	at Basic.fail(Basic.java:2747)
13:40:51  	at Basic.fail(Basic.java:2748)
13:40:51  	at Basic.equal(Basic.java:2754)
13:40:51  	at Basic.realMain(Basic.java:1745)
13:40:51  	at Basic.main(Basic.java:2757)
13:40:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:40:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:40:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:40:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:40:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:40:51  	at java.base/java.lang.Thread.run(Thread.java:836)
13:40:51  java.lang.AssertionError: Some tests failed
13:40:51  	at Basic.main(Basic.java:2759)
13:40:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:40:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:40:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:40:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:40:51  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:40:51  	at java.base/java.lang.Thread.run(Thread.java:836)
13:40:51  
13:40:51  JavaTest Message: Test threw exception: java.lang.AssertionError: Some tests failed
13:40:51  JavaTest Message: shutting down test
13:40:51  
13:40:51  STATUS:Failed.`main' threw exception: java.lang.AssertionError: Some tests failed
```
```
13:41:53  [TestNG] Running:
13:41:53    java/lang/ProcessHandle/OnExitTest.java
13:41:53  
13:41:53    Child Output: args: 5180 [stdin]
13:41:53    Child Output: 5180:1 stdin start
13:41:53    Child Output: 5180:2 pid 5180
13:41:53    Child Output: args: 4944 [stdin]
13:41:53    Child Output: 4944:1 stdin start
13:41:53    Child Output: 4944:2 pid 4944
13:41:53   a.isAlive: false, a.info: [user: Optional[BLD-IBM-W2012X2\jenkins], cmd: E:\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows\openjdkbinary\j2sdk-image\bin\java.exe, startTime: Optional[2021-03-09T13:40:21.747Z], totalTime: Optional[PT0.65625S]], @PT0.0159963S
13:41:53   A.onExit().A info: [user: Optional[BLD-IBM-W2012X2\jenkins], startTime: Optional[2021-03-09T13:40:21.747Z], totalTime: Optional[PT0.671875S]], now: 2021-03-09T13:40:27.771672500Z
13:41:53   A.toHandle().onExit().A info: [user: Optional[BLD-IBM-W2012X2\jenkins], startTime: Optional[2021-03-09T13:40:21.747Z], totalTime: Optional[PT0.671875S]], now: 2021-03-09T13:40:27.776672600Z
13:41:53    Child Output: 4944:3 waitpid false
13:41:53  test OnExitTest.peerOnExitTest(): success
13:41:53  args: 17816 [exit, 0]
13:41:53  17816:1 exit 0
13:41:53   javaChild done: Process[pid=17816, exitValue=0], exitStatus: 0
13:41:53  args: 8284 [exit, 1]
13:41:53  8284:1 exit 1
13:41:53   javaChild done: Process[pid=8284, exitValue=1], exitStatus: 1
13:41:53  args: 18144 [exit, 10]
13:41:53  18144:1 exit 10
13:41:53   javaChild done: Process[pid=18144, exitValue=10], exitStatus: 10
13:41:53  test OnExitTest.test1(): success
13:41:53   spawned: 15032
13:41:53   subprocess count: 0, waiting for 9
13:41:53   subprocess count: 0, waiting for 9
13:41:53   subprocess count: 0, waiting for 9
...
13:41:53   subprocess count: 7, waiting for 9
13:41:53   subprocess count: 7, waiting for 9
13:41:53  WARNING: not all children have been started. Can't complete test.
13:41:53           You can try to increase the timeout or
```
```
13:41:53  test OnExitTest.test2(): failure
13:41:53  java.lang.AssertionError: spawned process should have been in children expected [true] but found [false]
13:41:53  	at org.testng.Assert.fail(Assert.java:94)
13:41:53  	at org.testng.Assert.failNotEquals(Assert.java:496)
13:41:53  	at org.testng.Assert.assertTrue(Assert.java:42)
13:41:53  	at OnExitTest.lambda$test2$4(OnExitTest.java:154)
13:41:53  	at OnExitTest$$Lambda$74/0x0000000021c66c30.accept(Unknown Source)
13:41:53  	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
13:41:53  	at OnExitTest.test2(OnExitTest.java:153)
13:41:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:41:53  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl
```
```

```
5 Process type tests fail, but they work fine on the Azure node : https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows/456/

**Comment by sxa** [comment]
@andrew-m-leonard Have you done any investigation into this? It's not too easy to start a diagnosis based on `13:40:51  >'1'< not equal to '0'` - do you have an idea of which operation might be failing? Since this isn't a new machine has it passed ok in the machine previously?

**Comment by sxa** [comment]
Also is this the same failure we're seeing on AIX https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2024? It looks like it might be in the same area

**Comment by andrew-m-leonard** [comment]
@sxa not yet.... working my way through all the issues

**Comment by andrew-m-leonard** [comment]
Grinder: https://ci.adoptopenjdk.net/job/Grinder/7665/console

**Comment by andrew-m-leonard** [comment]
Passed on this machine on 2ndMar : https://trss.adoptopenjdk.net/deepHistory?testId=6047d2c45730424dbca1e87a

**Comment by andrew-m-leonard** [comment]
Grinder hotspot: https://ci.adoptopenjdk.net/job/Grinder/7670/

**Comment by andrew-m-leonard** [comment]
Grinder x20 openj9 jdk11 v0.26.0-release: https://ci.adoptopenjdk.net/job/Grinder/7673/

**Comment by sxa** [comment]
All of the above seem to be green - this is looking like a one-off glitch and not a machine-specific oddity so I'm going to close and add it to https://github.com/AdoptOpenJDK/openjdk-build/issues/1450 (Re-open if you disagree) - thanks for running the checks 👍🏻
