### ISSUE TITLE
jdk-16 AIX: java/lang/ProcessBuilder/Basic.java#id0 machine specific issue maybe?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2024]
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/36/consoleFull
node: test-osuosl-aix72-ppc64-1
openj9:
```
02:25:29  openjdk version "16" 2021-03-16
02:25:29  OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
02:25:29  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.26.0-m1, JRE 16 AIX ppc64-64-Bit Compressed References 20210309_68 (JIT enabled, AOT enabled)
02:25:29  OpenJ9   - b227feba2
02:25:29  OMR      - 4665e2f72
02:25:29  JCL      - 7d78cfa0dc2 based on jdk-16+36)
```
```
03:02:27  This appears to be a Unix system.
03:02:27  Testing ASCII environment values
03:02:27  Testing Latin1 environment values
03:02:27  Testing directory .
03:02:27  Testing directory ..
03:02:27  Testing directory /
03:02:27  Testing directory /bin
03:02:27  cmdp
03:02:27  cmdp 0: /home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/bin/java
03:02:27  cmdp 1: -XX:+DisplayVMOutputToStderr
03:02:27  cmdp 2: -classpath
03:02:27  cmdp 3: /home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_16153440635501/jdk_lang_0/work/classes/java/lang/ProcessBuilder/Basic_id0.d:/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/lang/ProcessBuilder:/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/openjdk-tests/TKG/output_16153440635501/jdk_lang_0/work/classes/test/lib:/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/openjdk-tests/openjdk/openjdk-jdk/test/lib:/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk16_j9_sanity.openjdk_ppc64_aix/jvmtest/openjdk/jtreg/lib/jtreg.jar
03:02:27  cmdp 4: Basic$JavaChild
03:02:27  cmdp 5: System.getenv()
03:02:27  envp
03:02:27  envp 0: LC_ALL=C
03:02:27  envp 1: FO=BR
03:02:27   waitFor process: delta: 92786
03:02:27  
03:02:27  Passed = 9127, failed = 4
03:02:27  
03:02:27  STDERR:
03:02:27  java.lang.Throwable
03:02:27  	at java.base/java.lang.Thread.dumpStack(Thread.java:526)
03:02:27  	at Basic.fail(Basic.java:2785)
03:02:27  	at Basic.check(Basic.java:2788)
03:02:27  	at Basic.realMain(Basic.java:1835)
03:02:27  	at Basic.main(Basic.java:2795)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
03:02:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:02:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
03:02:27  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:02:27  	at java.base/java.lang.Thread.run(Thread.java:853)
03:02:27  java.lang.Throwable
03:02:27  	at java.base/java.lang.Thread.dumpStack(Thread.java:526)
03:02:27  	at Basic.fail(Basic.java:2785)
03:02:27  	at Basic.check(Basic.java:2788)
03:02:27  	at Basic.realMain(Basic.java:1836)
03:02:27  	at Basic.main(Basic.java:2795)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
03:02:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:02:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
03:02:27  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:02:27  	at java.base/java.lang.Thread.run(Thread.java:853)
03:02:27  java.lang.Throwable
03:02:27  	at java.base/java.lang.Thread.dumpStack(Thread.java:526)
03:02:27  	at Basic.fail(Basic.java:2785)
03:02:27  	at Basic.check(Basic.java:2788)
03:02:27  	at Basic.realMain(Basic.java:1837)
03:02:27  	at Basic.main(Basic.java:2795)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
03:02:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:02:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
03:02:27  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:02:27  	at java.base/java.lang.Thread.run(Thread.java:853)
03:02:27  >'0'< not equal to '1'
03:02:27  java.lang.Throwable
03:02:27  	at java.base/java.lang.Thread.dumpStack(Thread.java:526)
03:02:27  	at Basic.fail(Basic.java:2785)
03:02:27  	at Basic.fail(Basic.java:2786)
03:02:27  	at Basic.equal(Basic.java:2792)
03:02:27  	at Basic.realMain(Basic.java:1838)
03:02:27  	at Basic.main(Basic.java:2795)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
03:02:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:02:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
03:02:27  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:02:27  	at java.base/java.lang.Thread.run(Thread.java:853)
03:02:27  java.lang.AssertionError: Some tests failed
03:02:27  	at Basic.main(Basic.java:2797)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:02:27  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
03:02:27  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:02:27  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
03:02:27  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:02:27  	at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by sxa** [comment]
Is this a new failure? Can we run some grinders on a few machines, and with the last GA to see

**Comment by sxa** [comment]
Running 20 iterations of the `jdk_lang` suite on the machine at https://ci.adoptopenjdk.net/job/Grinder/7695

**Comment by andrew-m-leonard** [comment]
10x Grinder here: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7699/console

**Comment by andrew-m-leonard** [comment]
I'm going to add some debug to basic.java

**Comment by andrew-m-leonard** [comment]
My debug shows the problem is because of this section that tries to force a OOM, but sometimes on these AIX boxes does not, probably because it has a huge amount of memory! https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/3ca051dd4467c4b024565e3c71d00b854c1e75d7/test/jdk/java/lang/ProcessBuilder/Basic.java#L370
Might explain why we saw it on a Windows box as well, and also it uses random() to choose what array type to use!

**Comment by andrew-m-leonard** [comment]
the code is actually exercising a specific Hotspot bug using the array's https://bugs.openjdk.java.net/browse/JDK-6850957  
I'm going to raise the issue with openj9 as the testcase maybe not relevant so they might want to patch, as they already patch this testcase.

**Comment by andrew-m-leonard** [comment]
Raised: https://github.com/eclipse/openj9/issues/12216

**Comment by Haroon-Khel** [comment]
iirc this same issue affected aix a while back https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1644#issuecomment-737283413

The solution there was to exclude those tests on aix

**Comment by andrew-m-leonard** [comment]
openj9 have merged a fix for this
