### ISSUE TITLE
Systems unavailable: test-ibm-aix71-ppc64-1 and test-ibm-aix71-ppc64-2 both down

### ISSUE THREAD

**Issue by aixtools** [AdoptOpenJDK/openjdk-infrastructure#2115]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-aix-ppc64-openj9/ was 'suspended' because both these systems (with label aix715) were down. The queue became processable by adding some missing tags to test-osuosl-aix71-ppc64-1

- Please describe the issue:
* At least one of the IBM hosted nodes was officially offline from jenkins for testing - however, for nearly 48 hours both systems are not responding to ping or attempts to connect with port 22 (to test availability).
* Jenkins is trying to reestablish contact - but fails:
```
SSH Connection failed with IOException: "connect timed out", retrying in 15 seconds. There are 1 more retries left.

connect timed out

ERROR: Connection is not established!
java.lang.IllegalStateException: Connection is not established!
	at com.trilead.ssh2.Connection.getRemainingAuthMethods(Connection.java:988)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.getRemainingAuthMethods(TrileadSSHPublicKeyAuthenticator.java:88)
	at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPublicKeyAuthenticator.canAuthenticate(TrileadSSHPublicKeyAuthenticator.java:80)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.newInstance(SSHAuthenticator.java:218)
	at com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.newInstance(SSHAuthenticator.java:171)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:865)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:436)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[04/09/21 17:12:48] Launch failed - cleaning up connection
[04/09/21 17:12:48] [SSH] Connection closed.
```

**Comment by sxa** [comment]
Machines have been accidentally decommissioned as I understand it. I have a discussion on Monday about recovering them. This will impact OpenJ9's AIX builds

**Comment by sxa** [comment]
Mitigated OpenJ9 build issues for now by adding the appropriate labels to https://ci.adoptopenjdk.net/computer/test-osuosl-aix71-ppc64-1/ to allow builds on it. Meeting with the IBM to take place later today to discuss re-provisioning

**Comment by sxa** [comment]
Machines have been rebuilt at `7100-05-06-2016` and are now ready to have the playbooks applied

**Comment by sxa** [comment]
@aixtools has setup one of the "spare" LPARs used for testing playbook deployments as a stop-gap for getting back to normal. @Haroon-Khel is in the process of rebuilding the two IBM AIX boxes.

**Comment by Haroon-Khel** [comment]
Update: the AIX playbook ran on both machines. `git` and `db` werent able to be installed/updated via yum (for both machines). As a result, @aixtools felt has installed git 2.24.1 on both, and ive excluded `db` from receiving yum updates (until we can figure out why yum is having trouble updating it). 

Error log when updating `db`
```
Running Transaction
Error in PREIN scriptlet in rpm package 1:db-5.3.28-1.ppc
/var/tmp/rpm-tmp.8mGqaa[4]: 4^J4: 0403-057 Syntax error
error: %prein(db-1:5.3.28-1.ppc) scriptlet failed, exit status 1
db-4.8.24-3.ppc was supposed to be removed but is not!

Failed:
  db.ppc 0:4.8.24-3
```

Error log when installing `git` via yum

```
bash-5.0# yum install git
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package git.ppc 0:2.20.4-1 will be installed
--> Processing Dependency: rsync for package: git-2.20.4-1.ppc
--> Processing Dependency: /opt/freeware/bin/perl for package: git-2.20.4-1.ppc
--> Processing Dependency: less for package: git-2.20.4-1.ppc
--> Running transaction check
---> Package less.ppc 0:557-1 will be installed
---> Package perl.ppc 1:5.30.3-2 will be installed
--> Processing Dependency: db >= 5.3.28 for package: 1:perl-5.30.3-2.ppc
--> Processing Dependency: libdb.a(libdb-5.3.so) for package: 1:perl-5.30.3-2.ppc
---> Package rsync.ppc 0:3.2.3-1 will be installed
--> Processing Dependency: lz4 >= 1.9.2 for package: rsync-3.2.3-1.ppc
--> Processing Dependency: liblz4.a(liblz4.so.1) for package: rsync-3.2.3-1.ppc
--> Running transaction check
---> Package lz4.ppc 0:1.9.2-1 will be installed
---> Package perl.ppc 1:5.30.3-2 will be installed
--> Processing Dependency: db >= 5.3.28 for package: 1:perl-5.30.3-2.ppc
--> Processing Dependency: libdb.a(libdb-5.3.so) for package: 1:perl-5.30.3-2.ppc
--> Finished Dependency Resolution
Error: Package: 1:perl-5.30.3-2.ppc (AIX_Toolbox)
           Requires: db >= 5.3.28
           Installed: db-4.8.24-3.ppc (installed)
               db = 4.8.24-3
Error: Package: 1:perl-5.30.3-2.ppc (AIX_Toolbox)
           Requires: libdb.a(libdb-5.3.so)
 You could try using --skip-broken to work around the problem
** Found 2 pre-existing rpmdb problem(s), 'yum check' output follows:
krb5-libs-1.18.3-1.ppc has missing requires of db >= ('0', '5.3.28', None)
krb5-libs-1.18.3-1.ppc has missing requires of libdb5.a(libdb-5.3.so)
```

**Comment by Haroon-Khel** [comment]
Machines are online in jenkins. Ive hit a certificates problem when running builds
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/906/console
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/959/console

```
15:35:53  No credentials specified
15:35:53  Cloning the remote Git repository
15:35:53  ERROR: Error cloning remote repo 'origin'
15:35:53  hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/adoptium/ci-jenkins-pipelines.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
15:35:53  stdout: 
15:35:53  stderr: fatal: unable to access 'https://github.com/adoptium/ci-jenkins-pipelines.git/': error setting certificate verify locations:
15:35:53    CAfile: /var/ssl/cacert.pem
15:35:53    CApath: none
15:35:53  
15:35:53  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2608)
15:35:53  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2048)
```

The machines both have `ca-certificates` installed

```
bash-5.0# yum info ca-certificates
Installed Packages
Name        : ca-certificates
Arch        : ppc
Version     : 2020.06.01
Release     : 1
Size        : 2.0 M
Repo        : installed
From repo   : AIX_Toolbox
Summary     : The Mozilla CA root certificate bundle
License     : Public Domain
Description : This package contains the set of CA certificates chosen by the
            : Mozilla Foundation for use with the Internet PKI.
```

**Comment by aixtools** [comment]
I'll fix that.
