### ISSUE TITLE
test-osuosl-aix71-ppc64-1 Test_openjdk16_j9_extended.openjdk_ppc64_aix test failures

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-infrastructure#2141]
Numerous test failure on node test-osuosl-aix71-ppc64-1 which don't occur on other nodes:
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_ppc64_aix/19/
eg:
```
10:19:34  FINE [Apr 18, 9:19:24.743800000] sun.net.httpserver.ServerImpl createContext: context created: /
10:19:34  java.lang.RuntimeException: Unexpected exception: java.net.ConnectException: Connection reset by peer
10:19:34  	at DigestEchoClient.testBasic(DigestEchoClient.java:455)
10:19:34  	at DigestEchoClient.main(DigestEchoClient.java:281)
10:19:34  	at DigestEchoClientSSL.main(DigestEchoClientSSL.java:57)
10:19:34  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:19:34  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
10:19:34  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:19:34  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
10:19:34  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
10:19:34  	at java.base/java.lang.Thread.run(Thread.java:853)
10:19:34  Caused by: java.net.ConnectException: Connection reset by peer
```
```
10:22:10  Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
10:22:10  	at java.net.http/jdk.internal.net.http.common.SSLTube.checkForHandshake(SSLTube.java:595)
10:22:10  	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onComplete(SSLTube.java:536)
10:22:10  	... 17 more
```
```
12:51:47  Caused by: java.io.EOFException: EOF reached while reading
12:51:47  	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:596)
```
```
18:03:42  java.lang.Error: Probable fatal error: No physical fonts found.
18:03:42  	at java.desktop/sun.font.SunFontManager.lambda$getDefaultPhysicalFont$0(SunFontManager.java:1050)
18:03:42  	at java.desktop/sun.font.SunFontManager$$Lambda$23/0x0000000000000000.get(Unknown Source)
18:03:42  	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
18:03:42  	at java.desktop/sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1050)
18:03:42  	at java.desktop/sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:291)
18:03:42  	at java.desktop/sun.font.CompositeFont.getSlotFont(CompositeFont.java:376)
18:03:42  	at java.desktop/sun.font.CompositeGlyphMapper.initMapper(CompositeGlyphMapper.java:81)
18:03:42  	at java.desktop/sun.font.CompositeGlyphMapper.<init>(CompositeGlyphMapper.java:62)
18:03:42  	at java.desktop/sun.font.CompositeFont.getMapper(CompositeFont.java:433)
18:03:42  	at java.desktop/sun.font.GlyphList.mapChars(GlyphList.java:249)
18:03:42  	at java.desktop/sun.font.GlyphList.setFromString(GlyphList.java:224)
18:03:42  	at java.desktop/sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:70)
18:03:42  	at java.desktop/sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2936)
18:03:42  	at ImageWriterCompressionTest.main(ImageWriterCompressionTest.java:82)
18:03:42  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:03:42  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
18:03:42  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:03:42  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
18:03:42  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
18:03:42  	at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by Haroon-Khel** [comment]
Alot of those test failures are due to `java.net.ConnectException: Connection reset by peer`. 
Examples
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_ppc64_aix/19/testReport/java_net_httpclient_ByteArrayPublishers/java/ByteArrayPublishers_2/
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_ppc64_aix/19/testReport/java_net_Socket_Streams/java/Streams/
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.openjdk_ppc64_aix/19/testReport/java_net_httpclient_DigestEchoClientSSL/java/DigestEchoClientSSL/

**Comment by aixtools** [comment]
* The java.net.ConnectionException errors are fixed. (Perhaps this can be closed)
* Might be related to #2059 - that is extended.functional failure, but on AIX 7.2.
* Currently re-running the extended.functional (jdk16/j9/master/nightly/extended.functional) - looking for current status.

**Comment by aixtools** [comment]
Closing this issue - as the `java.net.ConnectionException` has been resolved. The remaining issue is open at #2059
