### ISSUE TITLE
test-osuosl-aix71-ppc64-1: tests which require X server fail

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#2177]
Failing job link: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_ppc64_aix/28/consoleFull

Tests which require an X server are failed on `test-osuosl-aix71-ppc64-1` with the exception
```
21:26:52  STDERR:
21:26:52  _X11TransTRANS(ibmSHMConnect) () can't connect: errno = 78
21:26:52  java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
21:26:52  	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
21:26:52  	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
21:26:52  	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
21:26:52  	at java.security.AccessController.doPrivileged(AccessController.java:682)
21:26:52  	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
21:26:52  	at java.lang.Class.forNameImpl(Native Method)
21:26:52  	at java.lang.Class.forName(Class.java:332)
21:26:52  	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
21:26:52  	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
21:26:52  	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
21:26:52  	at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
21:26:52  	at BmpDefaultImageMetadataTest.<init>(BmpDefaultImageMetadataTest.java:53)
21:26:52  	at BmpDefaultImageMetadataTest.main(BmpDefaultImageMetadataTest.java:149)
21:26:52  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:26:52  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:26:52  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:26:52  	at java.lang.reflect.Method.invoke(Method.java:498)
21:26:52  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
21:26:52  	at java.lang.Thread.run(Thread.java:821)
21:26:52  
21:26:52  JavaTest Message: Test threw exception: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
21:26:52  JavaTest Message: shutting down test
```

The X server startup at the start of the job does not appear to be successful:
```
[Pipeline] sh
17:11:01  + nohup /usr/bin/X11/X -force -vfb -x abx -x dbe -x GLX :0
17:11:01  
17:11:01  Fatal server error:
17:11:01  Cannot establish any listening sockets - Make sure an X server isn't already running
[Pipeline] echo
17:11:01  env.DISPLAY is :0
```

**Comment by sxa** [comment]
Can't see anything obvious that would cause this - can you re-run and see if it recurs? If so I'll have a closer look.

**Comment by lumpfish** [comment]
Tests now running OK: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/625/console
Another mystery.

**Comment by sxa** [comment]
Closing for now but we can re-open if it recurs. Hopefully a one-off glitch. Tagging https://github.com/adoptium/temurin-build/issues/1450
