### ISSUE TITLE
SocketException on ci.adoptopenjdk.net

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-infrastructure#345]
Jenkins is currently showing this exception. We have attempted to restart jenkins but that has not yet cleared it.

```
java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
    at hudson.TcpSlaveAgentListener.<init>(TcpSlaveAgentListener.java:100)
    at jenkins.model.Jenkins.launchTcpSlaveAgentListener(Jenkins.java:1232)
    at jenkins.model.Jenkins.<init>(Jenkins.java:925)
    at hudson.model.Hudson.<init>(Hudson.java:85)
    at hudson.model.Hudson.<init>(Hudson.java:81)
    at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
    at hudson.WebAppMain$3.run(WebAppMain.java:250)
```

**Comment by sxa555** [comment]
`config.xml` had `<slaveAgentPort>21</slaveAgentPort>` which appears to have been causing a problem (potentially only when jenkins was upgraded from `2.107.1` to `2.107.2` earlier today as the slaveAgentPort has been set to 21 since 23rd October 2017. Prior to that it was 49187. We've switched it to zero which is consistent with the JCK jenkins instance which upgraded without problems.
