### ISSUE TITLE
OOM received consistently on test-marist-ubuntu1604-s390x-1 while compiling system tests 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-infrastructure#485]
System test compilation is resulting in a OutOfMemoryError on `test-marist-ubuntu1604-s390x-1` consistently for the last 4 builds that was scheduled on it. 

https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/

Exception: 
```
07:54:49     [javac] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
07:54:49     [javac] 	at java.util.HashMap.newNode(HashMap.java:1747)
07:54:49     [javac] 	at java.util.HashMap.putVal(HashMap.java:631)
07:54:49     [javac] 	at java.util.HashMap.put(HashMap.java:612)
07:54:49     [javac] 	at java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:204)
07:54:49     [javac] 	at java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:130)
07:54:49     [javac] 	at java.util.ResourceBundle.getObject(ResourceBundle.java:441)
07:54:49     [javac] 	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
07:54:49     [javac] 	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:190)
07:54:49     [javac] 	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:141)
07:54:49     [javac] 	at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:135)
07:54:49     [javac] 	at com.sun.tools.javac.util.Log.localize(Log.java:684)
07:54:49     [javac] 	at com.sun.tools.javac.util.Log.printLines(Log.java:497)
07:54:49     [javac] 	at com.sun.tools.javac.main.Main.resourceMessage(Main.java:610)
07:54:49     [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:543)
07:54:49     [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:381)
07:54:49     [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:370)
07:54:49     [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:361)
07:54:49     [javac] 	at com.sun.tools.javac.Main.compile(Main.java:56)
07:54:49     [javac] 	at com.sun.tools.javac.Main.main(Main.java:42)
```
https://ci.adoptopenjdk.net/view/Test_system/job/openjdk8_hs_systemtest_s390x_linux/66/console

**Comment by Mesbah-Alam** [comment]
@sxa555 .. FYI..

Is there a space issue on `test-marist-ubuntu1604-s390x-1` ?

**Comment by sxa555** [comment]
I've had some issues connecting to that machine recently (https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/455) but it looks like jenkins is reporting that it's rather lacking in swap space so if I can get onto it I'll try and increase it. I suspect it hasn't got any swap defined at the moment.

**Comment by sxa555** [comment]
As expected, machine was set up with a tiny amount of swap space. Now increased. Please reopen if this recurs.
