### ISSUE TITLE
Multicast Networking Non-Functional On zLinux Machines

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-infrastructure#699]
I have confirmed using the example multicast client and server code at https://examples.javacodegeeks.com/core-java/net/multicastsocket-net/java-net-multicastsocket-example that a fresh and unmodified zLinux machine provisioned through the Fyre service works.

**Comment by sxa555** [comment]
The network interfaces are definitely enabled for multicast so not clear why this is failing

**Comment by adamfarley** [comment]
Could this be the issue referred to in https://github.com/eclipse/openj9/issues/6669?

**Comment by andrew-m-leonard** [comment]
@sxa From my investigation I am coming to the same conclusion as Ben on this.... thse Adopt zLinux machine don't support multicast correctly

**Comment by adam-thorpe** [comment]
I believe these two tests are also linked to this issue:
- java/net/MulticastSocket/PromiscuousIPv6.java
- java/nio/channels/DatagramChannel/PromiscuousIPv6.java

**Comment by smlambert** [comment]
those tests also fail at OpenJ9

java/net/MulticastSocket/Promiscuous.java: 
https://ci.eclipse.org/openj9/view/Test/job/Grinder/547/

java/nio/channels/DatagramChannel/Promiscuous.java: 
https://ci.eclipse.org/openj9/view/Test/job/Grinder/548/

**Comment by sxa555** [comment]
@Haroon-Khel  I've put your key on one of the new Marist machines that I've got access to - `linux1@148.100.86.102`. Can you check if the problems exist on there as they are different infrastructure that we're going to migrate too soon (By soon I mean end of month!)

**Comment by sxa555** [comment]
FYI The node.js team modify the `iptables` setup on their Marist zLinux machines in relation to multicast - it's possible the same would work for us: See https://github.com/nodejs/build/blob/master/ansible/roles/jenkins-worker/tasks/main.yml

**Comment by Haroon-Khel** [comment]
@sxa555 I will begin running the associated tests on the machine. Ill post below the results

**Comment by Haroon-Khel** [comment]
@sxa555 Unfortunately, the same tests also fail on the new Marist machine. 

- java/net/MulticastSocket/Promiscuous.java
```
----------messages:(4/122)----------
command: main Promiscuous
reason: User specified action: run main Promiscuous 
Mode: othervm
elapsed time (seconds): 5.17
----------configuration:(0/0)----------
----------System.out:(4/128)----------
Using port: 58745
mc1 joined the MC group: /224.7.8.9
mc2 joined the MC group: /225.4.5.6
Sending datagram to: /224.7.8.9/58745
----------System.err:(15/893)----------
java.lang.RuntimeException: Expected message not received, Receive timed out
        at Promiscuous.receive(Promiscuous.java:62)
        at Promiscuous.test(Promiscuous.java:94)
        at Promiscuous.main(Promiscuous.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:819)

```

- java/net/MulticastSocket/SetLoopbackMode.java
```
----------messages:(4/143)----------
command: main SetLoopbackMode
reason: Assumed action based on file name: run main SetLoopbackMode 
Mode: othervm
elapsed time (seconds): 2.107
----------configuration:(0/0)----------
----------System.out:(15/260)----------

Test will use multicast group: /ff01:0:0:0:0:0:0:1

******************

Loopback mode is disabled.
Packet not received - correct.

******************

Loopback mode is enabled.
Packet not received (packet excepted as loopback is enabled)

******************

----------System.err:(13/703)----------
java.lang.RuntimeException: Test failed
        at SetLoopbackMode.main(SetLoopbackMode.java:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:819)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Test failed
```

- java/net/MulticastSocket/Test.java
```
Test 4: /ff0e:0:0:0:0:0:0:a
Join: /ff0e:0:0:0:0:0:0:a
Send packet to: /ff0e:0:0:0:0:0:0:a
Failed: No packet received within timeout!!!
Send packet to: /ff0e:0:0:0:0:0:0:a
Failed: No packet received within timeout!!!
Leave: /ff0e:0:0:0:0:0:0:a
No packet received within timeout! - Good.
Join: /ff0e:0:0:0:0:0:0:a
Send packet to: /ff0e:0:0:0:0:0:0:a
Failed: No packet received within timeout!!!
Send packet to: /ff0e:0:0:0:0:0:0:a
Failed: No packet received within timeout!!!
Leave: /ff0e:0:0:0:0:0:0:a
No packet received within timeout! - Good.
Test failed!!
**********************
4 test(s) executed. 4 test(s) failed.
----------System.err:(13/741)----------
java.lang.Exception: Test failed - see log file for details
        at Test.main(Test.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:819)

JavaTest Message: Test threw exception: java.lang.Exception: Test failed - see log file for details
JavaTest Message: shutting down test
```

- java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java
```
Test DatagramChannel to INET socket
join 225.4.5.6 @ enccw0.0.1000
Send message from 148.100.86.102 -> group 225.4.5.6 (id=0x8937bd83)
Waiting to receive message
----------System.err:(15/930)----------
java.lang.RuntimeException: Expected message not recieved
        at MulticastSendReceiveTests.receiveDatagram(MulticastSendReceiveTests.java:100)
        at MulticastSendReceiveTests.test(MulticastSendReceiveTests.java:172)
        at MulticastSendReceiveTests.main(MulticastSendReceiveTests.java:238)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:819)
```

- java/nio/channels/DatagramChannel/Promiscuous.java
```
Test family=INET
dc1 joining [225.4.5.6]:45427 @ enccw0.0.1000
dc2 joining [225.4.6.6]:45427 @ enccw0.0.1000
Send message -> group 225.4.5.6 (id=0x1363c6e5)
Checking if received by dc1
Waiting to receive message
----------System.err:(15/845)----------
java.lang.RuntimeException: Expected message not recieved
        at Promiscuous.receiveDatagram(Promiscuous.java:99)
        at Promiscuous.test(Promiscuous.java:168)
        at Promiscuous.main(Promiscuous.java:207)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:819)
```

**Comment by Haroon-Khel** [comment]
The above were only for JDK8. The two tests for JDK 11, test/jdk/java/net/MulticastSocket/Promiscuous.java and test/jdk/java/nio/channels/DatagramChannel/Promiscuous.java, also fail with similar output

**Comment by sxa555** [comment]
@Haroon-Khel Can you see if the multicast iptables rule from the link to node's playbooks rule gets around the problem?

**Comment by Haroon-Khel** [comment]
@sxa555 A solution inspired by that playbook has helped. After running `firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 0 -m udp -p udp -m pkttype --pkt-type multicast -j ACCEPT` followed by `firewall-cmd --reload` has resulted in the following tests to pass:

jdk/test/java/net/MulticastSocket/Promiscuous.java and jdk/test/java/nio/channels/DatagramChannel/Promiscuous.java

on both JDK8 and 11

**Comment by Haroon-Khel** [comment]
I have just noticed, the only passing tests now are the ones that involve ipv4 multicast, while those of ipv6 continue to fail

**Comment by adam-thorpe** [comment]
@Haroon-Khel any update on this? Just to update the issue, the ipv4 tests still seem to fail on `test-marist-sles12-s390x-1` and `test-marist-ubuntu1604-s390x-1​-z13`

**Comment by Haroon-Khel** [comment]
@adam-thorpe The failing ipv4 tests on the sles machine are expected; ipv6 passes, while ipv4 fails on this machine. 
I'm almost sure that `test-marist-ubuntu1604-s390x-1​-z13` was replaced with `test-marist-ubuntu1604-s390x-1​`

**Comment by sxa555** [comment]
Marked `-z13` offline. Must have missed it previously.

**Comment by sxa** [comment]
@Haroon-Khel Can you verify whether this problem still exists on the new machines we got in December please?

**Comment by Haroon-Khel** [comment]
This problem persists on the following marist machines:
`build-marist-rhel77-s390x-1`
`build-marist-rhel77-s390x-2`
`test-marist-sles12-s390x-1`
The two RHEL machines fail on ipv6 multicast tests, while the SLES machine fails the ipv4 multicast tests. Ill inform our contact to see whether there has been an update to our case from our emails in January

**Comment by sxa** [comment]
JDK14 xLinux installer glitched last night - conncetion issue:
```

> Task :rpm:uploadRedHatRpmPackage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rpm:uploadRedHatRpmPackage'.
> org.apache.http.conn.HttpHostConnectException: Connect to adoptopenjdk.jfrog.io:443 [adoptopenjdk.jfrog.io/35.231.52.82] failed: Connection refused (Connection refused)
```

**Comment by adamfarley** [comment]
Running some grinders to see if this error is still occurring:

build-marist-rhel77-s390x-1 - Machine doesn't appear to exist, though there is a "1x". Same machine?
build-marist-rhel77-s390x-2 - [OpenJ9 JDK8 Promiscuous.java x5 grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/764/console) - Passed
test-marist-sles12-s390x-1 - [OpenJ9 JDK11 MulticastSocket/Test.java x5 grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/764/console) - Fails due to:
```
Unable to find remote helper for 'https'
```
Could be connected to [this issue](https://github.com/adoptium/infrastructure/issues/1655). @sxa - What do you think?

**Comment by sxa** [comment]
To summarise earlier call ... 1X is a renamed version of 1 to resolve an issue with the Jenkins connection. It is likely it can be renamed back but it is the same machine.

Ignore the sles failure for the purposes of this. The machine does not currently have the ci.role.test label

**Comment by adamfarley** [comment]
Ok, here's a list of all of the multicast tests that were associated with this issue, with the results by VM, version, and machine. 

**build-marist-rhel77-s390x-1x**
java/net/MulticastSocket:
| Test Name                    | 8HS               | 11HS             | 16HS             | 8J9               | 11J9             | 16J9              |
| ----------------------- | -------------- | ------------- | -------------- | ------------- | ------------- | ------------- |
| Promiscuous.java          | [Pass][1MP1] | [Pass][1MP2] | [Pass][1MP3] | [Pass][1MP4] | [Pass][1MP5] | [Pass][1MP6] |
| PromiscuousIPv6.java   | N/A               | N/A               | [Pass][1MI3]  | N/A               | N/A               | [Pass][1MI6]  |
| SetLoopbackMode.java | [Fail][1S1]      | [Fail][1S2]      | [Fail][1S3]      | [Fail][1S4]       | [Fail][1S5]      | [Fail][1S6]      |
| Test.java                       | [Fail][1T1]      | [Fail][1T2]      | [Fail][1T3]       | [Fail][1T4]       | [Fail][1T5]      | [Fail][1T6]      |

java/nio/channels/DatagramChannel:
| Test Name                                 | 8HS              | 11HS            | 16HS           | 8J9               | 11J9              | 16J9             |
| -------------------------------- | ------------- | ------------- | ------------ | ------------- | ------------- | ------------- |
| MulticastSendReceiveTests.java  | [Fail][1M1]    | [Fail][1M2]    | [Fail][1M3]    | [Fail][1M4]    | [Fail][1M5]    | [Fail][1M6]    |
| Promiscuous.java                       | [Pass][1DP1] | [Pass][1DP2] | [Pass][1DP3] | [Pass][1DP4] | [Pass][1DP5] | [Pass][1DP6] |
| PromiscuousIPv6.java                | N/A              | N/A               | [Pass][1DI3]  | N/A              | N/A              | [Pass][1DI6]  |


[//]: # "build-marist-rhel77-s390x-1x"
[//]: # "java/net/MulticastSocket/Promiscuous.java"
[1MP1]: https://ci.adoptopenjdk.net/job/Grinder/812/
[1MP2]: https://ci.adoptopenjdk.net/job/Grinder/813/
[1MP3]: https://ci.adoptopenjdk.net/job/Grinder/828/
[1MP4]: https://ci.adoptopenjdk.net/job/Grinder/814/
[1MP5]: https://ci.adoptopenjdk.net/job/Grinder/816/
[1MP6]: https://ci.adoptopenjdk.net/job/Grinder/829/

[//]: # "java/net/MulticastSocket/PromiscuousIPv6.java"
[1MI3]: https://ci.adoptopenjdk.net/job/Grinder/826/
[1MI6]: https://ci.adoptopenjdk.net/job/Grinder/827/

[//]: # "java/net/MulticastSocket/SetLoopbackMode.java"
[1S1]: https://ci.adoptopenjdk.net/job/Grinder/830/
[1S2]: https://ci.adoptopenjdk.net/job/Grinder/836/
[1S3]: https://ci.adoptopenjdk.net/job/Grinder/837/
[1S4]: https://ci.adoptopenjdk.net/job/Grinder/833/
[1S5]: https://ci.adoptopenjdk.net/job/Grinder/834/
[1S6]: https://ci.adoptopenjdk.net/job/Grinder/835/

[//]: # "java/net/MulticastSocket/Test.java"
[1T1]: https://ci.adoptopenjdk.net/job/Grinder/838/
[1T2]: https://ci.adoptopenjdk.net/job/Grinder/840/
[1T3]: https://ci.adoptopenjdk.net/job/Grinder/841/
[1T4]: https://ci.adoptopenjdk.net/job/Grinder/842/
[1T5]: https://ci.adoptopenjdk.net/job/Grinder/843/
[1T6]: https://ci.adoptopenjdk.net/job/Grinder/844/

[//]: # "java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java"
[1M1]: https://ci.adoptopenjdk.net/job/Grinder/845/
[1M2]: https://ci.adoptopenjdk.net/job/Grinder/846/
[1M3]: https://ci.adoptopenjdk.net/job/Grinder/847/
[1M4]: https://ci.adoptopenjdk.net/job/Grinder/848/
[1M5]: https://ci.adoptopenjdk.net/job/Grinder/849/
[1M6]: https://ci.adoptopenjdk.net/job/Grinder/850/

[//]: # "java/nio/channels/DatagramChannel/Promiscuous.java"
[1DP1]: https://ci.adoptopenjdk.net/job/Grinder/851/
[1DP2]: https://ci.adoptopenjdk.net/job/Grinder/853/
[1DP3]: https://ci.adoptopenjdk.net/job/Grinder/854/
[1DP4]: https://ci.adoptopenjdk.net/job/Grinder/855/
[1DP5]: https://ci.adoptopenjdk.net/job/Grinder/856/
[1DP6]: https://ci.adoptopenjdk.net/job/Grinder/857/

[//]: # "java/nio/channels/DatagramChannel/PromiscuousIPv6.java"
[1DI3]: https://ci.adoptopenjdk.net/job/Grinder/858/
[1DI6]: https://ci.adoptopenjdk.net/job/Grinder/859/


**build-marist-rhel77-s390x-2**
java/net/MulticastSocket:
| Test Name                     | 8HS              | 11HS            | 16HS              | 8J9               | 11J9              | 16J9             |
| ------------------------ | ------------- | ------------- | -------------- | ------------- | ------------- | ------------- |
| Promiscuous.java          | [Pass][2MP1] | [Pass][2MP2] | [Pass][2MP3] | [Pass][2MP4] | [Pass][2MP5] | [Pass][2MP6] |
| PromiscuousIPv6.java   | N/A               | N/A               | [Pass][2MI3]  | N/A               | N/A               | [Pass][2MI6]  |
| SetLoopbackMode.java | [Fail][2S1]      | [Fail][2S2]      | [Fail][2S3]       | [Fail][2S4]      | [Fail][2S5]      | [Fail][2S6]      |
| Test.java                        | [Wait][2T1]    | [Wait][2T2]    | [Wait][2T3]     | [Wait][2T4]    | [Wait][2T5]     | [Wait][2T6]    |

java/nio/channels/DatagramChannel:
| Test Name                                | 8HS              | 11HS            | 16HS            | 8J9               | 11J9            | 16J9               |
| ------------------------------- | ------------- | ------------- | ------------- | ------------- | ------------ | -------------- |
| MulticastSendReceiveTests.java | [Wait][2M1]  | [Wait][2M2]   | [Wait][2M3]   | [Wait][2M4]  | [Wait][2M5] | [Wait][2M6]   |
| Promiscuous.java                      | [Wait][2DP1] | [Wait][2DP2] | [Wait][2DP3] | [Wait][2DP4] | [Wait][2DP5] | [Wait][2DP6] |
| PromiscuousIPv6.java               | N/A               | N/A              | [Wait][2DI3]  | N/A              | N/A              | [Wait][2DI6]  |

[//]: # "build-marist-rhel77-s390x-2"
[//]: # "java/net/MulticastSocket/Promiscuous.java"
[2MP1]: https://ci.adoptopenjdk.net/job/Grinder/860/
[2MP2]: https://ci.adoptopenjdk.net/job/Grinder/861/
[2MP3]: https://ci.adoptopenjdk.net/job/Grinder/862/
[2MP4]: https://ci.adoptopenjdk.net/job/Grinder/863/
[2MP5]: https://ci.adoptopenjdk.net/job/Grinder/864/
[2MP6]: https://ci.adoptopenjdk.net/job/Grinder/865/

[//]: # "java/net/MulticastSocket/PromiscuousIPv6.java"
[2MI3]: https://ci.adoptopenjdk.net/job/Grinder/866/
[2MI6]: https://ci.adoptopenjdk.net/job/Grinder/867/

[//]: # "java/net/MulticastSocket/SetLoopbackMode.java"
[2S1]: https://ci.adoptopenjdk.net/job/Grinder/868/
[2S2]: https://ci.adoptopenjdk.net/job/Grinder/869/
[2S3]: https://ci.adoptopenjdk.net/job/Grinder/870/
[2S4]: https://ci.adoptopenjdk.net/job/Grinder/871/
[2S5]: https://ci.adoptopenjdk.net/job/Grinder/872/
[2S6]: https://ci.adoptopenjdk.net/job/Grinder/873/

[//]: # "java/net/MulticastSocket/Test.java"
[2T1]: https://ci.adoptopenjdk.net/job/Grinder/874/
[2T2]: https://ci.adoptopenjdk.net/job/Grinder/875/
[2T3]: https://ci.adoptopenjdk.net/job/Grinder/876/
[2T4]: https://ci.adoptopenjdk.net/job/Grinder/877/
[2T5]: https://ci.adoptopenjdk.net/job/Grinder/878/
[2T6]: https://ci.adoptopenjdk.net/job/Grinder/879/

[//]: # "java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java"
[2M1]: https://ci.adoptopenjdk.net/job/Grinder/880/
[2M2]: https://ci.adoptopenjdk.net/job/Grinder/881/
[2M3]: https://ci.adoptopenjdk.net/job/Grinder/882/
[2M4]: https://ci.adoptopenjdk.net/job/Grinder/883/
[2M5]: https://ci.adoptopenjdk.net/job/Grinder/884/
[2M6]: https://ci.adoptopenjdk.net/job/Grinder/885/

[//]: # "java/nio/channels/DatagramChannel/Promiscuous.java"
[2DP1]: https://ci.adoptopenjdk.net/job/Grinder/886/
[2DP2]: https://ci.adoptopenjdk.net/job/Grinder/887/
[2DP3]: https://ci.adoptopenjdk.net/job/Grinder/888/
[2DP4]: https://ci.adoptopenjdk.net/job/Grinder/889/
[2DP5]: https://ci.adoptopenjdk.net/job/Grinder/890/
[2DP6]: https://ci.adoptopenjdk.net/job/Grinder/891/

[//]: # "java/nio/channels/DatagramChannel/PromiscuousIPv6.java"
[2DI3]: https://ci.adoptopenjdk.net/job/Grinder/892/
[2DI6]: https://ci.adoptopenjdk.net/job/Grinder/893/

**Comment by sxa** [comment]
This needs to be re-tested in light of the Marist machines having been rebuilt in the last few months.

**Comment by sxa** [comment]
Will link this to other issues as an "umbrella" for Marist/s390x networking failures

**Comment by sxa** [comment]
Related issues:
- https://github.com/adoptium/infrastructure/issues/2807
- https://github.com/adoptium/infrastructure/issues/3189
- https://github.com/adoptium/infrastructure/issues/2451
