### ISSUE TITLE
External tests build consistently failed on machine test-softlayer-ubuntu1604-x64-1 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#701]
External tests build consistently failed on machine test-softlayer-ubuntu1604-x64-1  with msg 

```
[Pipeline] End of Pipeline
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-softlayer-ubuntu1604-x64-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1072)
		at hudson.FilePath.act(FilePath.java:1061)
		at hudson.FilePath.mkdirs(FilePath.java:1246)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:821)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1169)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.nio.file.AccessDeniedException: /home/jenkins/workspace/openjdk8_j9_externaltest_x86-64_linux/openjdk-tests
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at hudson.FilePath.mkdirs(FilePath.java:3273)
	at hudson.FilePath.access$1300(FilePath.java:213)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1254)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1250)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3086)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

```

https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_j9_externaltest_x86-64_linux/346/console

Recently there is one build passed on this machine https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_hs_externaltest_extended_x86-64_linux/153/consoleFull

Not sure any configuration has changed or not? External tests required machine with label '**sw.tool.docker**'. Need to figure out what is the difference between this machine and others with same labels. For now if it fails again on this machine we will need to disable or remove the docker label from this machine

**Comment by karianna** [comment]
This will need someone at IBM with Softlayer access to resolve

**Comment by karianna** [comment]
Seems to be resolved now.

**Comment by tellison** [comment]
I'll admit that I ignore the system warnings coming to me from Softlayer; it may have been a planned outage I didn't pass on.  If there are any substantial outages I'll go and read the messages properly!

**Comment by sophia-guo** [comment]
@karianna  I could see same failure happened today.  https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_j9_externaltest_x86-64_linux/348/console.  If there is a planned outage, probably we would just disable it?

**Comment by karianna** [comment]
> @karianna I could see same failure happened today. https://ci.adoptopenjdk.net/view/Test_external/job/openjdk8_j9_externaltest_x86-64_linux/348/console. If there is a planned outage, probably we would just disable it?

I'm not sure if this is a planned outage issue, seems to be more of a regular Jenkins Agent/permissions issue.  If we can get full Adopt staff access to those hosts I can take a look, else it will require an IBM engineer to login and see if they can see what's causing the permissions issue

**Comment by sophia-guo** [comment]
Yes, agreed. This is a permission issue similar to windows one https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/706.  Though not sure why|how it happened. Now it only affects the workspace openjdk8_j9_externaltest_x86-64_linux , openjdk8_j9_externaltest_extended_x86-64_linux. 

@ShelleyLambert do you have idea who has the permission? We'd like to manually deleted the folder /home/jenkins/workspace/openjdk8_j9_externaltest_x86-64_linux/
and 
/home/jenkins/workspace/openjdk8_j9_externaltest_extended_x86-64_linux/

**Comment by smlambert** [comment]
@sxa555 - do you have access to test-softlayer-ubuntu1604-x64-1   to clean up some directories that we can't delete logged on with Jenkins id ?

**Comment by sxa555** [comment]
@sophia-guo @smlambert I have cleared  up `/home/jenkins/workspace/openjdk8_j9_externaltest_x86-64_linux/` and `/home/jenkins/workspace/openjdk8_j9_externaltest_extended_x86-64_linux/` from `test-softlayer-ubuntu1604-x64-1`

**Comment by smlambert** [comment]
thanks @sxa555 !
