### ISSUE TITLE
Connectivity and file access problems reported for test machine test-azure-win2012r2-x64-1 - preventing JDK12 testing

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-infrastructure#736]
Consistently fails with ...

```
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 13.68.134.204/13.68.134.204:51034
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1072)
		at hudson.FilePath.act(FilePath.java:1061)
		at hudson.FilePath.deleteContents(FilePath.java:1283)
		at hudson.plugins.git.extensions.impl.WipeWorkspace.beforeCheckout(WipeWorkspace.java:30)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1172)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\openjdk12_j9_openjdktest_x86-64_windows\openjdk-tests\TestConfig\test_output_15526538561209\jdk_util_0
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.nio.file.Files.readAttributes(Unknown Source)
	at hudson.Util.isSymlink(Util.java:531)
	at hudson.FilePath.deleteRecursive(FilePath.java:1295)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1314)
	at hudson.FilePath.deleteRecursive(FilePath.java:1296)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1314)
	at hudson.FilePath.deleteRecursive(FilePath.java:1296)
	at hudson.FilePath.deleteContentsRecursive(FilePath.java:1314)
	at hudson.FilePath.access$1800(FilePath.java:213)
	at hudson.FilePath$DeleteContents.invoke(FilePath.java:1289)
	at hudson.FilePath$DeleteContents.invoke(FilePath.java:1285)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3086)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Unknown Source)
```

This is the only Windows test machine currently available.

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_windows shows the same failures for the last 5 days of attempts. We consequently have no test results for the release candidate build and little recent history for triaging purposes.

Curiously, no such problems for 11 and 8 pipelines (https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_windows and https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows).

**Comment by ben-walsh** [comment]
Appears to be consistently failing to access directory C:\Users\jenkins\workspace\openjdk12_j9_openjdktest_x86-64_windows\openjdk-tests\TestConfig\test_output_15526538561209\jdk_util_0 during cleanup phase each time and this is sufficient to prevent execution of any tests.

Aside resolving this specific problem rapidly, by force deleting the directory in question using an administrator session, investigation should be made to determine how the directory in question got into this state.

Consideration should be given to whether such a failure should prevent tests being executed.

**Comment by ben-walsh** [comment]
Job before these is reporting failures to clean up files - possibly the trigger ? - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk12_j9_openjdktest_x86-64_windows/9/consoleText

**Comment by sxa555** [comment]
That's a new (to me) one ...
![image](https://user-images.githubusercontent.com/6487691/54622379-6a775780-4a61-11e9-84a9-e0230199a1c0.png)

**Comment by sxa555** [comment]
The `jdk_util_0` subdirectory is in a similar state (same message as above) but doesn't even have an owner somehow (!) and I'm struggling to do anything with it
![image](https://user-images.githubusercontent.com/6487691/54623586-bb884b00-4a63-11e9-83c3-28966a0dfc9e.png)

**Comment by sxa555** [comment]
Seems it was in an odd state due to a java process that was holding something in it - have now deleted them - not seen anything quite like this on Windows before but it should now be resolved.
