### ISSUE TITLE
Builds failing on Linux/ppc64le build machines due to disk space being exceeded

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-infrastructure#815]
e.g. from https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-openj9/265/console
```
Running on build-osuosl-centos74-ppc64le-2 in /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-ppc64le-openj9
[Pipeline] {
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] checkout
No credentials specified
Fetching changes from the remote Git repository
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/AdoptOpenJDK/openjdk-build.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:904)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1144)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1175)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
```

**Comment by gdams** [comment]
We might be able to get a big machine on softlayer and chop it up to add some more ppc64le machines.

**Comment by sxa555** [comment]
@gdams Do softlayer have ppc64le?

**Comment by sxa555** [comment]
build-osuosl-centos74-ppc64le-2 upgraded to 400Gb now, `-1` will be upgraded hopefully later today

**Comment by sxa555** [comment]
Both at 400Gb - closing.
