### ISSUE TITLE
Issues about test-marist-sles12-s390x-1 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-infrastructure#816]
[test-marist-sles12-s390x-1](https://ci.adoptopenjdk.net/computer/test-marist-sles12-s390x-1/)

Is this a test machine? Could the label 'build-marist-s390x-sles-12' be removed ( confusing) ?

Running test and got 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1723/console
```
16:02:01  ant -f ./src/build_envInfo.xml -DTEST_JDK_HOME=/data/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
16:02:01  Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tools/ant/launch/Launcher : Unsupported major.minor version 52.0
16:02:01  	at java.lang.ClassLoader.defineClass1(Native Method)
16:02:01  	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
16:02:01  	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
16:02:01  	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
16:02:01  	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
16:02:01  	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
16:02:01  	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
16:02:01  	at java.security.AccessController.doPrivileged(Native Method)
16:02:01  	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
16:02:01  	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
16:02:01  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
16:02:01  	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
16:02:01  	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

```

We'd like to enable this machine for test when all issues are fixed

**Comment by sophia-guo** [comment]
Is this the reason https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/765#issuecomment-484566440? @sxa555

**Comment by sxa555** [comment]
That is part of the de-duplication effort, yes. If there's an issue please reopen the other issue so we keep all the issues regarding donating that machine to testing in one place.
