### ISSUE TITLE
Poor connectivity to test-macincloud-macos1010-x64-1

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-infrastructure#905]
Cannot reliably launch jenkins agent on it. packet loss in horrendous
https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-x64-1/

```
[sxa@sxat470p sbin]$ ping 74.80.250.151
PING 74.80.250.151 (74.80.250.151) 56(84) bytes of data.
64 bytes from 74.80.250.151: icmp_seq=3 ttl=50 time=167 ms
64 bytes from 74.80.250.151: icmp_seq=4 ttl=50 time=177 ms
64 bytes from 74.80.250.151: icmp_seq=29 ttl=50 time=164 ms
64 bytes from 74.80.250.151: icmp_seq=62 ttl=50 time=245 ms
64 bytes from 74.80.250.151: icmp_seq=63 ttl=50 time=168 ms
```

Jenkins startup log:
```
[08/20/19 15:16:06] [SSH] Checking java version of java
[08/20/19 15:16:07] [SSH] java -version returned 1.8.0_131.
[08/20/19 15:16:07] [SSH] Starting sftp client.
[08/20/19 15:16:07] [SSH] Copying latest remoting.jar...

ERROR: null
java.util.concurrent.CancellationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at hudson.plugins.sshslaves.SSHLauncher.launch(SSHLauncher.java:475)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[08/20/19 15:22:28] Launch failed - cleaning up connection
java.io.IOException: Could not copy remoting.jar into '/Users/jenkins' on agent
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:696)
	at hudson.plugins.sshslaves.SSHLauncher.access$300(SSHLauncher.java:113)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:439)
	at hudson.plugins.sshslaves.SSHLauncher$1.call(SSHLauncher.java:406)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.InterruptedIOException
	at com.trilead.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:935)
	at com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:58)
	at com.trilead.ssh2.SFTPv3Client.readBytes(SFTPv3Client.java:215)
	at com.trilead.ssh2.SFTPv3Client.receiveMessage(SFTPv3Client.java:240)
	at com.trilead.ssh2.SFTPv3Client.read(SFTPv3Client.java:1249)
	at com.trilead.ssh2.jenkins.SFTPClient$SFTPInputStream.read(SFTPClient.java:172)
	at java.io.InputStream.read(InputStream.java:101)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:193)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:236)
	at hudson.plugins.sshslaves.SSHLauncher.readInputStreamIntoByteArrayAndClose(SSHLauncher.java:754)
	at hudson.plugins.sshslaves.SSHLauncher.copyAgentJar(SSHLauncher.java:665)
	... 7 more
[08/20/19 15:22:28] [SSH] Connection closed.

SSHLauncher{host='74.80.250.151', port=22, credentialsId='b8101a03-36e8-4687-a722-d48ad48acd5c', jvmOptions='', javaPath='', prefixStartSlaveCmd='', suffixStartSlaveCmd='', launchTimeoutSeconds=400, maxNumRetries=15, retryWaitTime=20, sshHostKeyVerificationStrategy=hudson.plugins.sshslaves.verifiers.NonVerifyingKeyVerificationStrategy, tcpNoDelay=true, trackCredentials=true}
[08/20/19 15:23:48] [SSH] Opening SSH connection to 74.80.250.151:22.

```

**Comment by Willsparker** [comment]
Err- did you mean to remove the labels off the macstadium-arm64 ones too (I'm fully aware this issue is over a year old, so if not, I may just put the labels back on)

**Comment by sxa** [comment]
@Willsparker Not sure what youre previous comment was related to but the machine that this issue was raised for looks ok now, therefore closing.

**Comment by Willsparker** [comment]
No clue! Maybe that comment was meant to be on a different issue ... hmm
