### ISSUE TITLE
Inconsistency between Mac 10.13 and 10.14 machines at hyc

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#967]
See: https://github.com/eclipse/openj9/issues/6035#issuecomment-543735755

Small group of 5 java net/nio tests that fail on mac 10.14 but not 10.11 machines at https://hyc-runtimes-jenkins.swg-devops.com. This is on both hotspot and openj9. When tested at https://ci.adoptopenjdk.net, both the 10.13 and 10.14 machines pass these tests, so there must be a missing dependency or some inconsistency between the two sets of machines.

Example output:
```
15:53:48  java.net.NoRouteToHostException: No route to host (Host unreachable)
15:53:48  	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
15:53:48  	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
15:53:48  	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
15:53:48  	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
15:53:48  	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
15:53:48  	at java.base/java.net.Socket.connect(Socket.java:591)
15:53:48  	at java.base/java.net.Socket.connect(Socket.java:540)
15:53:48  	at java.base/java.net.Socket.<init>(Socket.java:436)
15:53:48  	at java.base/java.net.Socket.<init>(Socket.java:246)
15:53:48  	at CheckJNI.main(CheckJNI.java:67)
15:53:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:53:48  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:53:48  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:53:48  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:53:48  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:53:48  	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by junyzheng** [comment]
Just wondering what's the missing dependencies?
