### ISSUE TITLE
JTReg test inconsistency on ci.adoptopenjdk.net linux machines

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-infrastructure#970]
Test: java/rmi/dgc/retryDirtyCalls/RetryDirtyCalls.java
Reproduce: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/rmi/dgc/retryDirtyCalls/RetryDirtyCalls.java&TARGET=jdk_custom_0&LABEL=test-scaleway-ubuntu1604-x64-1

Test produces this output when ran on test-scaleway-ubuntu1604-x64-1. Passes on test-godaddy-ubuntu1604-x64-1
```
09:26:55  STDOUT:
09:26:55  STDERR:
09:26:55  
09:26:55  Regression test for bug 4268258
09:26:55  
09:26:55  java.lang.RuntimeException: remote object unreferenced
09:26:55  	at RetryDirtyCalls.main(RetryDirtyCalls.java:127)
09:26:55  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:26:55  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:26:55  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:26:55  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
09:26:55  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:26:55  	at java.base/java.lang.Thread.run(Thread.java:832)
09:26:55  java.lang.RuntimeException: TEST FAILED: java.lang.RuntimeException: remote object unreferenced
09:26:55  	at RetryDirtyCalls.main(RetryDirtyCalls.java:148)
09:26:55  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:26:55  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:26:55  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:26:55  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
09:26:55  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
09:26:55  	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by adam-thorpe** [comment]
Test is intermittent so this information is wrong, it fails on both machines
